// frontend/app/src/pages/Models.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <q-page class="flex-center">
    <div v-if="selectedModel.file == ''" class="row justify-center full-width q-pa-md q-my-lg">
      <q-card style="width: 400px">
        <q-card-section v-if="modelList.length > 0">
          <div class="text-h6" style="text-align: center">Select existing model</div>
        </q-card-section>
        <q-select v-if="modelList.length > 0" dense class="q-pa-md" :options="modelList" option-label="title"
          v-model="selectedModel" label="Model" standout @update:model-value="selectModel"></q-select>

        <q-separator inset />
        <q-card-section v-if="modelList.length > 0">
          <div class="text-h6" style="text-align: center">Or</div>
        </q-card-section>
        <q-btn flat icon="fas fa-add" @click="dialogAddModel = true" :disable="store.TRIAL" style="width: 390px"
          label="Add a new Model">
          <q-tooltip v-if="!store.TRIAL">
            Disabled in trial version
          </q-tooltip>
        </q-btn>
      </q-card>
    </div>
    <div v-if="selectedModel.file != ''">
      <q-btn flat icon="fas fa-add" @click="dialogAddModel = true" :disable="store.TRIAL">
        <q-tooltip>
          <div v-if="!store.TRIAL">Add Model</div>
          <div v-if="store.TRIAL">Disabled in trial version</div>
        </q-tooltip>
      </q-btn>
      <q-select class="q-pa-sm" :options="modelList" option-label="title" v-model="selectedModel" label="Model" standout
        dense @update:model-value="selectModel"></q-select>

      <q-splitter v-model="verticalSplitterModel" class="body" :limits="[0, 100]" style="height:calc(100vh - 225px);">
        <template v-slot:before>
          <q-resize-observer @resize="onResizeBefore" :debounce="0" />
          <div v-if="sourceCode != ''">
            <div class="row">
              <q-btn class="q-ma-sm" color="primary" label="Save" @click="_saveModel" />
              <q-btn class="q-ma-sm" color="negative" label="Delete" @click="dialogDeleteModel = true" />
            </div>
            <q-scroll-area :style="{ 'height': modelHeight }">
              <prism-editor class="my-editor" v-model="sourceCode" :highlight="highlighter" line-numbers></prism-editor>
            </q-scroll-area>
          </div>
        </template>

        <template v-slot:after>
          <q-resize-observer @resize="onResizeAfter" :debounce="0" />
          <div v-if="Object.keys(config).length !== 0">
            <div class="row">
              <q-btn class="q-ma-sm" color="primary" label="Save" @click="_saveConfig" />
            </div>
            <q-scroll-area :style="{ 'height': configHeight }">
              <vue-json-pretty :data="config" :editable=true />
              <!-- <JsonEditorVue v-model="config" :mainMenuBar=false :navigationBar=false :statusBar=false :readOnly=false
              v-bind="{/* local props & attrs */ }" /> -->
            </q-scroll-area>
          </div>
        </template>
      </q-splitter>
    </div>

    <q-dialog v-model="dialogAddModel" persistent max-width="800">
      <q-card>
        <q-card-section>
          <div class="text-h6">Add Model</div>
        </q-card-section>

        <q-card-section class="q-pt-none">
          <q-input dense v-model="newModelName" label="Model Name" />
          <q-input dense v-model="description" label="Description" />
        </q-card-section>

        <q-card-actions align="right">
          <q-btn flat label="Create" color="primary" v-close-popup @click="_addModel" />
          <q-btn flat label="Cancel" color="primary" v-close-popup />
        </q-card-actions>
      </q-card>
    </q-dialog>

    <q-dialog v-model="dialogDeleteModel" persistent max-width="800">
      <q-card>
        <q-card-section>
          <div class="text-h6">Are you sure you want to delete {{ selectedModel.title }}?</div>
        </q-card-section>
        <q-card-actions align="right">
          <q-btn flat label="Delete" color="negative" v-close-popup @click="_deleteModel" />
          <q-btn flat label="Cancel" color="primary" v-close-popup />
        </q-card-actions>
      </q-card>
    </q-dialog>
  </q-page>
</template>

<script lang="ts">

import { useDefaultStore } from 'src/stores/default-store';
import { PrismEditor } from 'vue-prism-editor';
import 'vue-prism-editor/dist/prismeditor.min.css'; // import the styles somewhere
//@ts-expect-error Bla
import { highlight, languages } from 'prismjs/components/prism-core';
import 'prismjs/components/prism-python';
import 'prismjs/themes/prism-tomorrow.css'; // import syntax highlighting styles
// import JsonEditorVue from 'json-editor-vue'
import VueJsonPretty from 'vue-json-pretty';
import 'vue-json-pretty/lib/styles.css';

import { getOwnModels, getOwnModelFile, getConfig, saveConfig, saveModelFile, addModel, deleteModelFile } from '../client';
import type { GetOwnModelsResponse, ModelData } from 'src/client';

export default {
  name: 'CuratorPage',

  components: {
    PrismEditor,
    VueJsonPretty
    // JsonEditorVue
  },
  setup() {
    const store = useDefaultStore();
    return {
      store
    }
  },
  data() {
    return {
      modelList: [] as GetOwnModelsResponse,
      selectedModel: {
        title: '',
        file: '',
      },

      dialogAddModel: false,
      dialogDeleteModel: false,
      newModelName: '',
      description: '',

      sourceCode: '',
      config: {} as ModelData,
      verticalSplitterModel: 50,

      modelHeight: '400px',
      configHeight: '400px',
    };
  },
  methods: {
    onResizeBefore(size: object) {
      if ('height' in size) {
        this.modelHeight = size.height - 60 + 'px'
      }
    },
    onResizeAfter(size: object) {
      if ('height' in size) {
        this.configHeight = size.height - 60 + 'px'
      }
    },
    highlighter(code: string) {
      return highlight(code, languages.py); // languages.<insert language> to return html with markup
    },
    async _addModel() {
      const response = await addModel({
        modelName: this.newModelName,
        description: this.description
      })
      this.selectedModel.title = this.newModelName
      this.selectedModel.file = response
      await this._getModels()
      await this.selectModel()
    },
    async _getModels() {
      const response = await getOwnModels({
        verify: true
      })
      this.modelList = response;
    },
    async selectModel() {
      const response = await getOwnModelFile({
        modelFile: this.selectedModel.file
      })
      this.sourceCode = response
      const config = await getConfig({
        configFile: this.selectedModel.file
      })
      this.config = config as ModelData;
    },
    async _saveModel() {
      await saveModelFile({
        modelFile: this.selectedModel.file,
        sourceCode: this.sourceCode
      }).then(() => this.$q.notify({
        message: 'Model saved',
      })).catch((error) => {
        console.log(error.body.detail)
        this.$q.notify({
          type: 'negative',
          message: error.body.detail
        })
      })
    },
    async _saveConfig() {
      await saveConfig({
        configFile: this.selectedModel.file,
        requestBody: this.config
      }).then(() => this.$q.notify({
        message: 'Config saved',
      })).catch((error) => {
        console.log(error.body.detail)
        for (let i = 0; i < error.body.detail.length; i++) {
          this.$q.notify({
            type: 'negative',
            message: error.body.detail[i].msg + '\n' + error.body.detail[i].loc
          })
        }
      })
    },
    async _deleteModel() {
      await deleteModelFile({
        modelName: this.selectedModel.file,
      }).then(() => {
        this.$q.notify({
          message: 'Model deleted',
        })
        this.sourceCode = ''
        this.config = {}
      })
      await this._getModels()
    }
  },
  async mounted() {
    await this._getModels()
  },
  watch: {
  }
};
</script>
<style>
/* required class */
.my-editor {
  /* we dont use `language-` classes anymore so thats why we need to add background and text color manually */
  background: #2d2d2d;
  color: #ccc;

  /* you must provide font-family font-size line-height. Example: */
  font-family: Fira code, Fira Mono, Consolas, Menlo, Courier, monospace;
  font-size: 14px;
  line-height: 1.5;
  padding: 5px;
}

/* optional class for removing the outline */
.prism-editor__textarea:focus {
  outline: none;
}
</style>

// src/routes/models/+page.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { Dialog } from 'bits-ui';
  import { Plus } from 'lucide-svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { notify } from '$lib/utils/notify';
  import {
    getOwnModels,
    getOwnModelFile,
    getConfig,
    saveConfig,
    saveModelFile,
    addModel,
    deleteModelFile
  } from '$lib/client';
  import type { GetOwnModelsResponse, ModelData } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Card from '$lib/components/ui/Card.svelte';
  import CodeBlock from '$lib/components/views/CodeBlock.svelte';
  import JsonView from '$lib/components/views/JsonView.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';

  let modelList = $state<GetOwnModelsResponse>([]);
  let selectedModel = $state({ title: '', file: '' });

  let dialogAddModel = $state(false);
  let dialogDeleteModel = $state(false);
  let newModelName = $state('');
  let description = $state('');

  let sourceCode = $state('');
  let config = $state<ModelData | Record<string, never>>({});

  async function fetchModels() {
    modelList = await getOwnModels({ verify: true });
  }

  async function selectModel() {
    if (!selectedModel.file) return;
    try {
      sourceCode = (await getOwnModelFile({ modelFile: selectedModel.file })) as unknown as string;
      config = (await getConfig({ configFile: selectedModel.file })) as ModelData;
      viewStore.jsonData = config;
    } catch (error) {
      notify.apiError(error);
    }
  }

  async function addNewModel() {
    dialogAddModel = false;
    try {
      const response = await addModel({ modelName: newModelName, description });
      selectedModel = { title: newModelName, file: response as unknown as string };
      await fetchModels();
      await selectModel();
    } catch (error) {
      notify.apiError(error);
    }
  }

  async function saveModel() {
    try {
      await saveModelFile({ modelFile: selectedModel.file, sourceCode });
      notify.positive('Model saved');
    } catch (error) {
      notify.apiError(error);
    }
  }

  async function saveModelConfig() {
    try {
      await saveConfig({ configFile: selectedModel.file, requestBody: config as ModelData });
      notify.positive('Config saved');
    } catch (error: unknown) {
      const err = error as { body?: { detail?: { msg: string; loc: string[] }[] } };
      for (const d of err.body?.detail ?? []) {
        notify.negative(`${d.msg}\n${d.loc}`);
      }
    }
  }

  async function confirmDeleteModel() {
    dialogDeleteModel = false;
    try {
      await deleteModelFile({ modelName: selectedModel.file });
      notify.positive('Model deleted');
      sourceCode = '';
      config = {};
    } catch (error) {
      notify.apiError(error);
    }
    await fetchModels();
  }

  onMount(fetchModels);
</script>

<svelte:head>
  <title>Models — PeriHub</title>
</svelte:head>

<div class="mx-auto max-w-6xl px-4 py-8">
  {#if !selectedModel.file}
    <div class="flex justify-center">
      <Card class="w-full max-w-md p-6 text-center">
        {#if modelList.length > 0}
          <h2 class="mb-3 text-lg font-semibold">Select existing model</h2>
          <Select
            value={selectedModel.file}
            onchange={(e) => {
              const file = (e.target as HTMLSelectElement).value;
              const m = modelList.find((x) => x.file === file);
              if (m) {
                selectedModel = m as { title: string; file: string };
                selectModel();
              }
            }}
          >
            <option value="">— choose a model —</option>
            {#each modelList as model, modelIdx (model.file ?? modelIdx)}
              <option value={model.file}>{model.title}</option>
            {/each}
          </Select>
          <div class="border-border my-4 border-t"></div>
          <p class="text-muted-foreground mb-3 text-sm">Or</p>
        {/if}
        <Button
          class="w-full"
          disabled={defaultStore.trial}
          onclick={() => (dialogAddModel = true)}
          title={defaultStore.trial ? 'Disabled in trial version' : undefined}
        >
          <Plus class="h-4 w-4" /> Add a new Model
        </Button>
      </Card>
    </div>
  {:else}
    <div class="mb-4 flex flex-wrap items-center gap-3">
      <Button
        variant="ghost"
        size="icon"
        disabled={defaultStore.trial}
        onclick={() => (dialogAddModel = true)}
      >
        <Plus class="h-4 w-4" />
      </Button>
      <Select
        class="max-w-xs"
        value={selectedModel.file}
        onchange={(e) => {
          const file = (e.target as HTMLSelectElement).value;
          const m = modelList.find((x) => x.file === file);
          if (m) {
            selectedModel = m as { title: string; file: string };
            selectModel();
          }
        }}
      >
        {#each modelList as model, modelIdx (model.file ?? modelIdx)}
          <option value={model.file}>{model.title}</option>
        {/each}
      </Select>
    </div>

    <div class="grid grid-cols-1 gap-4 lg:grid-cols-2">
      {#if sourceCode !== ''}
        <div>
          <div class="mb-2 flex gap-2">
            <Button onclick={saveModel}>Save</Button>
            <Button variant="destructive" onclick={() => (dialogDeleteModel = true)}>Delete</Button>
          </div>
          <div class="border-border h-[calc(100vh-320px)] overflow-auto rounded-md border">
            <CodeBlock bind:value={sourceCode} language="python" />
          </div>
        </div>
      {/if}

      {#if Object.keys(config).length !== 0}
        <div>
          <div class="mb-2">
            <Button onclick={saveModelConfig}>Save</Button>
          </div>
          <div class="border-border h-[calc(100vh-320px)] overflow-auto rounded-md border">
            <JsonView />
          </div>
        </div>
      {/if}
    </div>
  {/if}
</div>

<Dialog.Root bind:open={dialogAddModel}>
  <Dialog.Portal>
    <Dialog.Overlay class="fixed inset-0 z-50 bg-black/50" />
    <Dialog.Content
      class="border-border bg-card fixed top-1/2 left-1/2 z-50 w-[min(92vw,26rem)] -translate-x-1/2 -translate-y-1/2 rounded-xl border p-5 shadow-lg"
    >
      <Dialog.Title class="mb-3 text-lg font-semibold">Add Model</Dialog.Title>
      <div class="space-y-3">
        <div class="space-y-1">
          <Label for="new-model-name">Model Name</Label>
          <Input id="new-model-name" bind:value={newModelName} />
        </div>
        <div class="space-y-1">
          <Label for="new-model-desc">Description</Label>
          <Input id="new-model-desc" bind:value={description} />
        </div>
      </div>
      <div class="mt-4 flex justify-end gap-2">
        <Button variant="ghost" onclick={() => (dialogAddModel = false)}>Cancel</Button>
        <Button onclick={addNewModel}>Create</Button>
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>

<Dialog.Root bind:open={dialogDeleteModel}>
  <Dialog.Portal>
    <Dialog.Overlay class="fixed inset-0 z-50 bg-black/50" />
    <Dialog.Content
      class="border-border bg-card fixed top-1/2 left-1/2 z-50 w-[min(92vw,26rem)] -translate-x-1/2 -translate-y-1/2 rounded-xl border p-5 shadow-lg"
    >
      <Dialog.Title class="mb-3 text-lg font-semibold">
        Are you sure you want to delete {selectedModel.title}?
      </Dialog.Title>
      <div class="flex justify-end gap-2">
        <Button variant="ghost" onclick={() => (dialogDeleteModel = false)}>Cancel</Button>
        <Button variant="destructive" onclick={confirmDeleteModel}>Delete</Button>
      </div>
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>
