// frontend/app/src/components/views/JobsView.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div>
    <q-table flat :rows="rows" :columns="columns" row-key="id" :loading="loading" clickable
      :rows-per-page-options="[0]">
      <template v-slot:loading>
        <q-inner-loading showing color="primary"></q-inner-loading>
      </template>
      <template v-slot:body="props">
        <q-tr :props="props">
          <q-td key="name" :props="props" @click="onRowClick(props.row)">
            {{ props.row.name + " (" + props.row.sub_name + ")" }}
          </q-td>
          <q-td key="cluster" :props="props">
            <q-badge color="purple">
              {{ props.row.cluster }}
            </q-badge>
          </q-td>
          <q-td key="submitted" :props="props">
            <q-badge :color="props.row.submitted ? 'green' : 'red'">
              {{ props.row.submitted }}
            </q-badge>
          </q-td>
          <q-td key="results" :props="props">
            <q-badge :color="props.row.results ? 'green' : 'red'">
              {{ props.row.results }}
            </q-badge>
          </q-td>
          <q-td key="id" :props="props">
            <q-btn flat icon="fas fa-times" @click="cancelJob(props.row)" :disable="!props.row.submitted">
              <q-tooltip>
                Cancel Job
              </q-tooltip>
            </q-btn>
          </q-td>
        </q-tr>
      </template>
    </q-table>

    <!-- <q-btn flat icon="fas fa-times" @click="cancelJob" :disable="selected.length==0">
            <q-tooltip>
                Cancel Job
            </q-tooltip>
        </q-btn> -->
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import { useModelStore } from 'src/stores/model-store';
import { useViewStore } from 'src/stores/view-store';
import { cancelJob, getJobs } from 'src/client';
import type { Jobs, ModelData_Output } from 'src/client';

export default defineComponent({
  name: 'JobsView',
  setup() {
    const modelStore = useModelStore();
    const modelData = computed(() => modelStore.modelData)
    const viewStore = useViewStore();
    return {
      modelStore,
      modelData,
      viewStore
    }
  },
  created() {
    this.$bus.on('getJobs', () => {
      this._getJobs()
    })
  },
  data() {
    return {
      loading: false,
      selected: [],
      columns: [
        { name: 'name', label: 'ModelName', field: 'name', sortable: true, align: 'left' as 'left' | 'right' | 'center' },
        { name: 'cluster', label: 'Cluster', field: 'cluster', sortable: true },
        { name: 'submitted', label: 'Submitted', field: 'submitted', sortable: true },
        { name: 'results', label: 'Results', field: 'results', sortable: true },
        // { name: 'created', hidden: true},
        { name: 'id', label: 'id', field: 'id', required: true, hidden: true },
      ],
      rows: [] as Jobs[]
    };
  },
  mounted() {
    this._getJobs()
  },
  methods: {
    async cancelJob(row: Jobs) {
      this.loading = true;

      await cancelJob({
        modelName: row.name,
        modelFolderName: row.sub_name,
        cluster: row.cluster,
        sbatch: true,
      })
        .then(() => {
          this.$q.notify({
            message: 'Job canceled'
          })
        })
        .catch(() => {
          this.$q.notify({
            color: 'negative',
            position: 'bottom-right',
            message: 'Failed',
            icon: 'report_problem'
          })
        })
      this.$bus.emit('getStatus')
      this._getJobs();
    },
    onRowClick(row: Jobs) {
      this.modelStore.modelData = row.model as ModelData_Output;
      console.log(row.model);
    },
    _getJobs() {
      this.loading = true;

      getJobs({ modelName: this.modelStore.selectedModel.file, sbatch: this.modelData.job.sbatch })
        .then((response) => {
          this.rows = response
          this.$q.notify({
            message: "Jobs found"
          })
        })
        .catch((error) => {
          this.$q.notify({
            type: 'negative',
            message: error.response.detail
          })
          this.loading = false;
        })
      this.loading = false;
    },
  },
})
</script>

<style></style>

// src/lib/components/views/JobsView.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { X } from 'lucide-svelte';
  import { onMount } from 'svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { cancelJob as cancelJobApi, getJobs } from '$lib/client';
  import type { Jobs, ModelData } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';

  let loading = $state(false);
  let rows = $state<Jobs[]>([]);

  async function fetchJobs() {
    loading = true;
    try {
      rows = await getJobs({
        modelName: modelStore.selectedModel.file,
        sbatch: modelStore.modelData.job.sbatch
      });
      // notify.info('Jobs found');
    } catch (error) {
      notify.apiError(error);
    } finally {
      loading = false;
    }
  }

  async function cancelJob(row: Jobs) {
    loading = true;
    try {
      await cancelJobApi({
        modelName: row.name,
        modelFolderName: row.sub_name,
        cluster: row.cluster,
        sbatch: true
      });
      notify.positive('Job canceled');
    } catch {
      notify.negative('Failed');
    }
    bus.emit('resetData');
    fetchJobs();
  }

  function onRowClick(row: Jobs) {
    modelStore.modelData = row.model as ModelData;
  }

  onMount(() => {
    fetchJobs();
    bus.on('resetData', fetchJobs);
    return () => bus.off('resetData', fetchJobs);
  });
</script>

<div class="overflow-x-auto">
  <table class="w-full text-left text-sm">
    <thead class="border-b border-border text-muted-foreground">
      <tr>
        <th class="px-3 py-2 font-medium">Model Name</th>
        <th class="px-3 py-2 font-medium">Cluster</th>
        <th class="px-3 py-2 font-medium">Submitted</th>
        <th class="px-3 py-2 font-medium">Results</th>
        <th class="px-3 py-2 font-medium"></th>
      </tr>
    </thead>
    <tbody>
      {#if loading}
        <tr><td colspan="5" class="px-3 py-6 text-center text-muted-foreground">Loading…</td></tr>
      {:else if rows.length === 0}
        <tr><td colspan="5" class="px-3 py-6 text-center text-muted-foreground">No jobs found</td></tr>
      {:else}
        {#each rows as row (row.id)}
          <tr class="border-b border-border hover:bg-muted/50">
            <td class="cursor-pointer px-3 py-2" onclick={() => onRowClick(row)}>
              {row.name} ({row.sub_name})
            </td>
            <td class="px-3 py-2">
              <span class="rounded-full bg-accent/20 px-2 py-0.5 text-xs font-medium text-accent-foreground">
                {row.cluster}
              </span>
            </td>
            <td class="px-3 py-2">
              <span
                class="rounded-full px-2 py-0.5 text-xs font-medium {row.submitted
                  ? 'bg-success/20 text-success'
                  : 'bg-destructive/20 text-destructive'}"
              >
                {row.submitted}
              </span>
            </td>
            <td class="px-3 py-2">
              <span
                class="rounded-full px-2 py-0.5 text-xs font-medium {row.results
                  ? 'bg-success/20 text-success'
                  : 'bg-destructive/20 text-destructive'}"
              >
                {row.results}
              </span>
            </td>
            <td class="px-3 py-2 text-right">
              <Button
                variant="ghost"
                size="icon"
                disabled={!row.submitted}
                onclick={() => cancelJob(row)}
                title="Cancel job"
              >
                <X class="h-4 w-4" />
              </Button>
            </td>
          </tr>
        {/each}
      {/if}
    </tbody>
  </table>
</div>
