// frontend/app/src/components/views/RenewableView.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <area-chart :data=plot_data label="Percent of renewable energy share"></area-chart>
</template>

<script lang="ts">
import { useViewStore } from 'src/stores/view-store';
import { getPrognosisEnergy } from 'src/client';
export default {
  name: 'RenewableView',
  setup() {
    const viewStore = useViewStore();

    return {
      viewStore
    }
  },
  data() {
    return {
      plot_data: {}
    };
  },
  methods: {},
  async mounted() {

    await getPrognosisEnergy()
      .then((response) => {
        this.plot_data = response;
      })
      .catch((error) => {
        this.$q.notify({
          color: 'negative',
          position: 'bottom-right',
          message: error,
          icon: 'report_problem'
        })
      })

  }
}
</script>

<style></style>

// src/lib/components/views/RenewableView.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import Chart from 'chart.js/auto';
  import { getPrognosisEnergy } from '$lib/client';
  import { notify } from '$lib/utils/notify';

  let canvas: HTMLCanvasElement;

  onMount(async () => {
    try {
      const response = await getPrognosisEnergy();
      // response is expected as { [timestamp: string]: number } (percent renewable share)
      const entries = Object.entries(response as Record<string, number>);
      new Chart(canvas, {
        type: 'line',
        data: {
          labels: entries.map(([label]) => label),
          datasets: [
            {
              label: 'Percent of renewable energy share',
              data: entries.map(([, value]) => value),
              fill: true,
              tension: 0.3
            }
          ]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          scales: { y: { beginAtZero: true } }
        }
      });
    } catch (error) {
      notify.apiError(error);
    }
  });
</script>

<div class="h-full w-full p-2">
  <canvas bind:this={canvas}></canvas>
</div>
