// src/routes/perihub/+page.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { Tabs } from 'bits-ui';
  import { Sliders, LineChart, FileText } from 'lucide-svelte';
  import ExpansionComp from '$lib/components/ExpansionComp.svelte';
  import ViewComp from '$lib/components/ViewComp.svelte';
  import TextComp from '$lib/components/TextComp.svelte';
  import ModelActions from '$lib/components/actions/ModelActions.svelte';
  import ViewActions from '$lib/components/actions/ViewActions.svelte';
  import TextActions from '$lib/components/actions/TextActions.svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { bus } from '$lib/utils/bus';

  let mobileTab = $state('setup');

  async function showTutorial() {
    // @ts-expect-error driver.js v0.9 ships no type declarations
    const { default: Driver } = await import('driver.js');
    // @ts-expect-error nor for its CSS
    await import('driver.js/dist/driver.min.css');

    const driver = new Driver({
      animate: true,
      opacity: 0.5,
      stageBackground: defaultStore.darkMode ? 'gray' : 'white'
    });

    driver.defineSteps([
      {
        element: '#ModelActions',
        popover: {
          title: 'ModelActions',
          description: 'Here you are able to upload, save, switch and generate models',
          position: 'right'
        }
      },
      {
        element: '#ExpansionComp',
        popover: {
          title: 'ExpansionComp',
          description: 'Here you can find the configuration for your simulation',
          position: 'right'
        }
      },
      {
        element: '#ViewActions',
        popover: {
          title: 'ViewActions',
          description: 'Here you are able to submit your simulation, view your results and download them',
          position: 'left'
        }
      },
      {
        element: '#ViewComp',
        popover: {
          title: 'ViewComp',
          description: 'This is where your simulation results are displayed',
          position: 'left'
        }
      },
      {
        element: '#TextActions',
        popover: {
          title: 'TextActions',
          description: 'If you want to edit your input-deck you can save it here',
          position: 'left'
        }
      },
      {
        element: '#TextComp',
        popover: {
          title: 'TextComp',
          description: 'This is where your input-deck or log-file is displayed',
          position: 'left'
        }
      }
    ]);

    driver.start();
  }

  onMount(() => {
    bus.on('showTutorial' as never, showTutorial);

    // Auto-launch the tour once for first-time visitors instead of relying
    // solely on them discovering the help icon in the header.
    if (!localStorage.getItem('periHubTourSeen')) {
      localStorage.setItem('periHubTourSeen', 'true');
      setTimeout(showTutorial, 600);
    }

    return () => bus.off('showTutorial' as never, showTutorial);
  });
</script>

<svelte:head>
  <title>PeriHub — Model Builder</title>
</svelte:head>

<!-- Desktop / tablet layout: side-by-side panels. -->
<div class="hidden h-[calc(100vh-4rem)] grid-cols-1 gap-3 overflow-hidden p-3 lg:grid lg:grid-cols-2">
  <div id="model-configuration" class="flex min-h-0 flex-col overflow-hidden rounded-lg border border-border">
    <div id="ModelActions"><ModelActions /></div>
    <div id="ExpansionComp" class="min-h-0 flex-1 overflow-hidden">
      <ExpansionComp />
    </div>
  </div>

  <div id="model-output" class="flex min-h-0 flex-col gap-3 overflow-hidden">
    <div class="flex min-h-0 flex-1 flex-col overflow-hidden">
      <div id="ViewActions"><ViewActions /></div>
      <div id="ViewComp" class="min-h-0 flex-1 overflow-hidden"><ViewComp /></div>
    </div>
    <div class="flex min-h-0 flex-1 flex-col overflow-hidden">
      <div id="TextActions"><TextActions /></div>
      <div id="TextComp" class="min-h-0 flex-1 overflow-hidden"><TextComp /></div>
    </div>
  </div>
</div>

<!-- Narrow-screen layout: splitters/side-by-side panels don't work well with
     touch on small viewports, so stack the three work areas as swipeable
     tabs instead. Pure CSS breakpoint (no JS screen-size detection) so it
     also behaves correctly during SSR/hydration. -->
<div class="flex h-[calc(100vh-4rem)] flex-col overflow-hidden lg:hidden">
  <Tabs.Root bind:value={mobileTab} class="flex h-full flex-col">
    <Tabs.List class="flex border-b border-border bg-muted/40">
      <Tabs.Trigger
        value="setup"
        class="flex flex-1 items-center justify-center gap-1.5 px-2 py-2.5 text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground"
      >
        <Sliders class="h-4 w-4" /> Setup
      </Tabs.Trigger>
      <Tabs.Trigger
        value="results"
        class="flex flex-1 items-center justify-center gap-1.5 px-2 py-2.5 text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground"
      >
        <LineChart class="h-4 w-4" /> Results
      </Tabs.Trigger>
      <Tabs.Trigger
        value="input"
        class="flex flex-1 items-center justify-center gap-1.5 px-2 py-2.5 text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground"
      >
        <FileText class="h-4 w-4" /> Input / Log
      </Tabs.Trigger>
    </Tabs.List>

    <div class="min-h-0 flex-1 overflow-hidden">
      <Tabs.Content value="setup" class="flex h-full flex-col overflow-hidden p-2">
        <ModelActions />
        <div class="min-h-0 flex-1 overflow-hidden">
          <ExpansionComp scrollable={false} />
        </div>
      </Tabs.Content>
      <Tabs.Content value="results" class="flex h-full flex-col overflow-hidden p-2">
        <ViewActions />
        <ViewComp />
      </Tabs.Content>
      <Tabs.Content value="input" class="flex h-full flex-col overflow-hidden p-2">
        <TextActions />
        <TextComp />
      </Tabs.Content>
    </div>
  </Tabs.Root>
</div>

// frontend/app/src/pages/PeriHub.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <q-page class="flex-center">
    <q-splitter v-model="verticalSplitterModel" class="body" :limits="[30, 60]">
      <template v-slot:before>
        <div class="q-pa-md">
          <ModelActions id="ModelActions" />
          <ExpansionComp id="ExpansionComp" />
        </div>
      </template>

      <template v-slot:after>
        <q-splitter v-model="horizontalSplitterModel" horizontal :limits="[1, 99]">
          <template v-slot:before>
            <q-resize-observer @resize="onResizeBefore" :debounce="0" />
            <div class="q-pa-md">
              <ViewActions id="ViewActions" />
              <ViewComp id="ViewComp" />
            </div>
          </template>
          <template v-slot:after>
            <q-resize-observer @resize="onResizeAfter" :debounce="0" />
            <div class="q-pa-md">
              <TextActions id="TextActions" />
              <TextComp id="TextComp" />
            </div>
          </template>
        </q-splitter>
      </template>
    </q-splitter>
  </q-page>
</template>

<script lang="ts">
import ModelActions from 'src/components/actions/ModelActions.vue'
import ExpansionComp from 'src/components/ExpansionComp.vue'
import ViewActions from 'src/components/actions/ViewActions.vue'
import ViewComp from 'src/components/ViewComp.vue'
import TextActions from 'src/components/actions/TextActions.vue'
import TextComp from 'src/components/TextComp.vue'
import { useDefaultStore } from 'src/stores/default-store';
import Driver from 'driver.js';
import 'driver.js/dist/driver.min.css';

export default {
  name: 'PeriHub',
  components: {
    ModelActions,
    ExpansionComp,
    ViewActions,
    ViewComp,
    TextActions,
    TextComp
  },
  setup() {
    const store = useDefaultStore();

    return {
      store
    }
  },
  created() {
    this.$bus.on('showTutorial', () => {
      this.showTutorial()
    })
  },
  data() {
    return {
      verticalSplitterModel: 40,
      horizontalSplitterModel: 50,
    };
  },
  methods: {
    onResizeBefore(size) {
      // console.log('get resize', width, height)
      this.$bus.emit('resizeViewPanel', size.height)
    },
    onResizeAfter(size) {
      // console.log('get resize', width, height)
      this.$bus.emit('resizeTextPanel', size.height)
    },
    showTutorial() {
      let color = 'white';
      if (this.store.darkMode) {
        color = 'gray';
      }

      const driver = new Driver({
        animate: true, // Animate while changing highlighted element
        opacity: 0.5,
        stageBackground: color,
      });

      // Define the steps for introduction
      driver.defineSteps([
        {
          element: '#ModelActions',
          popover: {
            className: 'first-step-popover-class',
            title: 'ModelActions',
            description: 'Here you are able to upload, save, switch and generate models',
            position: 'right',
          },
        },
        {
          element: '#ExpansionComp',
          popover: {
            title: 'ExpansionComp',
            description: 'Here you can find the configuration for your simulation',
            position: 'right',
          },
        },
        {
          element: '#ViewActions',
          popover: {
            title: 'ViewActions',
            description: 'Here you are able to submit your simulation, view your results and download them',
            position: 'left',
          },
        },
        {
          element: '#ViewComp',
          popover: {
            title: 'ViewComp',
            description: 'This is where your simulation results are displayed',
            position: 'left',
          },
        },
        {
          element: '#TextActions',
          popover: {
            title: 'TextActions',
            description: 'If you want to edit your input-deck you can save it here',
            position: 'left',
          },
        },
        {
          element: '#TextComp',
          popover: {
            title: 'TextComp',
            description: 'This is where your input-deck or log-file is displayed',
            position: 'left',
          },
        },
      ]);

      // Start the introduction
      driver.start();
    },
  },
};
</script>

<style>
.body {
  height: calc(100vh - 117px);
  flex: auto;
}
</style>
