// frontend/app/src/components/expansions/Additive.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div>
    <q-toggle class="my-toggle" v-model="additive.enabled" label="Enabled" standout dense></q-toggle>
    <div v-if="additive.enabled">
      <q-separator></q-separator>
      <q-list v-for="additiveModel, index in additive.additiveModels" :key="additiveModel.additiveModelId"
        style="padding: 0px">
        <div class="row my-row">
          <q-input class="my-input" v-model="additiveModel.name" :rules="[rules.required, rules.name]" label="Name"
            standout dense></q-input>
          <q-select class="my-input" :options="additiveTypes" v-model="additiveModel.additiveType" label="Type" standout
            dense></q-select>
          <q-input class="my-input" v-model="additiveModel.printTemp" :rules="[rules.required, rules.float]"
            label="Print Temperature" standout dense></q-input>
          <!-- <q-input class="my-input" v-model="additiveModel.timeFactor" :rules="[rules.required, rules.float]"
            label="Time Factor" standout dense></q-input> -->
          <q-btn flat icon="fas fa-trash-alt" @click="removeAdditiveModel(index)">
            <q-tooltip>
              Remove Additive Model
            </q-tooltip>
          </q-btn>
        </div>
        <q-separator></q-separator>
      </q-list>

      <q-btn flat icon="fas fa-plus" @click="addAdditiveModel">
        <q-tooltip>
          Add additive Model
        </q-tooltip>
      </q-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import { useModelStore } from 'src/stores/model-store';
import rules from 'assets/rules.js';

export default defineComponent({
  name: 'AdditiveSettings',
  setup() {
    const store = useModelStore();
    const additive = computed(() => store.modelData.additive)
    return {
      store,
      additive,
      rules
    }
  },
  created() {
  },
  data() {
    return {
      additiveTypes: ['Simple'],
    };
  },
  methods: {
    addAdditiveModel() {
      if (!this.additive.additiveModels) {
        this.additive.additiveModels = []
      }
      const len = this.additive.additiveModels.length;
      let newItem = {}
      if (len != 0) {
        newItem = structuredClone(this.additive.additiveModels[len - 1])
      }
      newItem.additiveModelsId = len + 1
      newItem.name = 'Additive Model ' + (len + 1)
      this.additive.additiveModels.push(newItem);
    },
    removeAdditiveModel(index: number) {
      this.additive.additiveModels.splice(index, 1);
      this.additive.additiveModels.forEach((model, i) => {
        model.additiveModelsId = i + 1
      })
    },
  }
})
</script>

// src/lib/components/expansions/Additive.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Plus, Trash2 } from 'lucide-svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  const additive = $derived(modelStore.modelData.additive);
  const additiveTypes = ['Simple'];

  function addAdditiveModel() {
    if (!additive.additiveModels) additive.additiveModels = [];
    const list = additive.additiveModels;
    const len = list.length;
    const newItem = len > 0 ? structuredClone($state.snapshot(list[len - 1])) : ({} as (typeof list)[number]);
    newItem.additiveModelId = len + 1;
    newItem.name = `Additive Model ${len + 1}`;
    list.push(newItem);
  }

  function removeAdditiveModel(index: number) {
    additive.additiveModels.splice(index, 1);
    additive.additiveModels.forEach((model, i) => (model.additiveModelId = i + 1));
  }
</script>

<div class="space-y-3 p-3">
  <Toggle bind:checked={additive.enabled} label="Enabled" />

  {#if additive.enabled}
    <div class="space-y-3 border-t border-border pt-3">
      {#each additive.additiveModels ?? [] as model, index (model.additiveModelId ?? index)}
        <div class="flex flex-wrap items-end gap-3 border-b border-border pb-3">
          <div class="space-y-1">
            <Label for={`add-name-${index}`}>Name</Label>
            <Input id={`add-name-${index}`} bind:value={model.name} />
          </div>
          <div class="space-y-1">
            <Label for={`add-type-${index}`}>Type</Label>
            <Select id={`add-type-${index}`} bind:value={model.additiveType}>
              {#each additiveTypes as type (type)}
                <option value={type}>{type}</option>
              {/each}
            </Select>
          </div>
          <div class="space-y-1">
            <Label for={`add-temp-${index}`}>Print Temperature</Label>
            <Input id={`add-temp-${index}`} type="number" bind:value={model.printTemp} />
          </div>
          <Button variant="ghost" size="icon" onclick={() => removeAdditiveModel(index)} title="Remove additive model">
            <Trash2 class="h-4 w-4" />
          </Button>
        </div>
      {/each}

      <Button variant="outline" size="sm" onclick={addAdditiveModel}>
        <Plus class="h-4 w-4" /> Add additive model
      </Button>
    </div>
  {/if}
</div>
