// quasar-gui/app/src/components/expansions/BondFilters.vue
<template>
    <div>
            <q-list
                v-for="bondFilter, index in bondFilters"
                :key="bondFilter.bondFiltersId"
                style="padding: 0px"
            >
                <div class="row my-row">
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.name"
                        :rules="[rules.required, rules.name]"
                        :label="bondFilterKeys.name"
                        standout
                        dense
                    ></q-input>
                    <q-select 
                        class="my-select"
                        :options="bondFiltertype"
                        v-model="bondFilter.type"
                        :label="bondFilterKeys.type"
                        standout
                        dense
                    ></q-select>
                    <q-input
                        v-if="bondFilter.type=='Rectangular_Plane'"
                        class="my-input"
                        v-model="bondFilter.bottomLength"
                        :rules="[rules.required, rules.name]"
                        :label="bondFilterKeys.bottomLength"
                        standout
                        dense
                    ></q-input>
                    <q-input
                        v-if="bondFilter.type=='Rectangular_Plane'"
                        class="my-input"
                        v-model="bondFilter.sideLength"
                        :rules="[rules.required, rules.name]"
                        :label="bondFilterKeys.sideLength"
                        standout
                        dense
                    ></q-input>
                    <q-input
                        v-if="bondFilter.type=='Disk'"
                        class="my-input"
                        v-model="bondFilter.radius"
                        :rules="[rules.required, rules.name]"
                        :label="bondFilterKeys.radius"
                        standout
                        dense
                    ></q-input>
                    <q-btn flat icon="fas fa-trash-alt" @click="removeBondFilter(index)">
                        <q-tooltip>
                            Remove Bond Filter
                        </q-tooltip>
                    </q-btn>
                </div>
                <div class="row my-row">
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.normalX"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.normalX"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.normalY"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.normalY"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.normalZ"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.normalZ"
                        standout
                        dense
                    ></q-input>
                    <q-toggle
                        class="my-toggle"
                        v-model="bondFilter.show"
                        @update:model-value="showHideBondFilters"
                        label="Show"
                        standout
                        dense
                    ></q-toggle>
                </div>
                <div class="row my-row" v-show="bondFilter.type=='Rectangular_Plane'">
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.lowerLeftCornerX"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.lowerLeftCornerX"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.lowerLeftCornerY"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.lowerLeftCornerY"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.lowerLeftCornerZ"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.lowerLeftCornerZ"
                        standout
                        dense
                    ></q-input>
                </div>
                <div class="row my-row" v-show="bondFilter.type=='Rectangular_Plane'">
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.bottomUnitVectorX"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.bottomUnitVectorX"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.bottomUnitVectorY"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.bottomUnitVectorY"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.bottomUnitVectorZ"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.bottomUnitVectorZ"
                        standout
                        dense
                    ></q-input>
                </div>
                <div class="row my-row" v-show="bondFilter.type=='Disk'">
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.centerX"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.centerX"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.centerY"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.centerY"
                        standout
                        dense
                    ></q-input>
                    <q-input 
                        class="my-input"
                        v-model="bondFilter.centerZ"
                        :rules="[rules.required, rules.float]"
                        :label="bondFilterKeys.centerZ"
                        standout
                        dense
                    ></q-input>
                </div>
                <q-separator></q-separator>
            </q-list>
            
            <q-btn flat icon="fas fa-plus" @click="addBondFilter">
                <q-tooltip>
                    Add Bond Filter
                </q-tooltip>
            </q-btn>
        </div>
</template>
  
<script>
    import { computed, defineComponent } from 'vue'
    import { useModelStore } from 'stores/model-store';
    import { useViewStore } from 'stores/view-store';
    import { inject } from 'vue'
    import rules from "assets/rules.js";
    import { deepCopy } from '../../utils/functions.js'
  
    export default defineComponent({
        name: 'BondFilterSettings',
        setup() {
            const store = useModelStore();
            const viewStore = useViewStore();
            const bondFilters = computed(() => store.modelData.bondFilters)
            const bondFilterPoints = computed(() => viewStore.bondFilterPoints)
            const bus = inject('bus')
            return {
                store,
                bondFilters,
                bondFilterPoints,
                rules,
                bus
            }
        },
        created() {
            this.bus.on('showHideBondFilters', () => {
                console.log("showHideBondFilters")
                this.showHideBondFilters()
            })
        },
        data() {
            return {
                bondFiltertype: ["Rectangular_Plane", "Disk"],
                bondFilterKeys: {
                    name: "name",
                    type: "Type",
                    normalX: "Normal_X",
                    normalY: "Normal_Y",
                    normalZ: "Normal_Z",
                    lowerLeftCornerX: "Lower_Left_Corner_X",
                    lowerLeftCornerY: "Lower_Left_Corner_Y",
                    lowerLeftCornerZ: "Lower_Left_Corner_Z",
                    bottomUnitVectorX: "Bottom_Unit_Vector_X",
                    bottomUnitVectorY: "Bottom_Unit_Vector_Y",
                    bottomUnitVectorZ: "Bottom_Unit_Vector_Z",
                    bottomLength: "Bottom_Length",
                    sideLength: "Side_Length",
                    centerX: "Center_X",
                    centerY: "Center_Y",
                    centerZ: "Center_Z",
                    radius: "Radius",
                },
            };
        },
        methods: {
            addBondFilter() {
                const len = this.bondFilters.length;
                let newItem = deepCopy(this.bondFilters[len - 1])
                newItem.bondFilterId = len + 1
                newItem.name = "bf_" + (len + 1)
                this.bondFilters.push(newItem);
                this.bondFilterPoints.push({
                    bondFilterPointsId: len + 1,
                    bondFilterPointString: [],
                });
            },
            removeBondFilter(index) {
                this.bondFilters.splice(index, 1);
                this.bondFilterPoints.splice(index, 1);
            },
            
            cross(a1, a2, a3, b1, b2, b3) {
                return [a2 * b3 - a3 * b2, a3 * b1 - a1 * b3, a1 * b2 - a2 * b1];
            },
            vectorLength(a1, a2, a3) {
                return Math.sqrt(a1 * a1 + a2 * a2 + a3 * a3);
            },
            getVectorNorm(a1, a2, a3) {
                const bottomLength = Math.abs(this.vectorLength(a1, a2, a3));
                const normx = a1 / bottomLength;
                const normy = a2 / bottomLength;
                const normz = a3 / bottomLength;
                return [normx, normy, normz];
            },
            showHideBondFilters() {
                // this.bondFilterPolyString = []
                // let bondFilterPolyString = []
                this.bondFilterPoints = [];

                for (var i = 0; i < this.bondFilters.length; i++) {
                    let bondFilterPointString = [];
                    const bondFilter = this.bondFilters[i];
                    if (bondFilter.show) {
                    const nx = parseFloat(bondFilter.normalX);
                    const ny = parseFloat(bondFilter.normalY);
                    const nz = parseFloat(bondFilter.normalZ);

                    if (bondFilter.type == "Disk") {
                        const cx = parseFloat(bondFilter.centerX);
                        const cy = parseFloat(bondFilter.centerY);
                        const cz = parseFloat(bondFilter.centerZ);
                        const radius = parseFloat(bondFilter.radius);

                        let crossVector1 = this.cross(nx, ny, nz, 1.0, 0.0, 0.0);
                        let crossVector2 = this.cross(nx, ny, nz, 0.0, 1.0, 0.0);
                        let crossVector3 = this.cross(nx, ny, nz, -1.0, 0.0, 0.0);
                        let crossVector4 = this.cross(nx, ny, nz, 0.0, -1.0, 0.0);

                        let normVector1 = this.getVectorNorm(
                        crossVector1[0],
                        crossVector1[1],
                        crossVector1[2]
                        );
                        let normVector2 = this.getVectorNorm(
                        crossVector2[0],
                        crossVector2[1],
                        crossVector2[2]
                        );
                        let normVector3 = this.getVectorNorm(
                        crossVector3[0],
                        crossVector3[1],
                        crossVector3[2]
                        );
                        let normVector4 = this.getVectorNorm(
                        crossVector4[0],
                        crossVector4[1],
                        crossVector4[2]
                        );

                        const point1x = cx + normVector1[0] * radius;
                        const point1y = cy + normVector1[1] * radius;
                        const point1z = cz + normVector1[2] * radius;
                        const point2x = cx + normVector2[0] * radius;
                        const point2y = cy + normVector2[1] * radius;
                        const point2z = cz + normVector2[2] * radius;
                        const point3x = cx + normVector3[0] * radius;
                        const point3y = cy + normVector3[1] * radius;
                        const point3z = cz + normVector3[2] * radius;
                        const point4x = cx + normVector4[0] * radius;
                        const point4y = cy + normVector4[1] * radius;
                        const point4z = cz + normVector4[2] * radius;

                        bondFilterPointString.push(point1x, point1y, point1z);
                        bondFilterPointString.push(point2x, point2y, point2z);
                        bondFilterPointString.push(point3x, point3y, point3z);
                        bondFilterPointString.push(point4x, point4y, point4z);
                    } else {
                        const lx = parseFloat(bondFilter.lowerLeftCornerX);
                        const ly = parseFloat(bondFilter.lowerLeftCornerY);
                        const lz = -parseFloat(bondFilter.lowerLeftCornerZ);
                        const bx = parseFloat(bondFilter.bottomUnitVectorX);
                        const by = parseFloat(bondFilter.bottomUnitVectorY);
                        const bz = parseFloat(bondFilter.bottomUnitVectorZ);
                        const bl = parseFloat(bondFilter.bottomLength);
                        const sl = parseFloat(bondFilter.sideLength);

                        const point1x = lx;
                        const point1y = ly;
                        const point1z = lz;

                        let [normx, normy, normz] = this.getVectorNorm(bx, by, bz);

                        const point2x = lx + normx * bl;
                        const point2y = ly + normy * bl;
                        const point2z = lz + normz * bl;

                        let crossVector = this.cross(nx, ny, nz, bx, by, bz);

                        let normVector = this.getVectorNorm(
                        crossVector[0],
                        crossVector[1],
                        crossVector[2]
                        );

                        const point4x = lx + normVector[0] * sl;
                        const point4y = ly + normVector[1] * sl;
                        const point4z = lz + normVector[2] * sl;

                        const point3x = point2x + normVector[0] * sl;
                        const point3y = point2y + normVector[1] * sl;
                        const point3z = point2z + normVector[2] * sl;

                        bondFilterPointString.push(point1x, point1y, point1z);
                        bondFilterPointString.push(point2x, point2y, point2z);
                        bondFilterPointString.push(point3x, point3y, point3z);
                        bondFilterPointString.push(point4x, point4y, point4z);

                        // bondFilterPolyString.push(4, 0, 1, 3, 2)
                    }
                    }
                    if (this.bondFilterPoints.length < i + 1) {
                    this.bondFilterPoints.push({
                        bondFilterPointsId: i + 1,
                        bondFilterPointString: [],
                    });
                    }
                    this.bondFilterPoints[i].bondFilterPointString = bondFilterPointString;

                    // this.bondFilterPoints[i].bondFilterPolyString = bondFilterPolyString
                }
            },
        }
    })
</script>

// src/lib/components/expansions/BondFilters.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Plus, Trash2 } from 'lucide-svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import type { BondFilters } from '$lib/client';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  const bondFilters = $derived(modelStore.modelData.bondFilters ?? []);
  const bondFilterTypes = ['Rectangular_Plane', 'Disk'];

  function addBondFilter() {
    const len = bondFilters.length;
    const newItem =
      len > 0 ? (structuredClone($state.snapshot(bondFilters[len - 1])) as BondFilters) : ({} as BondFilters);
    newItem.bondFiltersId = len + 1;
    newItem.name = `bf_${len + 1}`;
    bondFilters.push(newItem);
  }

  function removeBondFilter(index: number) {
    bondFilters.splice(index, 1);
  }
</script>

<div class="space-y-3 p-3">
  {#each bondFilters as bondFilter, index (bondFilter.bondFiltersId ?? index)}
    <div class="space-y-2 border-b border-border pb-3">
      <div class="flex flex-wrap items-end gap-3">
        <div class="space-y-1">
          <Label for={`bf-name-${index}`}>name</Label>
          <Input id={`bf-name-${index}`} bind:value={bondFilter.name} />
        </div>
        <div class="space-y-1">
          <Label for={`bf-type-${index}`}>Type</Label>
          <Select id={`bf-type-${index}`} bind:value={bondFilter.type}>
            {#each bondFilterTypes as type (type)}
              <option value={type}>{type}</option>
            {/each}
          </Select>
        </div>
        {#if bondFilter.type === 'Rectangular_Plane'}
          <div class="space-y-1">
            <Label for={`bf-bottomlen-${index}`}>Bottom_Length</Label>
            <Input id={`bf-bottomlen-${index}`} type="number" bind:value={bondFilter.bottomLength} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-sidelen-${index}`}>Side_Length</Label>
            <Input id={`bf-sidelen-${index}`} type="number" bind:value={bondFilter.sideLength} />
          </div>
        {:else if bondFilter.type === 'Disk'}
          <div class="space-y-1">
            <Label for={`bf-radius-${index}`}>Radius</Label>
            <Input id={`bf-radius-${index}`} type="number" bind:value={bondFilter.radius} />
          </div>
        {/if}
        <Toggle bind:checked={bondFilter.allow_contact} label="Allow Contact" />
        <Button variant="ghost" size="icon" onclick={() => removeBondFilter(index)} title="Remove Bond Filter">
          <Trash2 class="h-4 w-4" />
        </Button>
      </div>

      <div class="flex flex-wrap items-end gap-3">
        <div class="space-y-1">
          <Label for={`bf-nx-${index}`}>Normal_X</Label>
          <Input id={`bf-nx-${index}`} type="number" bind:value={bondFilter.normalX} />
        </div>
        <div class="space-y-1">
          <Label for={`bf-ny-${index}`}>Normal_Y</Label>
          <Input id={`bf-ny-${index}`} type="number" bind:value={bondFilter.normalY} />
        </div>
        <div class="space-y-1">
          <Label for={`bf-nz-${index}`}>Normal_Z</Label>
          <Input id={`bf-nz-${index}`} type="number" bind:value={bondFilter.normalZ} />
        </div>
        <Toggle bind:checked={bondFilter.show} label="Show" />
      </div>

      {#if bondFilter.type === 'Rectangular_Plane'}
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`bf-llx-${index}`}>Lower_Left_Corner_X</Label>
            <Input id={`bf-llx-${index}`} type="number" bind:value={bondFilter.lowerLeftCornerX} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-lly-${index}`}>Lower_Left_Corner_Y</Label>
            <Input id={`bf-lly-${index}`} type="number" bind:value={bondFilter.lowerLeftCornerY} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-llz-${index}`}>Lower_Left_Corner_Z</Label>
            <Input id={`bf-llz-${index}`} type="number" bind:value={bondFilter.lowerLeftCornerZ} />
          </div>
        </div>
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`bf-bux-${index}`}>Bottom_Unit_Vector_X</Label>
            <Input id={`bf-bux-${index}`} type="number" bind:value={bondFilter.bottomUnitVectorX} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-buy-${index}`}>Bottom_Unit_Vector_Y</Label>
            <Input id={`bf-buy-${index}`} type="number" bind:value={bondFilter.bottomUnitVectorY} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-buz-${index}`}>Bottom_Unit_Vector_Z</Label>
            <Input id={`bf-buz-${index}`} type="number" bind:value={bondFilter.bottomUnitVectorZ} />
          </div>
        </div>
      {:else if bondFilter.type === 'Disk'}
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`bf-cx-${index}`}>Center_X</Label>
            <Input id={`bf-cx-${index}`} type="number" bind:value={bondFilter.centerX} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-cy-${index}`}>Center_Y</Label>
            <Input id={`bf-cy-${index}`} type="number" bind:value={bondFilter.centerY} />
          </div>
          <div class="space-y-1">
            <Label for={`bf-cz-${index}`}>Center_Z</Label>
            <Input id={`bf-cz-${index}`} type="number" bind:value={bondFilter.centerZ} />
          </div>
        </div>
      {/if}
    </div>
  {/each}

  <Button variant="outline" size="sm" onclick={addBondFilter}>
    <Plus class="h-4 w-4" /> Add Bond Filter
  </Button>
</div>
