// frontend/app/src/components/expansions/Deviations.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div>
    <q-toggle class="my-toggle" v-model="deviations.enabled" label="Enabled" standout dense :disable="store.TRIAL">
      <q-tooltip v-if="store.TRIAL">
        <div>Disabled in trial version</div>
      </q-tooltip>
    </q-toggle>
    <div v-if="deviations.enabled">
      <q-input class="my-input" v-model="deviations.sampleSize" :rules="[rules.required, rules.int]" label="sampleSize"
        standout dense></q-input>
      <q-separator></q-separator>
      <q-toggle class="my-toggle" v-model="deviations.fileInput" label="Additional txt Input" standout dense />
      <div v-if="deviations.fileInput">
        <q-input class="my-input" v-model="deviations.file" label="File" standout dense></q-input>
        <!-- <div v-if='deviations.type == "json"'>
          <q-input class="my-input" v-model="deviations.mean" :rules="[rules.float]" label="mean" standout
            dense></q-input>
          <q-input class="my-input" v-model="deviations.std" :rules="[rules.float]" label="std" standout
            dense></q-input>
        </div> -->
        <q-list v-for="parameter, index in deviations.oldParameters" :key="parameter.parameterId as PropertyKey"
          style="padding: 0px">
          <div class="row my-row">
            <q-select class="my-input" :options="filterOptions" v-model="parameter.id" label="Id" use-input use-chips
              multiple input-debounce="0" @filter="filterFn" standout dense></q-select>
            <q-input class="my-input" v-model="parameter.factor" :rules="[rules.required, rules.float]" label="Factor"
              standout dense></q-input>
            <q-btn flat icon="fas fa-trash-alt" @click="removeOldParameter(index)">
              <q-tooltip>
                Remove parameter
              </q-tooltip>
            </q-btn>
          </div>
          <q-separator></q-separator>
        </q-list>

        <q-btn flat icon="fas fa-plus" @click="addOldParameter">
          <q-tooltip>
            Add parameter
          </q-tooltip>
        </q-btn>
      </div>
      <q-separator></q-separator>
      <q-list v-for="parameter, index in deviations.parameters" :key="parameter.parameterId as PropertyKey"
        style="padding: 0px">
        <div class="row my-row">
          <q-select class="my-input" :options="filterOptions" v-model="parameter.id" label="Id" use-input use-chips
            multiple input-debounce="0" @filter="filterFn" standout dense></q-select>
          <q-input class="my-input" v-model="parameter.std" :rules="[rules.required, rules.float]" label="Std" standout
            dense></q-input>
          <q-btn flat icon="fas fa-trash-alt" @click="removeParameter(index)">
            <q-tooltip>
              Remove parameter
            </q-tooltip>
          </q-btn>
        </div>
        <q-separator></q-separator>
      </q-list>

      <q-btn flat icon="fas fa-plus" @click="addParameter">
        <q-tooltip>
          Add parameter
        </q-tooltip>
      </q-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, toRaw } from 'vue'
import { useDefaultStore } from 'src/stores/default-store';
import { useModelStore } from 'src/stores/model-store';
import type { Parameter, Deviations } from 'src/client';
//@ts-expect-error Bla
// import objleaves from 'objleaves';
import rules from 'assets/rules.js';

export default defineComponent({
  name: 'DeviationsSettings',
  setup() {
    const store = useDefaultStore();
    const modelStore = useModelStore();
    const modelData = computed(() => modelStore.modelData)
    const deviations = computed(() => modelStore.modelData.deviations) as unknown as Deviations
    return {
      store,
      modelData,
      deviations,
      rules,
    }
  },
  data() {
    return {
      parameters: [
        'materials[0].youngsModulus'
      ],
      distrKeys: {
        gcode: {
          overwriteMesh: 'overwriteMesh',
          sampling: 'Sampling',
          width: 'Width',
          height: 'Height',
          scale: 'Scale'
        }
      },
      filterOptions: [] as string[],
    }
  },
  mounted() {
    this.getAllParameters()
  },
  methods: {
    filterFn(val: string, update: (callbackFn: () => void) => void) {
      update(() => {
        if (val === '') {
          this.filterOptions = this.parameters
        }
        else {
          const needle = val.toLowerCase()
          this.filterOptions = this.parameters.filter(
            v => v.toLowerCase().indexOf(needle) > -1
          )
        }
      })
    },
    isObject(val) {
      return val != null && typeof val === 'object' && Array.isArray(val) === false;
    },
    objleaves(obj, acc = []) {
      const fn = (o, s) => {
        if (Array.isArray(o) || this.isObject(o)) {
          return Object.keys(o).forEach((k) => {
            const path = s ? (Array.isArray(o) ? `${s}[${k}]` : `${s}.${k}`) : k;

            const isLeaf = fn(o[k], path) === false;
            if (isLeaf) {
              acc.push(path);
            }
          });
        }
        return false;
      };

      fn(obj, undefined);
      return acc;
    },
    getAllParameters() {
      this.parameters = this.objleaves(this.modelData)
    },
    addParameter() {
      if (!this.deviations.parameters) {
        this.deviations.parameters = []
      }
      const len = this.deviations.parameters.length;
      const newItem = len > 0 ? structuredClone(toRaw(this.deviations.parameters[len - 1])) as Parameter : {} as Parameter;
      newItem.parameterId = len + 1
      this.deviations.parameters.push(newItem);
    },
    removeParameter(index: number) {
      this.deviations.parameters.splice(index, 1);
      this.deviations.parameters.forEach((model, i) => {
        model.parameterId = i + 1
      })
    },
    addOldParameter() {
      if (!this.deviations.oldParameters) {
        this.deviations.oldParameters = []
      }
      const len = this.deviations.oldParameters.length;
      const newItem = len > 0 ? structuredClone(toRaw(this.deviations.oldParameters[len - 1])) as Parameter : {} as Parameter;
      newItem.parameterId = len + 1
      this.deviations.oldParameters.push(newItem);
    },
    removeOldParameter(index: number) {
      this.deviations.oldParameters.splice(index, 1);
      this.deviations.oldParameters.forEach((model, i) => {
        model.parameterId = i + 1
      })
    },
  },
})
</script>

// src/lib/components/expansions/Deviations.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { Plus, Trash2 } from 'lucide-svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import type { Parameter } from '$lib/client';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  const deviations = $derived(modelStore.modelData.deviations);
  let parameters = $state<string[]>(['materials[0].youngsModulus']);

  function isObject(val: unknown): val is Record<string, unknown> {
    return val != null && typeof val === 'object' && !Array.isArray(val);
  }

  function objleaves(obj: unknown, prefix = '', acc: string[] = []): string[] {
    if (Array.isArray(obj) || isObject(obj)) {
      const entries = Array.isArray(obj) ? obj.entries() : Object.entries(obj);
      for (const [k, v] of entries) {
        const path = prefix
          ? Array.isArray(obj)
            ? `${prefix}[${k}]`
            : `${prefix}.${k}`
          : String(k);
        if (Array.isArray(v) || isObject(v)) {
          objleaves(v, path, acc);
        } else {
          acc.push(path);
        }
      }
    }
    return acc;
  }

  function getAllParameters() {
    parameters = objleaves(modelStore.modelData);
  }

  function addParameter() {
    if (!deviations.parameters) deviations.parameters = [];
    const list = deviations.parameters;
    const len = list.length;
    const newItem =
      len > 0 ? (structuredClone($state.snapshot(list[len - 1])) as Parameter) : ({} as Parameter);
    newItem.parameterId = len + 1;
    list.push(newItem);
  }

  function removeParameter(index: number) {
    deviations.parameters.splice(index, 1);
    deviations.parameters.forEach((p, i) => (p.parameterId = i + 1));
  }

  function addOldParameter() {
    if (!deviations.oldParameters) deviations.oldParameters = [];
    const list = deviations.oldParameters;
    const len = list.length;
    const newItem =
      len > 0 ? (structuredClone($state.snapshot(list[len - 1])) as Parameter) : ({} as Parameter);
    newItem.parameterId = len + 1;
    list.push(newItem);
  }

  function removeOldParameter(index: number) {
    deviations.oldParameters!.splice(index, 1);
    deviations.oldParameters!.forEach((p, i) => (p.parameterId = i + 1));
  }

  onMount(getAllParameters);
</script>

<div class="space-y-3 p-3">
  <Toggle bind:checked={deviations.enabled} label="Enabled" disabled={defaultStore.trial} />

  {#if deviations.enabled}
    <div class="space-y-1">
      <Label for="dev-samplesize">sampleSize</Label>
      <Input id="dev-samplesize" type="number" bind:value={deviations.sampleSize} />
    </div>

    <Toggle bind:checked={deviations.fileInput} label="Additional txt Input" />

    {#if deviations.fileInput}
      <div class="space-y-1">
        <Label for="dev-file">File</Label>
        <Input id="dev-file" bind:value={deviations.file} />
      </div>

      {#each deviations.oldParameters ?? [] as parameter, index (parameter.parameterId ?? index)}
        <div class="border-border flex flex-wrap items-end gap-3 border-b pb-2">
          <div class="w-56 space-y-1">
            <Label for={`dev-old-id-${index}`}>Id</Label>
            <select
              id={`dev-old-id-${index}`}
              multiple
              bind:value={parameter.id}
              class="border-input bg-background h-20 w-full rounded-md border px-2 py-1 text-sm"
            >
              {#each parameters as p (p)}
                <option value={p}>{p}</option>
              {/each}
            </select>
          </div>
          <div class="space-y-1">
            <Label for={`dev-old-factor-${index}`}>Factor</Label>
            <Input id={`dev-old-factor-${index}`} type="number" bind:value={parameter.factor} />
          </div>
          <Button
            variant="ghost"
            size="icon"
            onclick={() => removeOldParameter(index)}
            title="Remove parameter"
          >
            <Trash2 class="h-4 w-4" />
          </Button>
        </div>
      {/each}
      <Button variant="outline" size="sm" onclick={addOldParameter}>
        <Plus class="h-4 w-4" /> Add parameter
      </Button>
    {/if}

    <div class="border-border border-t pt-3"></div>

    {#each deviations.parameters ?? [] as parameter, index (parameter.parameterId ?? index)}
      <div class="border-border flex flex-wrap items-end gap-3 border-b pb-2">
        <div class="w-56 space-y-1">
          <Label for={`dev-id-${index}`}>Id</Label>
          <select
            id={`dev-id-${index}`}
            multiple
            bind:value={parameter.id}
            class="border-input bg-background h-20 w-full rounded-md border px-2 py-1 text-sm"
          >
            {#each parameters as p (p)}
              <option value={p}>{p}</option>
            {/each}
          </select>
        </div>
        <div class="space-y-1">
          <Label for={`dev-std-${index}`}>Std</Label>
          <Input id={`dev-std-${index}`} type="number" bind:value={parameter.std} />
        </div>
        <Button
          variant="ghost"
          size="icon"
          onclick={() => removeParameter(index)}
          title="Remove parameter"
        >
          <Trash2 class="h-4 w-4" />
        </Button>
      </div>
    {/each}
    <Button variant="outline" size="sm" onclick={addParameter}>
      <Plus class="h-4 w-4" /> Add parameter
    </Button>
  {/if}
</div>
