// frontend/app/src/components/expansions/Discretization.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div>
    <q-select class="my-select" :options="distributionTypes" v-model="discretization.distributionType"
      label="Distribution Type" standout dense></q-select>
    <q-list v-for="nodeSet in discretization.nodeSets" :key="nodeSet.nodeSetId" style="padding: 0px">
      <div class="row my-row">
        <q-input class="my-input" v-model="nodeSet.file" :rules="[rules.required, rules.name]" label="Nodeset" standout
          dense></q-input>
        <q-btn flat icon="fas fa-trash-alt" @click="removeNodeSet(index)">
          <q-tooltip>
            Remove Nodeset
          </q-tooltip>
        </q-btn>
      </div>
      <q-separator></q-separator>
    </q-list>
    <q-btn flat icon="fas fa-plus" @click="addNodeSet">
      <q-tooltip>
        Add Nodeset
      </q-tooltip>
    </q-btn>
    <div v-if="store.modelData.discretization.discType == 'gcode' && discretization.gcode != null">
      <q-toggle class="my-toggle" v-model="discretization.gcode.overwriteMesh" :label=discKeys.gcode.overwriteMesh
        standout dense></q-toggle>
      <q-input class="my-input" v-model="discretization.gcode.sampling" :rules="[rules.required, rules.float]"
        :label="discKeys.gcode.sampling" standout dense></q-input>
      <q-input class="my-input" v-model="discretization.gcode.width" :rules="[rules.required, rules.float]"
        :label="discKeys.gcode.width" standout dense></q-input>
      <q-input class="my-input" v-model="discretization.gcode.height" :rules="[rules.required, rules.float]"
        :label="discKeys.gcode.height" standout dense></q-input>
      <q-input class="my-input" v-model="discretization.gcode.scale" :rules="[rules.required, rules.float]"
        :label="discKeys.gcode.scale" standout dense></q-input>
      <q-list v-for="block in discretization.gcode.blockFunctions" :key="block.id" style="padding: 0px">
        <div class="row my-row">
          <q-input class="my-input" v-model="block.id" :rules="[rules.required, rules.float]" label="id" standout
            dense></q-input>
          <q-input class="my-input" v-model="block.function" :rules="[rules.required, rules.equation]" label="Function"
            standout dense></q-input>
          <q-btn flat icon="fas fa-trash-alt" @click="removeBlockFunction(index)">
            <q-tooltip>
              Remove Block Function
            </q-tooltip>
          </q-btn>
        </div>
        <q-separator></q-separator>
      </q-list>
      <q-btn flat icon="fas fa-plus" @click="addBlockFunction">
        <q-tooltip>
          Add Block Function
        </q-tooltip>
      </q-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, toRaw } from 'vue'
import { useModelStore } from 'src/stores/model-store';
import type { Discretization, BlockFunction } from 'src/client';
import rules from 'assets/rules.js';

export default defineComponent({
  name: 'DiscretizazionSettings',
  setup() {
    const store = useModelStore();
    const discretization = computed(() => store.modelData.discretization)
    return {
      store,
      discretization,
      rules,
    }
  },
  data() {
    return {
      distributionTypes: [
        'Neighbor based',
        'Node based'
      ],
      discKeys: {
        gcode: {
          overwriteMesh: 'overwriteMesh',
          sampling: 'Sampling',
          width: 'Width',
          height: 'Height',
          scale: 'Scale'
        }
      }
    }
  },
  methods: {
    addNodeSet() {
      if (!this.discretization.nodeSets) {
        this.discretization.nodeSets = []
      }
      const len = this.discretization.nodeSets.length;
      const newItem = len > 0 ? structuredClone(toRaw(this.discretization.nodeSets[len - 1])) : {} as Discretization;
      newItem.nodeSetId = len + 1
      this.discretization.nodeSets.push(newItem);
    },
    removeNodeSet(index) {
      this.discretization.nodeSets.splice(index, 1);
      this.discretization.nodeSets.forEach((model, i) => {
        model.nodeSetId = i + 1
      })
    },

    addBlockFunction() {
      if (!this.discretization.gcode.blockFunctions) {
        this.discretization.gcode.blockFunctions = []
      }
      const len = this.discretization.gcode.blockFunctions.length;
      const newItem = len > 0 ? structuredClone(toRaw(this.discretization.gcode.blockFunctions[len - 1])) : {} as BlockFunction;
      newItem.id = len + 1
      this.discretization.gcode.blockFunctions.push(newItem);
    },
    removeBlockFunction(index) {
      this.discretization.gcode.blockFunctions.splice(index, 1);
      this.discretization.gcode.blockFunctions.forEach((model, i) => {
        model.id = i + 1
      })
    },
  }
})
</script>

// src/lib/components/expansions/Discretization.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Plus, Trash2 } from 'lucide-svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import type { BlockFunction, Gcode, NodeSet } from '$lib/client';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  const discretization = $derived(modelStore.modelData.discretization);
  const distributionTypes = ['Neighbor based', 'Node based'];

  function addNodeSet() {
    if (!discretization.nodeSets) discretization.nodeSets = [];
    const list = discretization.nodeSets;
    const len = list.length;
    const newItem = len > 0 ? (structuredClone($state.snapshot(list[len - 1])) as NodeSet) : ({} as NodeSet);
    newItem.nodeSetId = len + 1;
    list.push(newItem);
  }

  function removeNodeSet(index: number) {
    if (!discretization.nodeSets) return;
    discretization.nodeSets.splice(index, 1);
    discretization.nodeSets.forEach((n, i) => (n.nodeSetId = i + 1));
  }

  function addBlockFunction() {
    if (!discretization.gcode) discretization.gcode = {} as Gcode;
    if (!discretization.gcode.blockFunctions) discretization.gcode.blockFunctions = [];
    const list = discretization.gcode.blockFunctions;
    const len = list.length;
    const newItem =
      len > 0 ? (structuredClone($state.snapshot(list[len - 1])) as BlockFunction) : ({} as BlockFunction);
    newItem.id = len + 1;
    list.push(newItem);
  }

  function removeBlockFunction(index: number) {
    if (!discretization.gcode?.blockFunctions) return;
    discretization.gcode.blockFunctions.splice(index, 1);
    discretization.gcode.blockFunctions.forEach((b, i) => (b.id = i + 1));
  }
</script>

<div class="space-y-3 p-3">
  <div class="max-w-xs space-y-1">
    <Label for="disc-type">Distribution Type</Label>
    <Select id="disc-type" bind:value={discretization.distributionType}>
      {#each distributionTypes as type (type)}
        <option value={type}>{type}</option>
      {/each}
    </Select>
  </div>

  {#each discretization.nodeSets ?? [] as nodeSet, index (nodeSet.nodeSetId ?? index)}
    <div class="flex items-end gap-2 border-b border-border pb-2">
      <div class="flex-1 space-y-1">
        <Label for={`nodeset-${index}`}>Nodeset</Label>
        <Input id={`nodeset-${index}`} bind:value={nodeSet.file} />
      </div>
      <Button variant="ghost" size="icon" onclick={() => removeNodeSet(index)} title="Remove Nodeset">
        <Trash2 class="h-4 w-4" />
      </Button>
    </div>
  {/each}
  <Button variant="outline" size="sm" onclick={addNodeSet}>
    <Plus class="h-4 w-4" /> Add Nodeset
  </Button>

  {#if discretization.discType === 'gcode' && discretization.gcode != null}
    <div class="space-y-3 border-t border-border pt-3">
      <Toggle bind:checked={discretization.gcode.overwriteMesh} label="Overwrite Mesh" />
      <div class="space-y-1">
        <Label for="gcode-sampling">Sampling</Label>
        <Input id="gcode-sampling" type="number" bind:value={discretization.gcode.sampling} />
      </div>
      <div class="space-y-1">
        <Label for="gcode-width">Width</Label>
        <Input id="gcode-width" type="number" bind:value={discretization.gcode.width} />
      </div>
      <div class="space-y-1">
        <Label for="gcode-height">Height</Label>
        <Input id="gcode-height" type="number" bind:value={discretization.gcode.height} />
      </div>
      <div class="space-y-1">
        <Label for="gcode-scale">Scale</Label>
        <Input id="gcode-scale" type="number" bind:value={discretization.gcode.scale} />
      </div>

      {#each discretization.gcode.blockFunctions ?? [] as block, index (block.id ?? index)}
        <div class="flex flex-wrap items-end gap-2 border-b border-border pb-2">
          <div class="space-y-1">
            <Label for={`bf-id-${index}`}>id</Label>
            <Input id={`bf-id-${index}`} type="number" bind:value={block.id} />
          </div>
          <div class="flex-1 space-y-1">
            <Label for={`bf-fn-${index}`}>Function</Label>
            <Input id={`bf-fn-${index}`} bind:value={block.function} />
          </div>
          <Button variant="ghost" size="icon" onclick={() => removeBlockFunction(index)} title="Remove Block Function">
            <Trash2 class="h-4 w-4" />
          </Button>
        </div>
      {/each}
      <Button variant="outline" size="sm" onclick={addBlockFunction}>
        <Plus class="h-4 w-4" /> Add Block Function
      </Button>
    </div>
  {/if}
</div>
