// frontend/app/src/components/expansions/Model.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div>
    <q-toggle class="my-toggle" standout dense v-model="model.ownModel" label="Own Model"
      @update:model-value="switchOwnModels" :disable="store.TRIAL"></q-toggle>
    <q-select class="my-select" :options="modelStore.availableModels" option-label="title"
      v-model="modelStore.selectedModel" v-show="!model.ownModel" label="Model Name" standout dense
      @update:model-value="selectMethod"></q-select>
    <q-input class="my-input" v-model="modelStore.selectedModel.file" v-show="model.ownModel" :rules="[rules.required]"
      label="Model Name" standout dense></q-input>

    <q-select standout dense class="q-pa-sm" v-model="model.modelFolderName" use-input hide-selected fill-input
      input-debounce="0" @new-value="createValue" :options="filteredModelFolderNameList" @filter="filterFn"
      label="Model Subname" @update:model-value="bus.emit('getStatus')"></q-select>

    <!-- <q-input class="my-select" v-model="model.modelFolderName" label="Model Subname" placeholder="Default" standout
      dense></q-input> -->
    <q-input class="my-input" v-model="model.meshFile" v-show="model.ownModel" :rules="[rules.required]"
      label="Mesh File" standout dense></q-input>

    <q-toggle class="my-toggle" standout dense v-model="model.twoDimensional" label="Two Dimensional"></q-toggle>

    <div v-if="!model.ownModel">
      <div v-for="param in modelStore.modelParams.valves" :key="param.name">
        <div v-if="!param.depends || modelStore.modelParams.valves.find(o => o.name === param.depends).value">
          <q-input class="my-select" v-if="['text', 'number'].includes(param.type)" :label="param.label"
            v-model.number="param.value" :type="param.type" standout dense>
            <q-tooltip>
              {{ param.description }}
            </q-tooltip>
          </q-input>
          <q-select class="my-select" standout dense v-if="param.type == 'select'" :options="param.options"
            option-label="name" v-model="param.value" :label="param.label">
            <q-tooltip>
              {{ param.description }}
            </q-tooltip>
          </q-select>
          <q-toggle class="my-toggle" standout dense v-if="param.type == 'checkbox'" v-model="param.value"
            :label="param.label">
            <q-tooltip>
              {{ param.description }}
            </q-tooltip>
          </q-toggle>
        </div>
      </div>
    </div>

    <!-- <q-input class="my-input" v-model="model.length" v-show="!model.ownModel & modelStore.selectedModel.file != 'RVE'"
      :rules="[rules.required, rules.float]" label="Length" standout dense></q-input>
    <q-input class="my-input" v-model="model.cracklength"
      v-show="['GICmodel', 'GIICmodel', 'CompactTension'].includes(modelStore.selectedModel.file)"
      @update:model-value="bus.emit('updateCracklength')" :rules="[rules.required, rules.float]" label="Cracklength"
      standout dense></q-input>
    <q-toggle class="my-toggle" v-model="model.notchEnabled"
      v-show="['CompactTension'].includes(modelStore.selectedModel.file)" label="Notch enabled" dense></q-toggle>
    <q-input class="my-input" v-model="model.width"
      v-show="!model.ownModel & modelStore.selectedModel.file != 'RVE' & !model.twoDimensional"
      @update:model-value="bus.emit('updateCracklength')" :rules="[rules.required, rules.float]" label="Width" standout
      dense></q-input>
    <q-input class="my-input" v-model="model.height"
      v-show="!model.ownModel & !['RVE', 'CompactTension', 'Smetana'].includes(modelStore.selectedModel.file)"
      :rules="[rules.required, rules.float]" label="Height" standout dense></q-input>
    <q-input class="my-input" v-model="model.height"
      v-show="!model.ownModel & ['Smetana'].includes(modelStore.selectedModel.file)" :rules="[rules.required, rules.float]"
      label="Ply height" standout dense></q-input>
    <q-input v-show="modelStore.selectedModel.file == 'Dogbone' & !model.ownModel" class="my-input" v-model="model.height2"
      :rules="[rules.required, rules.float]" label="Inner Height" standout dense></q-input>
    <q-input v-show="['PlateWithHole', 'RingOnRing'].includes(modelStore.selectedModel.file) & !model.ownModel"
      class="my-input" v-model="model.radius" :rules="[rules.required, rules.float]" label="Radius" standout
      dense></q-input>
    <q-input v-show="modelStore.selectedModel.file == 'RingOnRing' & !model.ownModel" class="my-input" v-model="model.radius2"
      :rules="[rules.required, rules.float]" label="Radius 2" standout dense></q-input>
    <q-input class="my-input" v-model="model.discretization" v-show="!model.ownModel & modelStore.selectedModel.file != 'RVE'"
      :rules="[rules.required, rules.int]" label="Discretization" standout dense></q-input>
    <q-input class="my-input" v-model="model.horizon" v-show="model.ownModel" :rules="[rules.required, rules.posFloat]"
      label="Horizon" standout dense></q-input>
    <q-input class="my-input" v-model="model.amplitudeFactor"
      v-show="!model.ownModel & modelStore.selectedModel.file == 'Smetana'" :rules="[rules.required, rules.posFloat]"
      label="Amplitude Factor" standout dense></q-input>
    <q-input class="my-input" v-model="model.wavelength" v-show="!model.ownModel & modelStore.selectedModel.file == 'Smetana'"
      :rules="[rules.required, rules.posFloat]" label="Wavelength" standout dense></q-input>
    <q-toggle class="my-toggle" v-show="modelStore.selectedModel.file == 'Dogbone' & !model.ownModel"
      v-model="model.structured" label="Structured" dense></q-toggle>
    <q-toggle class="my-toggle" v-show="!model.ownModel & modelStore.selectedModel.file != 'RVE'"
      v-model="model.twoDimensional" label="Two Dimensional" dense></q-toggle>
    <q-toggle class="my-toggle" v-model="model.rotatedAngles"
      v-show="!model.ownModel & modelStore.selectedModel.file != 'RVE' & modelStore.selectedModel.file != 'Dogbone'"
      label="Rotated Angles" dense></q-toggle>
    <div class="row"
      v-show="model.rotatedAngles & !model.ownModel & modelStore.selectedModel.file != 'RVE' & modelStore.selectedModel.file != 'Dogbone'">
      <div class="my-input">
        <q-input v-model="model.angles[0]" label="Angle 0" standout dense></q-input>
      </div>
      <div class="my-input">
        <q-input v-model="model.angles[1]" label="Angle 1" standout dense></q-input>
      </div>
      <div class="my-input">
        <q-input v-model="model.angles[2]" label="Angle 2" standout dense></q-input>
      </div>
      <div class="my-input">
        <q-input v-model="model.angles[3]" label="Angle 3" standout dense></q-input>
      </div>
    </div> -->
    <!-- <div v-show="modelStore.selectedModel.file=='RVE' & !model.ownModel">
                <v-text-field

                            class="my-input"
                    v-model="micofam.RVE.rve_fvc"
                    :rules="[rules.required, rules.float]"
                    label="rve_fvc"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.RVE.rve_radius"
                    :rules="[rules.required, rules.float]"
                    label="rve_radius"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.RVE.rve_lgth"
                    :rules="[rules.required, rules.float]"
                    label="rve_lgth"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.RVE.rve_dpth"
                    :rules="[rules.required, rules.float]"
                    label="rve_dpth"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.Mesh.mesh_fib"
                    :rules="[rules.required, rules.float]"
                    label="mesh_fib"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.Mesh.mesh_lgth"
                    :rules="[rules.required, rules.float]"
                    label="mesh_lgth"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.Mesh.mesh_dpth"
                    :rules="[rules.required, rules.float]"
                    label="mesh_dpth"
                    standout
                    dense
                ></v-text-field>
                <v-text-field

                            class="my-input"
                    v-model="micofam.Mesh.mesh_aa"
                    :rules="[rules.required]"
                    label="mesh_aa"
                    standout
                    dense
                ></v-text-field>
            </div> -->
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import { useDefaultStore } from 'src/stores/default-store';
import { useModelStore } from 'src/stores/model-store';
import { getConfig, getModels, getValves, getJobFolders } from 'src/client'
import rules from 'assets/rules.js';

export default defineComponent({
  name: 'ModelSettings',
  setup() {
    const store = useDefaultStore();
    const modelStore = useModelStore();
    const model = computed(() => modelStore.modelData.model)
    return {
      store,
      modelStore,
      model,
      rules
    }
  },
  created() {
    this.$bus.on('resetData', () => {
      this.resetData()
    })
    this.$bus.on('getJobFolders', () => {
      this._getJobFolders()
    })
  },
  data() {
    return {
      modelFolderNameList: ['Default'],
      filteredModelFolderNameList: [],
    };
  },
  methods: {
    resetData() {
      getConfig({ configFile: this.modelStore.selectedModel.file }).then((response) => {
        this.modelStore.modelData = structuredClone(response)
      })
        .catch((error) => {
          this.$q.notify({
            type: 'negative',
            message: error.body.detail
          })
        })
      getValves({ modelName: this.modelStore.selectedModel.file }).then((response) => {
        this.modelStore.modelParams = structuredClone(response)
      }).catch((error) => {
        this.$q.notify({
          type: 'negative',
          message: error.body.detail
        })
      })
    },
    _getJobFolders() {
      getJobFolders({ modelName: this.modelStore.selectedModel.file }).then((response) => {
        this.modelFolderNameList = response.data
      })
        .catch((error) => {
          this.$q.notify({
            type: 'negative',
            message: error.body.detail
          })
        })
    },
    async selectMethod() {
      // this.viewStore.viewLoading = true
      const response = getValves({
        modelName: this.modelStore.selectedModel.file
      })
      this.modelStore.modelParams = response
      // this.viewStore.viewLoading = false
      this._getJobFolders()
    },
    async switchOwnModels() {
      if (!this.model.ownModel) {
        this.modelStore.selectedModel = {
          title: 'Compact Tenison',
          file: 'CompactTension',
        }
      }
      await this.selectMethod()
    },
    createValue(val, done) {

      if (val.length > 0) {
        if (!this.modelFolderNameList.includes(val)) {
          this.modelFolderNameList.push(val)
        }
        done(val, 'toggle')
      }
    },

    filterFn(val, update) {
      update(() => {
        if (val === '') {
          this.filteredModelFolderNameList = this.modelFolderNameList
        }
        else {
          const needle = val.toLowerCase()
          this.filteredModelFolderNameList = this.modelFolderNameList.filter(
            v => v.toLowerCase().indexOf(needle) > -1
          )
        }
      })
    }
  },
  async beforeMount() {
    this.modelStore.availableModels = await getModels()
    await this.selectMethod()
  },
  watch: {
    'modelStore.selectedModel': {
      handler() {
        localStorage.setItem('selectedModel', JSON.stringify(this.modelStore.selectedModel));
        if (!this.modelStore.modelData.model.ownModel) {
          this.$bus.emit('showModelImg', this.modelStore.selectedModel.file)
          // this.resetData()
        }
        this.$bus.emit('getStatus')
      },
      deep: true,
    },
  }
})
</script>

// src/lib/components/expansions/Model.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { getModels, getValves, getJobFolders } from '$lib/client';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Label from '$lib/components/ui/Label.svelte';

  const model = $derived(modelStore.modelData.model);

  let modelFolderNameList = $state(['Default']);

  function _getJobFolders() {
    getJobFolders({ modelName: modelStore.selectedModel.file })
      .then((response) => (modelFolderNameList = response))
      .catch((error) => notify.apiError(error));
  }

  async function selectMethod() {
    modelStore.modelParams = await getValves({ modelName: modelStore.selectedModel.file });
    _getJobFolders();
  }

  function selectModelFolderName() {
    bus.emit('getStatus' as never);
  }

  async function switchOwnModels() {
    if (!model.ownModel) {
      modelStore.selectedModel = { title: 'Compact Tenison', file: 'CompactTension' };
    }
    await selectMethod();
  }

  function onSelectedModelChange() {
    if (typeof window !== 'undefined') {
      localStorage.setItem('selectedModel', JSON.stringify(modelStore.selectedModel));
    }
    if (!modelStore.modelData.model.ownModel) {
      bus.emit('showModelImg' as never, modelStore.selectedModel.file as never);
    }
    bus.emit('getStatus' as never);
  }

  onMount(() => {
    bus.on('getJobFolders' as never, _getJobFolders);
    (async () => {
      modelStore.availableModels = await getModels();
      await _getJobFolders();
    })();
    return () => bus.off('getJobFolders' as never, _getJobFolders);
  });
</script>

<div class="space-y-3 p-3">
  <Toggle
    checked={model.ownModel}
    onCheckedChange={(v: boolean) => {
      model.ownModel = v;
      switchOwnModels();
    }}
    label="Own Model"
    disabled={defaultStore.trial}
  />

  {#if !model.ownModel}
    <div class="max-w-xs space-y-1">
      <Label for="model-select">Model Name</Label>
      <Select
        id="model-select"
        value={modelStore.selectedModel.file}
        onchange={(e) => {
          const file = (e.target as HTMLSelectElement).value;
          const m = modelStore.availableModels.find((x) => x.file === file);
          if (m) modelStore.selectedModel = m;
          onSelectedModelChange();
          selectMethod();
        }}
      >
        {#each modelStore.availableModels as m, mIdx (m.file ?? mIdx)}
          <option value={m.file}>{m.title}</option>
        {/each}
      </Select>
    </div>
  {:else}
    <div class="max-w-xs space-y-1">
      <Label for="model-name">Model Name</Label>
      <Input
        id="model-name"
        bind:value={modelStore.selectedModel.file}
        oninput={onSelectedModelChange}
      />
    </div>
  {/if}

  <div class="max-w-xs space-y-1">
    <Label for="model-subname">Model Subname</Label>
    <input
      id="model-subname"
      list="model-folder-names"
      bind:value={model.modelFolderName}
      onchange={selectModelFolderName}
      class="flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm"
    />
    <datalist id="model-folder-names">
      {#each modelFolderNameList as name, folderIdx (name ?? folderIdx)}
        <option value={name}></option>
      {/each}
    </datalist>
  </div>

  {#if model.ownModel}
    <div class="max-w-xs space-y-1">
      <Label for="mesh-file">Mesh File</Label>
      <Input id="mesh-file" bind:value={model.meshFile} />
    </div>
  {/if}

  <Toggle bind:checked={model.twoDimensional} label="Two Dimensional" />

  {#if !model.ownModel}
    <div class="space-y-2 border-t border-border pt-3">
      {#each modelStore.modelParams.valves ?? [] as param, paramIdx (param.name ?? paramIdx)}
        {#if !param.depends || modelStore.modelParams.valves?.find((o) => o.name === param.depends)?.value}
          {#if typeof param.value !== 'boolean' && ['text', 'number'].includes(param.type)}
            <div class="max-w-xs space-y-1">
              <Label for={`valve-${param.name}`}>{param.label}</Label>
              <Input id={`valve-${param.name}`} type={param.type} bind:value={param.value} title={param.description} />
            </div>
          {:else if param.type === 'select' && param.options}
            <div class="max-w-xs space-y-1">
              <Label for={`valve-${param.name}`}>{param.label}</Label>
              <Select id={`valve-${param.name}`} bind:value={param.value} title={param.description}>
                {#each Array.isArray(param.options) ? param.options : [param.options] as opt (opt)}
                  <option value={opt}>{opt}</option>
                {/each}
              </Select>
            </div>
          {:else if param.type === 'checkbox'}
            <Toggle bind:checked={param.value} label={param.label} />
          {/if}
        {/if}
      {/each}
    </div>
  {/if}
</div>
