// frontend/app/src/components/expansions/Thermal.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div>
    <q-toggle class="my-toggle" v-model="thermal.enabled" label="Enabled" standout dense></q-toggle>
    <div v-if="thermal.enabled">
      <q-separator></q-separator>
      <q-list v-for="thermalModel, index in thermal.thermalModels" :key="thermalModel.thermalModelId"
        style="padding: 0px">
        <div
          v-bind:style="(thermalModel.thermalModelsId % 2 == 0) ? 'background-color: rgba(190, 190, 190, 0.1);' : 'background-color: rgba(255, 255, 255, 0.0);'">
          <h4 class="my-title">Thermal {{ thermalModel.thermalModelsId }}</h4>
          <div class="row my-row">
            <q-input class="my-input" v-model="thermalModel.name" :rules="[rules.required, rules.name]"
              :label="thermalKeys.name" standout dense></q-input>
            <q-btn flat icon="fas fa-trash-alt" @click="removeThermalModel(index)">
              <q-tooltip>
                Remove Thermal Model
              </q-tooltip>
            </q-btn>
          </div>
          <div class="row my-row">
            <div class="row my-row">
              <q-select class="my-input" v-model="thermalModel.thermalModel" use-input use-chips multiple
                input-debounce="0" :options="thermalModelNames" @filter="filterFn"
                style="width: 250px; margin-bottom:20px;" :label="thermalKeys.thermalType" standout dense></q-select>
              <q-select class="my-input" :options="thermalTypes" v-model="thermalKeys.thermalType"
                :label="thermalKeys.thermalType" standout dense></q-select>
            </div>
            <div class="row my-row">
              <q-input class="my-input" v-model="thermalModel.thermalConductivity"
                :rules="[rules.required, rules.float]" :label="thermalKeys.thermalConductivity" standout
                dense></q-input>
              <q-input class="my-input" v-model="thermalModel.heatTransferCoefficient"
                :rules="[rules.required, rules.float]" :label="thermalKeys.heatTransferCoefficient" standout
                dense></q-input>
            </div>
            <div class="row my-row">
              <q-input class="my-input" v-model="thermalModel.thermalExpansionCoefficient"
                :rules="[rules.required, rules.float]" :label="thermalKeys.thermalExpansionCoefficient" clearable
                standout dense></q-input>
              <q-input class="my-input" v-model="thermalModel.environmentalTemperature"
                :rules="[rules.required, rules.float]" :label="thermalKeys.environmentalTemperature" clearable standout
                dense></q-input>
            </div>
            <q-separator></q-separator>
            <h6 class="my-title">Additive</h6>
            <div class="row my-row">
              <q-input class="my-input" v-model="thermalModel.printBedTemperature"
                :rules="[rules.required, rules.float]" :label="thermalKeys.printBedTemperature" clearable standout
                dense></q-input>
              <q-input class="my-input" v-model="thermalModel.thermalConductivityPrintBed"
                :rules="[rules.required, rules.float]" :label="thermalKeys.thermalConductivityPrintBed" clearable
                standout dense></q-input>
              <q-input class="my-input" v-model="thermalModel.printBedZCoord" :rules="[rules.required, rules.float]"
                :label="thermalKeys.printBedZCoord" clearable standout dense></q-input>
            </div>
            <q-separator></q-separator>
            <h6 class="my-title">HETVAL</h6>
            <div class="row my-row">
              <q-input class="my-input" v-model="thermalModel.file" :label="thermalKeys.file" clearable standout
                dense></q-input>
              <q-input class="my-input" v-model="thermalModel.numStateVars" :rules="[rules.required, rules.float]"
                :label="thermalKeys.numStateVars" clearable standout dense></q-input>
              <q-input class="my-input" v-model="thermalModel.predefinedFieldNames"
                :label="thermalKeys.predefinedFieldNames" clearable standout dense></q-input>
            </div>
          </div>
          <q-separator></q-separator>
        </div>
      </q-list>

      <q-btn flat icon="fas fa-plus" @click="addThermalModel">
        <q-tooltip>
          Add Thermal Model
        </q-tooltip>
      </q-btn>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, toRaw } from 'vue'
import { useModelStore } from 'src/stores/model-store';
import type { ThermalModel } from 'src/client';
import rules from 'assets/rules.js';

export default defineComponent({
  name: 'ThermalSettings',
  setup() {
    const store = useModelStore();
    const thermal = computed(() => store.modelData.thermal)
    return {
      store,
      thermal,
      rules
    }
  },
  data() {
    return {
      thermalModelNames: ['Thermal Flow', 'Heat Transfer', 'Thermal Expansion'],
      thermalTypes: ['Bond based'],
      thermalKeys: {
        name: 'Name',
        thermalType: 'Type',
        heatTransferCoefficient: 'Heat Transfer Coefficient',
        environmentalTemperature: 'Environmental Temperature',
        thermalConductivity: 'Thermal Conductivity',
        thermalExpansionCoefficient: 'Thermal Expansion Coefficient',
        thermalConductivityPrintBed: 'Thermal Conductivity Print Bed',
        printBedTemperature: 'Print Bed Temperature',
        printBedZCoord: 'Print Bed Z Coordinate',
        file: 'File',
        numStateVars: 'Number of State Variables',
        predefinedFieldNames: 'Predefined Field Names',
      },
      filterOptions: this.thermalModelNames,
    };
  },
  methods: {
    filterFn(val, update) {
      update(() => {
        if (val === '') {
          this.filterOptions = this.thermalModelNames
        }
        else {
          const needle = val.toLowerCase()
          this.filterOptions = this.thermalModelNames.filter(
            v => v.toLowerCase().indexOf(needle) > -1
          )
        }
      })
    },
    addThermalModel() {
      if (!this.thermal.thermalModels) {
        this.thermal.thermalModels = []
      }
      const len = this.thermal.thermalModels.length;
      // const newItem = len > 0 ? structuredClone(toRaw(this.thermal.thermalModels[len - 1])) : {} as ThermalModel;
      const newItem = {} as ThermalModel;
      newItem.thermalModelsId = len + 1
      newItem.name = 'Thermal Model ' + (len + 1)
      this.thermal.thermalModels.push(newItem);
    },
    removeThermalModel(index: number) {
      this.thermal.thermalModels.splice(index, 1);
      this.thermal.thermalModels.forEach((model, i) => {
        model.thermalModelsId = i + 1
      })
    },
  }
})
</script>

// src/lib/components/expansions/Thermal.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Plus, Trash2 } from 'lucide-svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import type { ThermalModel, Thermal } from '$lib/client';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  const thermal = $derived(modelStore.modelData.thermal ?? ({} as Thermal));
  const thermalModelNames = ['Thermal Flow', 'Heat Transfer', 'Thermal Expansion'];
  const thermalTypes = ['Bond based'];

  function addThermalModel() {
    if (!thermal.thermalModels) thermal.thermalModels = [];
    const list = thermal.thermalModels;
    const len = list.length;
    const newItem =
      len > 0
        ? (structuredClone($state.snapshot(list[len - 1])) as ThermalModel)
        : ({} as ThermalModel);
    newItem.thermalModelsId = len + 1;
    newItem.name = `Thermal Model ${len + 1}`;
    list.push(newItem);
  }

  function removeThermalModel(index: number) {
    thermal.thermalModels!.splice(index, 1);
    thermal.thermalModels!.forEach((m, i) => (m.thermalModelsId = i + 1));
  }
</script>

<div class="space-y-3 p-3">
  <Toggle bind:checked={thermal.enabled} label="Enabled" />

  {#if thermal.enabled}
    {#each thermal.thermalModels ?? [] as thermalModel, index (thermalModel.thermalModelsId ?? index)}
      <div class="border-border space-y-3 rounded-md border p-3">
        <h4 class="font-medium">Thermal {thermalModel.thermalModelsId}</h4>

        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`th-name-${index}`}>Name</Label>
            <Input id={`th-name-${index}`} bind:value={thermalModel.name} />
          </div>
          <Button
            variant="ghost"
            size="icon"
            onclick={() => removeThermalModel(index)}
            title="Remove Thermal Model"
          >
            <Trash2 class="h-4 w-4" />
          </Button>
        </div>

        <div class="flex flex-wrap items-end gap-3">
          <div class="w-56 space-y-1">
            <Label for={`th-model-${index}`}>Type</Label>
            <select
              id={`th-model-${index}`}
              multiple
              bind:value={thermalModel.thermalModel}
              class="border-input bg-background h-20 w-full rounded-md border px-2 py-1 text-sm"
            >
              {#each thermalModelNames as name (name)}
                <option value={name}>{name}</option>
              {/each}
            </select>
          </div>
          <div class="space-y-1">
            <Label for={`th-type-${index}`}>Bond Type</Label>
            <Select id={`th-type-${index}`} bind:value={thermalModel.thermalType}>
              {#each thermalTypes as type (type)}
                <option value={type}>{type}</option>
              {/each}
            </Select>
          </div>
        </div>

        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`th-cond-${index}`}>Thermal Conductivity</Label>
            <Input
              id={`th-cond-${index}`}
              type="number"
              bind:value={thermalModel.thermalConductivity}
            />
          </div>
          <div class="space-y-1">
            <Label for={`th-htc-${index}`}>Heat Transfer Coefficient</Label>
            <Input
              id={`th-htc-${index}`}
              type="number"
              bind:value={thermalModel.heatTransferCoefficient}
            />
          </div>
        </div>

        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`th-exp-${index}`}>Thermal Expansion Coefficient</Label>
            <Input
              id={`th-exp-${index}`}
              type="number"
              bind:value={thermalModel.thermalExpansionCoefficient}
            />
          </div>
          <div class="space-y-1">
            <Label for={`th-env-${index}`}>Environmental Temperature</Label>
            <Input
              id={`th-env-${index}`}
              type="number"
              bind:value={thermalModel.environmentalTemperature}
            />
          </div>
        </div>

        <h5 class="text-muted-foreground text-sm font-medium">Additive</h5>
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`th-pbt-${index}`}>Print Bed Temperature</Label>
            <Input
              id={`th-pbt-${index}`}
              type="number"
              bind:value={thermalModel.printBedTemperature}
            />
          </div>
          <div class="space-y-1">
            <Label for={`th-pbc-${index}`}>Thermal Conductivity Print Bed</Label>
            <Input
              id={`th-pbc-${index}`}
              type="number"
              bind:value={thermalModel.thermalConductivityPrintBed}
            />
          </div>
          <div class="space-y-1">
            <Label for={`th-pbz-${index}`}>Print Bed Z Coordinate</Label>
            <Input id={`th-pbz-${index}`} type="number" bind:value={thermalModel.printBedZCoord} />
          </div>
        </div>

        <h5 class="text-muted-foreground text-sm font-medium">HETVAL</h5>
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`th-file-${index}`}>File</Label>
            <Input id={`th-file-${index}`} bind:value={thermalModel.file} />
          </div>
          <div class="space-y-1">
            <Label for={`th-nsv-${index}`}>Number of State Variables</Label>
            <Input id={`th-nsv-${index}`} type="number" bind:value={thermalModel.numStateVars} />
          </div>
          <div class="space-y-1">
            <Label for={`th-pfn-${index}`}>Predefined Field Names</Label>
            <Input id={`th-pfn-${index}`} bind:value={thermalModel.predefinedFieldNames} />
          </div>
        </div>
      </div>
    {/each}

    <Button variant="outline" size="sm" onclick={addThermalModel}>
      <Plus class="h-4 w-4" /> Add Thermal Model
    </Button>
  {/if}
</div>
