// src/routes/tools/+page.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import ConversionCard from '$lib/components/tools/ConversionCard.svelte';
  import SiConversionCard from '$lib/components/tools/SiConversionCard.svelte';
  import StiffnessCard from '$lib/components/tools/StiffnessCard.svelte';
  import AmplitudeCard from '$lib/components/tools/AmplitudeCard.svelte';
</script>

<svelte:head>
  <title>Tools — PeriHub</title>
</svelte:head>

<div class="mx-auto flex max-w-5xl flex-col items-center gap-8 px-6 py-10">
  <SiConversionCard />
  <ConversionCard />
  <StiffnessCard />
  <AmplitudeCard />
</div>

// gui/app/src/pages/Tools.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
    <q-page class="flex-center">
        <ConversionCard/>
        <SiConversionCard/>
    </q-page>
</template>

<script>
import { defineComponent } from 'vue'
import ConversionCard from 'components/tools/ConversionCard.vue'
import SiConversionCard from 'components/tools/SiConversionCard.vue'

export default defineComponent({
    name: "GuidePage",
    components: {
        ConversionCard,
        SiConversionCard,
    },
});
</script>

<style>
</style>
