// src/lib/components/tools/AmplitudeCard.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Tabs } from 'bits-ui';
  import Card from '$lib/components/ui/Card.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import PlotlyChart from '$lib/components/views/PlotlyChart.svelte';
  import CodeBlock from '$lib/components/views/CodeBlock.svelte';

  const amplitudeTypes = ['Type 1', 'Type 2', 'Sinus'];

  let amplitude = $state({
    max: 10,
    min: 2,
    frequency: 5,
    end: 5,
    type: 'Type 1'
  });

  let valueOutput = $state('A*sin(B*(t-C))+D');
  let tab = $state('plotly');

  let plotData = $state<{ name: string; x: number[]; y: number[]; type: string }[]>([
    { name: 'Load', x: [1, 2, 3, 4], y: [10, 15, 20, 17], type: 'scatter' }
  ]);

  const plotLayout = {
    showlegend: true,
    hovermode: 'compare',
    bargap: 0,
    xaxis: { showgrid: true, zeroline: true, color: 'white' },
    yaxis: { showgrid: true, zeroline: true, color: 'white' },
    plot_bgcolor: '#2D2D2D',
    paper_bgcolor: '#2D2D2D',
    font: { color: 'white' },
    modebar: { color: 'white' }
  };

  function plotType1() {
    const { max, min, frequency, end } = amplitude;
    const n = 10 * frequency;
    const x: number[] = [];
    const y: number[] = [];
    for (let i = 0; i < n; i++) {
      const t = (i / (n - 1)) * end;
      x[i] = t;
      for (let j = 0; j < frequency; j++) {
        if (j === 0) {
          if (t <= (1 / frequency) * end) {
            y[i] = (t / ((1 / frequency) * end)) * max;
            break;
          }
        } else if (j % 2 !== 0) {
          if ((j / frequency) * end < t && t <= ((j + 1) / frequency) * end) {
            y[i] = max - ((t - (j / frequency) * end) / ((1 / frequency) * end)) * (max - min);
            break;
          }
        } else {
          if ((j / frequency) * end < t && t <= ((j + 1) / frequency) * end) {
            y[i] = min + ((t - (j / frequency) * end) / ((1 / frequency) * end)) * (max - min);
            break;
          }
        }
      }
    }
    plotData = [{ ...plotData[0], x, y }];
    valueOutput =
      `double max = ${max};\n` +
      `double min = ${min};\n` +
      `double frequency = ${frequency};\n` +
      `double end = ${end};\n` +
      'int idx = 0;\n' +
      'while (idx < frequency) {\n' +
      ' if (idx == 0) {\n' +
      '   if (t <= 1 / frequency *end) {\n' +
      '     value = (t / ((1 / frequency) * end)) * max;\n' +
      '   }\n' +
      ' }\n' +
      ' else if (idx % 2 != 0) {\n' +
      '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) {\n' +
      '     value = max - ((t - (idx / frequency) * end) / ((1 / frequency) * end)) * (max - min);\n' +
      '   }\n' +
      ' }\n' +
      ' else if (idx % 2 == 0) {\n' +
      '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) {\n' +
      '     value = min + ((t - (idx / frequency) * end) / ((1 / frequency) * end)) * (max - min);\n' +
      '   }\n' +
      ' }\n' +
      ' idx = idx + 1;\n' +
      '}\n';
  }

  function plotType2() {
    const { max, frequency, end } = amplitude;
    const n = 1000;
    const x: number[] = [];
    const y: number[] = [];
    for (let i = 0; i < n; i++) {
      const t = (i / (n - 1)) * end;
      x[i] = t;
      for (let j = 0; j < frequency; j++) {
        if (j === 0) {
          if (t <= (1 / frequency) * end) {
            y[i] = (t / end) * max * 2;
            break;
          }
        } else if (j % 2 !== 0) {
          if ((j / frequency) * end < t && t <= ((j + 1) / frequency) * end) {
            y[i] = (j / frequency) * max * 2 - ((j - 1) / frequency) * max;
            break;
          }
        } else {
          if ((j / frequency) * end < t && t <= ((j + 1) / frequency) * end) {
            y[i] = ((t - ((j / 2) * end) / frequency) / end) * max * 2;
            break;
          }
        }
      }
    }
    plotData = [{ ...plotData[0], x, y }];
    valueOutput =
      `double max = ${max};\n` +
      `double frequency = ${frequency};\n` +
      `double end = ${end};\n` +
      'int idx = 0;\n' +
      'while (idx < frequency) {\n' +
      ' if (idx == 0) {\n' +
      '   if (t <= 1 / frequency *end) {\n' +
      '     value = (t / end) * max * 2;\n' +
      '   }\n' +
      ' }\n' +
      ' else if (idx % 2 != 0) {\n' +
      '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) {\n' +
      '     value = (idx / frequency) * max * 2 - ((idx - 1) / frequency) * max;\n' +
      '   }\n' +
      ' }\n' +
      ' else if (idx % 2 == 0) {\n' +
      '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) {\n' +
      '     value = ((t - ((idx / 2) * end) / frequency) / end) * max * 2;\n' +
      '   }\n' +
      ' }\n' +
      ' idx = idx + 1;\n' +
      '}\n';
  }

  function plotSin() {
    const { max, min, frequency, end } = amplitude;
    const n = 100 * frequency;
    const offset = (max + min) / 2;
    const R = (max - min) / 2;
    const x: number[] = [];
    const y: number[] = [];
    for (let i = 0; i < n; i++) {
      const t = (i / (n - 1)) * end;
      x[i] = t;
      y[i] = R * Math.sin(2 * Math.PI * frequency * t - Math.PI / 2) + offset;
    }
    plotData = [{ ...plotData[0], x, y }];
    valueOutput = `${R} * sin(2 * pi * ${frequency} * t - pi / 2) + ${offset}`;
  }

  function replot() {
    if (amplitude.type === 'Type 1') plotType1();
    else if (amplitude.type === 'Type 2') plotType2();
    else plotSin();

    if (typeof window !== 'undefined') {
      localStorage.setItem('amplitude', JSON.stringify(amplitude));
    }
  }

  $effect(() => {
    // re-run whenever any amplitude field changes
    void amplitude.max;
    void amplitude.min;
    void amplitude.frequency;
    void amplitude.end;
    void amplitude.type;
    replot();
  });

  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('amplitude');
    if (stored) {
      try {
        amplitude = { ...amplitude, ...JSON.parse(stored) };
      } catch {
        /* ignore malformed cache */
      }
    }
  }
</script>

<Card class="w-full max-w-4xl p-5">
  <h2 class="text-lg font-semibold">Amplitude Generator</h2>

  <div class="my-4 border-t border-border"></div>

  <div class="grid grid-cols-1 gap-6 lg:grid-cols-[minmax(0,16rem)_1fr]">
    <div class="space-y-3">
      <div class="space-y-1">
        <Label for="amp-max">Max</Label>
        <Input id="amp-max" type="number" bind:value={amplitude.max} />
      </div>
      {#if amplitude.type !== 'Type 2'}
        <div class="space-y-1">
          <Label for="amp-min">Min</Label>
          <Input id="amp-min" type="number" bind:value={amplitude.min} />
        </div>
      {/if}
      <div class="space-y-1">
        <Label for="amp-freq">Frequency</Label>
        <Input id="amp-freq" type="number" bind:value={amplitude.frequency} />
      </div>
      <div class="space-y-1">
        <Label for="amp-end">Time</Label>
        <Input id="amp-end" type="number" bind:value={amplitude.end} />
      </div>
      <div class="space-y-1">
        <Label for="amp-type">Type of Amplitude</Label>
        <Select id="amp-type" bind:value={amplitude.type}>
          {#each amplitudeTypes as type (type)}
            <option value={type}>{type}</option>
          {/each}
        </Select>
      </div>
    </div>

    <Tabs.Root bind:value={tab}>
      <Tabs.List class="flex gap-1 border-b border-border">
        <Tabs.Trigger
          value="plotly"
          class="rounded-t-md px-3 py-2 text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground"
        >
          Plotly
        </Tabs.Trigger>
        <Tabs.Trigger
          value="output"
          class="rounded-t-md px-3 py-2 text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground"
        >
          Output
        </Tabs.Trigger>
      </Tabs.List>
      <Tabs.Content value="plotly" class="pt-3">
        <PlotlyChart data={plotData} layout={plotLayout} />
      </Tabs.Content>
      <Tabs.Content value="output" class="pt-3">
        <CodeBlock bind:value={valueOutput} editable={false} />
      </Tabs.Content>
    </Tabs.Root>
  </div>
</Card>

// frontend/app/src/components/tools/AmplitudeCard.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <q-card bordered>
    <q-card-section>
      <div class="text-h6">Amplitude Generator</div>
      <!-- <div class="text-subtitle2">Enter two constants to run the calculations</div> -->
    </q-card-section>

    <q-separator inset></q-separator>

    <q-card-section>
      <q-splitter v-model="verticalSplitterModel" class="body" :limits="[30, 60]">
        <template v-slot:before>
          <div class="col">
            <q-input class="my-input" v-model="amplitude.max" label="Max" standout dense></q-input>
            <q-input class="my-input" v-show="amplitude.type != 'Type 2'" v-model="amplitude.min" label="Min" standout
              dense></q-input>
            <q-input class="my-input" v-model="amplitude.frequency" label="Frequency" standout dense></q-input>
            <q-input class="my-input" v-model="amplitude.end" label="Time" standout dense></q-input>
            <!-- <q-input class="my-input" v-show="amplitude.type == 'Sinus'" v-model="amplitude.t_max" label="t Max"
              standout dense></q-input> -->
            <q-select class="my-select" :options="amplitudeTypes" v-model="amplitude.type" label="Type of Amplitude"
              standout dense></q-select>
          </div>
        </template>

        <template v-slot:after>
          <q-tabs v-model="tab_id" dense class="text-grey" active-color="primary" indicator-color="primary"
            align="justify" color="deep-purple accent-4" left max-width="1100">
            <q-tab name="plotly" label="Plotly"></q-tab>
            <q-tab name="output" label="Output"></q-tab>
          </q-tabs>

          <q-tab-panels v-model="tab_id" animated style="height:100%">
            <q-tab-panel name="plotly">
              <q-card>
                <VuePlotly :data="plotData" :layout="plotLayout" :options="plotOptions" :display-mode-bar="true"
                  :autoResize="true" :scrollZoom="true">
                </VuePlotly>
              </q-card>
            </q-tab-panel>
            <q-tab-panel name="output">
              <q-card>
                <prism-editor class="my-editor" v-model="valueOutput" :highlight="highlighter"
                  line-numbers></prism-editor>
              </q-card>
            </q-tab-panel>
          </q-tab-panels>
        </template>
      </q-splitter>
    </q-card-section>
  </q-card>
</template>

<script lang="ts">
import { defineComponent, toRaw } from 'vue'
import { VuePlotly } from 'vue3-plotly'
import { PrismEditor } from 'vue-prism-editor';
import 'vue-prism-editor/dist/prismeditor.min.css'; // import the styles somewhere
import { highlight, languages } from 'prismjs/components/prism-core';
import 'prismjs/components/prism-clike';
import 'prismjs/components/prism-javascript';
import 'prismjs/themes/prism-tomorrow.css'; // import syntax highlighting styles
export default defineComponent({
  name: 'AmplitudeCard',
  components: {
    PrismEditor,
    VuePlotly,
  },
  data() {
    return {
      verticalSplitterModel: 50,
      tab_id: 'plotly',
      amplitudeTypes: ['Type 1', 'Type 2', 'Sinus'],
      amplitude: {
        max: 10,
        min: 2,
        frequency: 5,
        end: 5,
        type: 'Type 1',
        t_max: 1,
      },
      valueOutput: 'A*sin(B*(t-C))+D',
      plotData: [
        {
          name: 'Load',
          x: [1, 2, 3, 4],
          y: [10, 15, 20, 17],
          type: 'scatter',
        },
      ],
      plotLayout: {
        showlegend: true,
        // margin: { t: 50 },
        hovermode: 'compare',
        bargap: 0,
        xaxis: {
          showgrid: true,
          zeroline: true,
          color: 'white',
        },
        yaxis: {
          showgrid: true,
          zeroline: true,
          color: 'white',
        },
        plot_bgcolor: '#2D2D2D',
        paper_bgcolor: '#2D2D2D',
        font: {
          color: 'white',
        },
        modebar: {
          color: 'white',
          // color: '#6E6E6E'
        },
      },
      plotOptions: {
        scrollZoom: true,
        setBackground: 'black',
      },
    }
  },
  methods: {
    highlighter(code: string) {
      return highlight(code, languages.js); // languages.<insert language> to return html with markup
    },
    plot() {
      const tempData = structuredClone(toRaw(this.plotData));
      tempData[0]!.x = [];
      tempData[0]!.y = [];
      const n = 10 * this.amplitude.frequency;
      const max = this.amplitude.max;
      const min = this.amplitude.min;
      const frequency = this.amplitude.frequency;
      const end = this.amplitude.end;
      for (let i = 0; i < n; i++) {
        const t = (i / (n - 1)) * end;
        tempData[0]!.x[i] = t;
        for (let j = 0; j < frequency; j++) {
          if (j == 0) {
            if (t <= (1 / frequency) * end) {
              tempData[0]!.y[i] = (t / ((1 / frequency) * end)) * max;
              break;
            }
          } else if (j % 2 != 0) {
            if (
              ((j / frequency) * end < t) &&
              (t <= ((j + 1) / frequency) * end)
            ) {
              tempData[0]!.y[i] =
                max -
                ((t - (j / frequency) * end) / ((1 / frequency) * end)) *
                (max - min);
              break;
            }
          } else if (j % 2 == 0) {
            if (
              ((j / frequency) * end < t) &&
              (t <= ((j + 1) / frequency) * end)
            ) {
              tempData[0]!.y[i] =
                min +
                ((t - (j / frequency) * end) / ((1 / frequency) * end)) *
                (max - min);
              break;
            }
          }
        }
      }
      this.plotData = structuredClone(tempData);
      this.valueOutput =
        'double max = ' +
        this.amplitude.max.toString() +
        ';\n' +
        'double min = ' +
        this.amplitude.min.toString() +
        ';\n' +
        'double frequency = ' +
        this.amplitude.frequency.toString() +
        ';\n' +
        'double end = ' +
        this.amplitude.end.toString() +
        ';\n' +
        'int idx = 0;\n' +
        'while (idx < frequency) \\{\n' +
        ' if (idx == 0) \\{\n' +
        '   if (t <= 1 / frequency *end) \\{\n' +
        '     value = (t / ((1 / frequency) * end)) * max;\n' +
        '   \\}\n' +
        ' \\}\n' +
        ' else if (idx % 2 != 0) \\{\n' +
        '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) \\{\n' +
        '     value = max - ((t - (idx / frequency) * end) / ((1 / frequency) * end)) * (max - min);\n' +
        '   \\}\n' +
        ' \\}\n' +
        ' else if (idx % 2 == 0) \\{\n' +
        '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) \\{\n' +
        '     value = min + ((t - (idx / frequency) * end) / ((1 / frequency) * end)) * (max - min);\n' +
        '   \\}\n' +
        ' \\}\n' +
        ' idx = idx + 1;\n' +
        '\\}\n';
    },
    plot2() {
      const tempData = structuredClone(this.plotData);
      tempData[0]!.x = [];
      tempData[0]!.y = [];
      const n = 1000;
      const max = this.amplitude.max;
      const frequency = this.amplitude.frequency;
      const end = this.amplitude.end;
      for (let i = 0; i < n; i++) {
        const t = (i / (n - 1)) * end;
        tempData[0]!.x[i] = t;
        for (let j = 0; j < frequency; j++) {
          if (j == 0) {
            if (t <= (1 / frequency) * end) {
              tempData[0]!.y[i] = (t / end) * max * 2;
              break;
            }
          } else if (j % 2 != 0) {
            if (
              ((j / frequency) * end < t) &&
              (t <= ((j + 1) / frequency) * end)
            ) {
              tempData[0]!.y[i] =
                (j / frequency) * max * 2 - ((j - 1) / frequency) * max;
              break;
            }
          } else if (j % 2 == 0) {
            if (
              ((j / frequency) * end < t) &&
              (t <= ((j + 1) / frequency) * end)
            ) {
              tempData[0]!.y[i] =
                ((t - ((j / 2) * end) / frequency) / end) * max * 2;
              break;
            }
          }
        }
      }
      this.plotData = structuredClone(tempData);
      // this.plotData[0].x = time.split(',');
      this.valueOutput =
        'double max = ' +
        this.amplitude.max.toString() +
        ';\n' +
        'double frequency = ' +
        this.amplitude.frequency.toString() +
        ';\n' +
        'double end = ' +
        this.amplitude.end.toString() +
        ';\n' +
        'int idx = 0;\n' +
        'while (idx < frequency) \\{\n' +
        ' if (idx == 0) \\{\n' +
        '   if (t <= 1 / frequency *end) \\{\n' +
        '     value = (t / end) * max * 2;\n' +
        '   \\}\n' +
        ' \\}\n' +
        ' else if (idx % 2 != 0) \\{\n' +
        '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) \\{\n' +
        '     value = (idx / frequency) * max * 2 - ((idx - 1) / frequency) * max;\n' +
        '   \\}\n' +
        ' \\}\n' +
        ' else if (idx % 2 == 0) \\{\n' +
        '   if ((idx / frequency *end < t) && (t <= (idx + 1) / frequency *end)) \\{\n' +
        '     value = ((t - ((idx / 2) * end) / frequency) / end) * max * 2;\n' +
        '   \\}\n' +
        ' \\}\n' +
        ' idx = idx + 1;\n' +
        '\\}\n';
    },
    sin() {
      const tempData = structuredClone(this.plotData);
      tempData[0]!.x = [];
      tempData[0]!.y = [];
      const n = 100 * this.amplitude.frequency;
      const max = this.amplitude.max;
      const min = this.amplitude.min;
      // const t_max = this.amplitude.t_max;
      const offset = (max + min) / 2;
      const frequency = this.amplitude.frequency;
      const end = this.amplitude.end;
      const R = (max - min) / 2; // Konstante Amplitude
      for (let i = 0; i < n; i++) {
        const t = (i / (n - 1)) * end;
        tempData[0]!.x[i] = t;
        tempData[0]!.y[i] = R * Math.sin(2 * Math.PI * frequency * t - Math.PI / 2) + offset; // Sinuskurve mit konstanter Amplitude
      }
      this.plotData = structuredClone(tempData);
      this.valueOutput = R.toString() + ' * sin(2 * pi * ' + this.amplitude.frequency.toString() + ' * t - pi / 2) + ' + offset.toString();
    },

  },
  mounted() {
    if (localStorage.getItem('amplitude')) {
      this.amplitude = JSON.parse(localStorage.getItem('amplitude')!);
    }
    if (this.amplitude.type == 'Type 1') {
      this.plot();
    } else if (this.amplitude.type == 'Type 2') {
      this.plot2();
    } else if (this.amplitude.type == 'Sinus') {
      this.sin();
    }
  },
  watch: {
    amplitude: {
      handler() {
        console.log('amplitude changed!');
        if (this.amplitude.type == 'Type 1') {
          this.plot();
        } else if (this.amplitude.type == 'Type 2') {
          this.plot2();
        } else if (this.amplitude.type == 'Sinus') {
          this.sin();
        }
        localStorage.setItem('amplitude', JSON.stringify(this.amplitude));
      },
      deep: true,
    },
  }
})
</script>
<style scoped>
.my-input {
  margin-left: 10px;
}
</style>
