// src/lib/components/expansions/Material.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { inv, matrix } from 'mathjs';
  import { Plus, Trash2, Upload } from 'lucide-svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { uploadFiles as uploadFilesApi } from '$lib/client';
  import type { Material, properties as MaterialProperties } from '$lib/client';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import Button from '$lib/components/ui/Button.svelte';

  const materials = $derived(modelStore.modelData.materials ?? []);
  const materialModelNames = [
    'Bond-based Elastic', 'PD Solid Elastic', 'PD Solid Plastic', 'Correspondence Elastic', 'Correspondence Plastic'
  ];
  const materialSymmetries = ['Isotropic', 'Anisotropic', 'Orthotropic', 'Transverse Isotropic'];
  const stabilizationTypes = ['Bond Based', 'State Based', 'Sub Horizon', 'Global Stiffness'];

  let multiSoInput: HTMLInputElement;
  let propsInput: HTMLInputElement;
  let selectedMaterial = 0;

  function editNumStateVars(numStateVars: number) {
    bus.emit('addStateVarsToOutput' as never, numStateVars as never);
  }

  function calculateStiffnessMatrix(materialId: number) {
    const material = materials[materialId]!;
    const sm = material.stiffnessMatrix;
    if (!sm?.calculateStiffnessMatrix) return;

    const E1 = sm.engineeringConstants.E1 as number | null;
    const E2 = sm.engineeringConstants.E2 as number | null;
    let E3 = sm.engineeringConstants.E3 as number | null;
    const G12 = sm.engineeringConstants.G12 as number | null;
    let G13 = sm.engineeringConstants.G13 as number | null;
    let G23 = sm.engineeringConstants.G23 as number | null;
    const nu12 = sm.engineeringConstants.nu12 as number | null;
    let nu13 = sm.engineeringConstants.nu13 as number | null;
    let nu23 = sm.engineeringConstants.nu23 as number | null;

    if (E1 == null || E2 == null || G12 == null || nu12 == null) return;

    if (E3 == null) E3 = E2;
    if (G13 == null) G13 = G12;
    if (nu13 == null) nu13 = nu12;
    if (nu23 == null) nu23 = nu12;
    if (G23 == null) G23 = E2 / (2 * (1 + nu23));

    const compliance = matrix([
      [1 / E1, -nu12 / E1, -nu13 / E1, 0, 0, 0],
      [-nu12 / E1, 1 / E2, -nu23 / E2, 0, 0, 0],
      [-nu13 / E1, -nu23 / E2, 1 / E3, 0, 0, 0],
      [0, 0, 0, 1 / G23, 0, 0],
      [0, 0, 0, 0, 1 / G13, 0],
      [0, 0, 0, 0, 0, 1 / G12]
    ]);
    const s = inv(compliance).toArray() as number[][];

    sm.matrix = {
      C11: s[0]![0]!, C12: s[0]![1]!, C13: s[0]![2]!, C14: s[0]![3]!, C15: s[0]![4]!, C16: s[0]![5]!,
      C22: s[1]![1]!, C23: s[1]![2]!, C24: s[1]![3]!, C25: s[1]![4]!, C26: s[1]![5]!,
      C33: s[2]![2]!, C34: s[2]![3]!, C35: s[2]![4]!, C36: s[2]![5]!,
      C44: s[3]![3]!, C45: s[3]![4]!, C46: s[3]![5]!,
      C55: s[4]![4]!, C56: s[4]![5]!,
      C66: s[5]![5]!
    };
  }

  function uploadSo() {
    multiSoInput.click();
  }

  function onMultiFilePicked(event: Event) {
    const files = (event.target as HTMLInputElement).files;
    if (!files || files.length === 0) return;
    viewStore.modelLoading = true;

    const formData = new FormData();
    Array.from(files).forEach((f) => formData.append('files', f));

    uploadFilesApi({
      modelName: modelStore.selectedModel.title,
      modelFolderName: modelStore.modelData.model.modelFolderName,
      formData
    } as never)
      .then(() => notify.positive('File uploaded'))
      .catch((error) => notify.apiError(error));

    viewStore.modelLoading = false;
  }

  function uploadProps(id: number) {
    propsInput.click();
    selectedMaterial = id;
  }

  function onPropsFilePicked(event: Event) {
    const files = (event.target as HTMLInputElement).files;
    if (!files || files.length === 0) return;

    const fr = new FileReader();
    fr.onload = (e) => {
      const inputString = e.target?.result as string;
      const filteredString = inputString.match(/\*User([\D\S]*?)\*/gi);
      if (!filteredString) return;

      let propsArray = filteredString[0]!.split(/[\n,]/gi).filter((v) => v.trim() !== '');
      propsArray = propsArray.slice(0, propsArray.length - 1);
      const numConstants = propsArray.length - 2;

      if (!propsArray[1]) {
        console.log('Constants not found.');
        return;
      }
      const numConstantsFound = propsArray[1].match(/\d+/);
      if (!numConstantsFound) {
        console.log('Number of constants not found.');
        return;
      }

      if (parseFloat(numConstantsFound[0]!) === numConstants) {
        materials[0]!.properties = [];
        const parameterString = inputString.match(/\*PARAMETER([\D\S]*?)\*HEADING/gi);
        if (!parameterString) {
          console.log('Parameter string not found.');
          return;
        }
        const parameterValues = parameterString[0]!.match(/\w+=([\d.]+)/gi);
        if (!parameterValues) {
          console.log('Parameter values not found.');
          return;
        }

        for (let i = 2; i < propsArray.length; i++) {
          addProp(0);
          let propValue = propsArray[i]!.trim();
          if (propValue.startsWith('<') && propValue.endsWith('>')) {
            const paramName = propValue.slice(1, -1);
            const paramValue = parameterValues.find((p) => p.startsWith(`${paramName}=`));
            if (paramValue) propValue = paramValue.split('=')[1]!;
            else console.log(`Parameter ${paramName} not found.`);
          }
          materials[0]!.properties![i - 2]!.value = parseFloat(propValue);
        }
      } else {
        console.log('Length of Propsarray unexpected');
      }
    };
    fr.readAsText(files.item(0)!);
  }

  function addMaterial() {
    if (!modelStore.modelData.materials) modelStore.modelData.materials = [];
    const list = modelStore.modelData.materials;
    const len = list.length;
    const newItem = len > 0 ? (structuredClone($state.snapshot(list[len - 1])) as Material) : ({} as Material);
    newItem.materialsId = len + 1;
    newItem.name = `Material ${len + 1}`;
    list.push(newItem);
  }

  function removeMaterial(index: number) {
    materials.splice(index, 1);
    materials.forEach((m, i) => (m.materialsId = i + 1));
  }

  function addProp(index: number) {
    const material = materials[index]!;
    if (!material.properties) material.properties = [];
    const len = material.properties.length;
    const newItem =
      len > 0
        ? (structuredClone($state.snapshot(material.properties[len - 1])) as MaterialProperties)
        : ({} as MaterialProperties);
    newItem.materialsPropId = len + 1;
    newItem.name = `Prop_${len + 1}`;
    material.properties.push(newItem);
  }

  function removeProp(index: number, subindex: number) {
    materials[index]!.properties!.splice(subindex, 1);
  }
</script>

<div class="space-y-3 p-3">
  {#each materials as material, index (material.materialsId ?? index)}
    <div class="space-y-3 rounded-md border border-border p-3">
      <h4 class="font-medium">Material {material.materialsId}</h4>

      <div class="flex flex-wrap items-end gap-3">
        <div class="space-y-1">
          <Label for={`mat-name-${index}`}>name</Label>
          <Input id={`mat-name-${index}`} bind:value={material.name} />
        </div>
        <Button variant="ghost" size="icon" onclick={() => removeMaterial(index)} title="Remove Material">
          <Trash2 class="h-4 w-4" />
        </Button>
      </div>

      <div class="w-64 space-y-1">
        <Label for={`mat-type-${index}`}>Material Models</Label>
        <select
          id={`mat-type-${index}`}
          multiple
          bind:value={material.matType}
          class="h-24 w-full rounded-md border border-input bg-background px-2 py-1 text-sm"
        >
          {#each materialModelNames as name (name)}
            <option value={name}>{name}</option>
          {/each}
        </select>
      </div>

      {#if material.matType?.includes('User')}
        <div class="space-y-2 border-t border-border pt-2">
          {#each material.properties ?? [] as prop, subindex (prop.materialsPropId ?? subindex)}
            <div class="flex flex-wrap items-end gap-3">
              <div class="space-y-1">
                <Label for={`mat-prop-${index}-${subindex}`}>{prop.name}</Label>
                <Input id={`mat-prop-${index}-${subindex}`} type="number" bind:value={prop.value} />
              </div>
              <Button variant="ghost" size="icon" onclick={() => removeProp(index, subindex)} title="Remove Property">
                <Trash2 class="h-4 w-4" />
              </Button>
            </div>
          {/each}
          <div class="flex flex-wrap items-end gap-2">
            <Button variant="outline" size="sm" onclick={() => addProp(index)}>
              <Plus class="h-4 w-4" /> Add Property
            </Button>
            <Button variant="outline" size="sm" onclick={() => uploadProps(index)}>
              <Upload class="h-4 w-4" /> Upload Property
            </Button>
            <Button variant="outline" size="sm" onclick={uploadSo}>
              <Upload class="h-4 w-4" /> Upload shared Library
            </Button>
            <div class="space-y-1">
              <Label for={`mat-nsv-${index}`}>Number of State Vars</Label>
              <Input
                id={`mat-nsv-${index}`}
                type="number"
                bind:value={material.numStateVars}
                oninput={() => editNumStateVars(material.numStateVars!)}
              />
            </div>
          </div>
        </div>
      {/if}

      {#if material.materialSymmetry === 'Isotropic'}
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`mat-pr-${index}`}>Poisson's Ratio</Label>
            <Input id={`mat-pr-${index}`} type="number" bind:value={material.poissonsRatio} />
          </div>
          <div class="space-y-1">
            <Label for={`mat-bulk-${index}`}>Bulk Modulus</Label>
            <Input id={`mat-bulk-${index}`} type="number" bind:value={material.bulkModulus} />
          </div>
          <div class="space-y-1">
            <Label for={`mat-shear-${index}`}>Shear Modulus</Label>
            <Input id={`mat-shear-${index}`} type="number" bind:value={material.shearModulus} />
          </div>
          <div class="space-y-1">
            <Label for={`mat-young-${index}`}>Young's Modulus</Label>
            <Input id={`mat-young-${index}`} type="number" bind:value={material.youngsModulus} />
          </div>
        </div>
      {/if}

      <div class="flex flex-wrap items-end gap-3">
        <div class="space-y-1">
          <Label for={`mat-sym-${index}`}>Material Symmetry</Label>
          <select
            id={`mat-sym-${index}`}
            bind:value={material.materialSymmetry}
            class="flex h-9 rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm"
          >
            {#each materialSymmetries as sym (sym)}
              <option value={sym}>{sym}</option>
            {/each}
          </select>
        </div>
        <Toggle bind:checked={material.planeStress} label="Plane Stress" />
        <Toggle bind:checked={material.planeStrain} label="Plane Strain" />
        {#if material.stiffnessMatrix && material.materialSymmetry === 'Anisotropic' && material.matType?.includes('Correspondence')}
          <Toggle bind:checked={material.stiffnessMatrix.calculateStiffnessMatrix} label="Calculate Stiffness Matrix" />
        {/if}
      </div>

      {#if material.materialSymmetry === 'Transverse Isotropic' || material.materialSymmetry === 'Orthotropic'}
        <div class="flex flex-wrap items-end gap-3">
          <div class="space-y-1">
            <Label for={`mat-ex-${index}`}>Young's Modulus X</Label>
            <Input id={`mat-ex-${index}`} type="number" bind:value={material.youngsModulusX} />
          </div>
          <div class="space-y-1">
            <Label for={`mat-ey-${index}`}>Young's Modulus Y</Label>
            <Input id={`mat-ey-${index}`} type="number" bind:value={material.youngsModulusY} />
          </div>
          {#if material.materialSymmetry === 'Orthotropic'}
            <div class="space-y-1">
              <Label for={`mat-ez-${index}`}>Young's Modulus Z</Label>
              <Input id={`mat-ez-${index}`} type="number" bind:value={material.youngsModulusZ} />
            </div>
          {/if}
          <div class="space-y-1">
            <Label for={`mat-pxy-${index}`}>Poisson's Ratio XY</Label>
            <Input id={`mat-pxy-${index}`} type="number" bind:value={material.poissonsRatioXY} />
          </div>
          {#if material.planeStrain || material.materialSymmetry === 'Orthotropic'}
            <div class="space-y-1">
              <Label for={`mat-pyz-${index}`}>Poisson's Ratio YZ</Label>
              <Input id={`mat-pyz-${index}`} type="number" bind:value={material.poissonsRatioYZ} />
            </div>
          {/if}
          {#if material.materialSymmetry === 'Orthotropic'}
            <div class="space-y-1">
              <Label for={`mat-pxz-${index}`}>Poisson's Ratio XZ</Label>
              <Input id={`mat-pxz-${index}`} type="number" bind:value={material.poissonsRatioXZ} />
            </div>
          {/if}
          <div class="space-y-1">
            <Label for={`mat-gxy-${index}`}>Shear Modulus XY</Label>
            <Input id={`mat-gxy-${index}`} type="number" bind:value={material.shearModulusXY} />
          </div>
          {#if material.materialSymmetry === 'Orthotropic'}
            <div class="space-y-1">
              <Label for={`mat-gyz-${index}`}>Shear Modulus YZ</Label>
              <Input id={`mat-gyz-${index}`} type="number" bind:value={material.shearModulusYZ} />
            </div>
            <div class="space-y-1">
              <Label for={`mat-gxz-${index}`}>Shear Modulus XZ</Label>
              <Input id={`mat-gxz-${index}`} type="number" bind:value={material.shearModulusXZ} />
            </div>
          {/if}
        </div>
      {/if}

      {#if material.stiffnessMatrix && material.materialSymmetry === 'Anisotropic' && material.matType?.includes('Correspondence')}
        <div class="flex flex-wrap gap-6 border-t border-border pt-3">
          {#if material.stiffnessMatrix.calculateStiffnessMatrix}
            <div class="space-y-2">
              {#each Object.keys(material.stiffnessMatrix.engineeringConstants) as key (key)}
                <div class="space-y-1">
                  <Label for={`mat-ec-${index}-${key}`}>{key}</Label>
                  <Input
                    id={`mat-ec-${index}-${key}`}
                    type="number"
                    bind:value={
                      material.stiffnessMatrix.engineeringConstants[
                        key as keyof typeof material.stiffnessMatrix.engineeringConstants
                      ]
                    }
                    oninput={() => calculateStiffnessMatrix(index)}
                  />
                </div>
              {/each}
            </div>
          {/if}
          <div class="space-y-2">
            {#each Object.keys(material.stiffnessMatrix.matrix) as key (key)}
              <div class="space-y-1">
                <Label for={`mat-mx-${index}-${key}`}>{key}</Label>
                <Input
                  id={`mat-mx-${index}-${key}`}
                  type="number"
                  bind:value={material.stiffnessMatrix.matrix[key as keyof typeof material.stiffnessMatrix.matrix]}
                  readonly={material.stiffnessMatrix.calculateStiffnessMatrix}
                />
              </div>
            {/each}
          </div>
        </div>
      {/if}

      <div class="space-y-1">
        <Label for={`mat-stab-${index}`}>Stabilization Type</Label>
        <select
          id={`mat-stab-${index}`}
          bind:value={material.stabilizationType}
          class="flex h-9 rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm"
        >
          {#each stabilizationTypes as type (type)}
            <option value={type}>{type}</option>
          {/each}
        </select>
      </div>

      {#if material.matType?.some((t) => t.includes('Plastic'))}
        <div class="space-y-1">
          <Label for={`mat-yield-${index}`}>Yield Stress</Label>
          <Input id={`mat-yield-${index}`} type="number" bind:value={material.yieldStress} />
        </div>
      {/if}
    </div>
  {/each}

  <Button variant="outline" size="sm" onclick={addMaterial}>
    <Plus class="h-4 w-4" /> Add Material
  </Button>

  <input bind:this={multiSoInput} type="file" multiple accept=".so" class="hidden" onchange={onMultiFilePicked} />
  <input bind:this={propsInput} type="file" multiple accept=".inp" class="hidden" onchange={onPropsFilePicked} />
</div>

// gui/app/src/components/expansions/Material.vue
<template>
    <div>
        <q-list v-for="material, index in materials" :key="material.materialsId" style="padding: 0px">
            <div
                v-bind:style="(material.materialsId % 2 == 0) ? 'background-color: rgba(190, 190, 190, 0.1);' : 'background-color: rgba(255, 255, 255, 0.0);'">
                <h4 class="my-title">Material {{ material.materialsId }}</h4>
                <div class="row my-row">
                    <q-input class="my-input" v-model="material.name" :rules="[rules.required, rules.name]"
                        :label="materialKeys.name" standout dense></q-input>
                    <q-btn flat icon="fas fa-trash-alt" @click="removeMaterial(index)">
                        <q-tooltip>
                            Remove Material
                        </q-tooltip>
                    </q-btn>
                </div>
                <div class="row my-row">
                    <q-select class="my-input" :options="materialModelName" v-model="material.matType"
                        :label="materialKeys.matType" standout dense></q-select>
                </div>
                <div v-if="material.matType.includes('User')">
                    <q-list v-for="prop, subindex in material.properties" :key="prop.materialsPropId" style="padding: 0px">
                        <div class="row my-row">
                            <q-input class="my-input" v-model="prop.value" :rules="[rules.required, rules.float]"
                                :label="prop.name" standout dense></q-input>
                            <q-btn flat icon="fas fa-trash-alt" @click="removeProp(index, subindex)">
                                <q-tooltip>
                                    Remove Property
                                </q-tooltip>
                            </q-btn>
                        </div>
                    </q-list>
                    <div class="row my-row">
                        <q-btn flat icon="fas fa-plus" @click="addProp(index)">
                            <q-tooltip>
                                Add Property
                            </q-tooltip>
                        </q-btn>
                    </div>
                    <div class="row my-row">
                        <q-btn flat icon="fas fa-upload" @click="uploadProps(index)">
                            <q-tooltip>
                                Upload Property
                            </q-tooltip>
                        </q-btn>

                        <q-btn flat icon="fas fa-upload" @click="uploadSo">
                            <q-tooltip>
                                Upload shared Librarie
                            </q-tooltip>
                        </q-btn>
                        <q-input class="my-input" v-model="material.numStateVars" :rules="[rules.required, rules.int]"
                            :label="materialKeys.numStateVars"
                            @update:model-value="bus.emit('addStateVarsToOutput', material.numStateVars)" standout
                            dense></q-input>
                    </div>
                </div>
                <div class="row my-row">
                    <q-input class="my-input" v-model="material.density" :rules="[rules.required, rules.float]"
                        :label="materialKeys.density" standout dense></q-input>
                    <q-input class="my-input" v-model="material.poissonsRatio" :rules="[rules.required, rules.float]"
                        :label="materialKeys.poissonsRatio" clearable standout dense></q-input>
                </div>
                <div class="row my-row">
                    <q-input class="my-input" v-model="material.bulkModulus" :rules="[rules.required, rules.float]"
                        :label="materialKeys.bulkModulus" clearable standout dense></q-input>
                    <q-input class="my-input" v-model="material.shearModulus" :rules="[rules.required, rules.float]"
                        :label="materialKeys.shearModulus" clearable standout dense></q-input>
                    <q-input class="my-input" v-model="material.youngsModulus" :rules="[rules.required, rules.float]"
                        :label="materialKeys.youngsModulus" clearable standout dense></q-input>
                </div>
                <div class="row my-row">
                    <q-input class="my-input" v-model="material.tensionSeparation" :rules="[rules.required, rules.float]"
                        :label="materialKeys.tensionSeparation" clearable standout dense></q-input>
                    <q-toggle class="my-toggle" v-model="material.nonLinear" :label="materialKeys.nonLinear"
                        dense></q-toggle>
                    <q-toggle class="my-toggle" v-model="material.planeStress" :label="materialKeys.planeStress"
                        dense></q-toggle>
                    <q-toggle v-if="material.matType == 'Elastic'" class="my-toggle" v-model="material.computePartialStress"
                        :label="materialKeys.computePartialStress" dense></q-toggle>
                </div>
                <div class="row my-row">
                    <q-select class="my-input" :options="materialSymmetry" v-model="material.materialSymmetry"
                        v-show="['Linear Elastic Correspondence', 'Anisotropic Elastic Bond Associated Correspondence'].includes(material.matType)"
                        :label="materialKeys.materialSymmetry" standout dense></q-select>
                </div>
                <div class="row my-row"
                    v-if="material.materialSymmetry == 'Anisotropic' & ['Linear Elastic Correspondence', 'Anisotropic Elastic Bond Associated Correspondence'].includes(material.matType)">
                    <q-list v-for="params in material.Parameter" :key="params.index" style="padding: 0px">
                        <q-input class="my-input" v-model="params.value" :rules="[rules.required, rules.float]"
                            :label="params.name" standout dense></q-input>
                    </q-list>
                </div>
                <div class="row my-row">
                    <q-select class="my-input" :options="stabilizationType" v-model="material.stabilizationType"
                        :label="materialKeys.stabilizationType" standout dense></q-select>
                </div>
                <div class="row my-row">
                    <q-input class="my-input" v-model="material.thickness" :rules="[rules.required, rules.float]"
                        :label="materialKeys.thickness" standout dense></q-input>
                </div>
                <div class="row my-row">
                    <q-input class="my-input" v-model="material.hourglassCoefficient" :rules="[rules.required, rules.float]"
                        :label="materialKeys.hourglassCoefficient" standout dense></q-input>
                </div>
                <div class="row my-row" v-show="material.matType == 'Elastic Plastic Hypoelastic Correspondence'">
                    <q-input class="my-input" v-model="material.actualHorizon" :rules="[rules.required, rules.float]"
                        :label="materialKeys.actualHorizon" standout dense></q-input>
                </div>
                <div class="row my-row" v-show="material.matType.includes('Plastic')">
                    <q-input class="my-input" v-model="material.yieldStress" :rules="[rules.required, rules.float]"
                        :label="materialKeys.yieldStress" standout dense></q-input>
                </div>
                <q-separator></q-separator>
                <h6 class="my-title">Thermal</h6>
                <q-toggle class="my-toggle" v-model="material.enableThermal" label="Enabled" standout dense></q-toggle>
                <div v-if="material.enableThermal">
                    <div class="row my-row">
                        <q-input class="my-input" v-model="material.specificHeatCapacity"
                            :rules="[rules.required, rules.float]" :label="materialKeys.specificHeatCapacity" standout
                            dense></q-input>
                        <q-input class="my-input" v-model="material.thermalConductivity"
                            :rules="[rules.required, rules.float]" :label="materialKeys.thermalConductivity" standout
                            dense></q-input>
                        <q-input class="my-input" v-model="material.heatTransferCoefficient"
                            :rules="[rules.required, rules.float]" :label="materialKeys.heatTransferCoefficient" standout
                            dense></q-input>
                    </div>
                    <div class="row my-row">
                        <q-toggle class="my-toggle" v-model="material.applyThermalFlow"
                            :label="materialKeys.applyThermalFlow" dense></q-toggle>
                        <q-toggle class="my-toggle" v-model="material.applyThermalStrain"
                            :label="materialKeys.applyThermalStrain" dense></q-toggle>
                        <q-toggle class="my-toggle" v-model="material.applyHeatTransfer"
                            :label="materialKeys.applyHeatTransfer" dense></q-toggle>
                        <q-toggle class="my-toggle" v-model="material.thermalBondBased"
                            :label="materialKeys.thermalBondBased" dense></q-toggle>
                    </div>
                    <div class="row my-row">
                        <q-input class="my-input" v-model="material.thermalExpansionCoefficient"
                            :rules="[rules.required, rules.float]" :label="materialKeys.thermalExpansionCoefficient"
                            clearable standout dense></q-input>
                        <q-input class="my-input" v-model="material.environmentalTemperature"
                            :rules="[rules.required, rules.float]" :label="materialKeys.environmentalTemperature" clearable
                            standout dense></q-input>
                    </div>
                    <q-separator></q-separator>
                    <h6 class="my-title">Additive</h6>
                    <div class="row my-row">
                        <q-input class="my-input" v-model="material.printBedTemperature"
                            :rules="[rules.required, rules.float]" :label="materialKeys.printBedTemperature" clearable
                            standout dense></q-input>
                        <q-input class="my-input" v-model="material.printBedThermalConductivity"
                            :rules="[rules.required, rules.float]" :label="materialKeys.printBedThermalConductivity"
                            clearable standout dense></q-input>
                    </div>
                    <div class="row my-row">
                        <q-input class="my-input" v-model="material.volumeFactor" :rules="[rules.required, rules.float]"
                            :label="materialKeys.volumeFactor" clearable standout dense></q-input>
                        <q-input class="my-input" v-model="material.volumeLimit" :rules="[rules.required, rules.float]"
                            :label="materialKeys.volumeLimit" clearable standout dense></q-input>
                        <q-input class="my-input" v-model="material.surfaceCorrection"
                            :rules="[rules.required, rules.float]" :label="materialKeys.surfaceCorrection" clearable
                            standout dense></q-input>
                    </div>
                </div>
            </div>
        </q-list>
        <q-btn flat icon="fas fa-plus" @click="addMaterial">
            <q-tooltip>
                Add Material
            </q-tooltip>
        </q-btn>
        <input type="file" style="display: none" ref="multiSoInput" multiple accept=".so" @change="onMultiFilePicked" />
        <input type="file" style="display: none" ref="propsInput" multiple accept=".inp" @change="onPropsFilePicked" />
    </div>
</template>
  
<script>
import { computed, defineComponent } from 'vue'
import { useModelStore } from 'stores/model-store';
import { useViewStore } from 'stores/view-store';
import { inject } from 'vue'
import rules from "assets/rules.js";
import { deepCopy } from '../../utils/functions.js'

export default defineComponent({
    name: 'MaterialSettings',
    setup() {
        const store = useModelStore();
        const viewStore = useViewStore();
        const materials = computed(() => store.modelData.materials)
        const modelData = computed(() => store.modelData)
        const bus = inject('bus')
        return {
            viewStore,
            materials,
            modelData,
            rules,
            bus
        }
    },
    created() {
    },
    data() {
        return {
            selectedMaterial: 0,
            materialModelName: [
                "Diffusion",
                "Elastic",
                "Elastic Bond Based",
                "Elastic Bond Associated Correspondence",
                "Anisotropic Elastic Bond Associated Correspondence",
                "Elastic Correspondence",
                "Elastic Correspondence Partial Stress",
                "Elastic Hypoelastic Correspondence",
                "Elastic Partial Volume",
                "Elastic Plastic",
                "Elastic Plastic Correspondence",
                "Elastic Plastic Hardening",
                "Elastic Plastic Hypoelastic Correspondence",
                "Isotropic Hardening Correspondence",
                "Isotropic Hardening Hypoelastic Correspondence",
                "LCM",
                "Linear Elastic Correspondence",
                "Linear LPS Partial Volume",
                "Multiphysics Elastic",
                "Pals",
                "Pressure Dependent Elastic Plastic",
                "User Correspondence",
                "Viscoelastic",
                "Viscoplastic Needleman Correspondence",
                "Vector Poisson",
            ],
            materialSymmetry: ["Isotropic", "Anisotropic"],
            stabilizationType: [
                "Bond Based",
                "State Based",
                "Sub Horizon",
                "Global Stiffness",
            ],
            micofam: {
                RVE: {
                    rve_fvc: 30,
                    rve_radius: 6.6,
                    rve_lgth: 50,
                    rve_dpth: 1,
                },
                Mesh: {
                    mesh_fib: 35,
                    mesh_lgth: 35,
                    mesh_dpth: 1,
                    mesh_aa: "on",
                },
            },
            materialKeys: {
                name: "name",
                matType: "Material Model",
                density: "Density",
                bulkModulus: "Bulk Modulus",
                shearModulus: "Shear Modulus",
                youngsModulus: "Young's Modulus",
                poissonsRatio: "Poisson's Ratio",
                tensionSeparation: "Tension Separation",
                nonLinear: "Non linear",
                planeStress: "Plane Stress",
                materialSymmetry: "Material Symmetry",
                stabilizationType: "Stabilization Type",
                thickness: "Thickness",
                hourglassCoefficient: "Hourglass Coefficient",
                actualHorizon: "Actual Horizon",
                yieldStress: "Yield Stress",
                Parameter_0: "C11",
                Parameter_1: "C12",
                Parameter_2: "C13",
                Parameter_3: "C14",
                Parameter_4: "C15",
                Parameter_5: "C16",
                Parameter_6: "C22",
                Parameter_7: "C23",
                Parameter_8: "C24",
                Parameter_9: "C25",
                Parameter_10: "C26",
                Parameter_11: "C33",
                Parameter_12: "C34",
                Parameter_13: "C35",
                Parameter_14: "C36",
                Parameter_15: "C44",
                Parameter_16: "C45",
                Parameter_17: "C46",
                Parameter_18: "C55",
                Parameter_19: "C56",
                Parameter_20: "C66",
                computePartialStress: "Compute Partial Stress",
                useCollocationNodes: "Use Collocation Nodes",
                numStateVars: "Number of State Vars",
                // Thermal
                specificHeatCapacity: "Specific Heat Capacity",
                thermalConductivity: "Thermal Conductivity",
                heatTransferCoefficient: "Heat Transfer Coefficient",
                applyThermalFlow: "Apply Thermal Flow",
                applyThermalStrain: "Apply Thermal Strain",
                applyHeatTransfer: "Apply Heat Transfer",
                thermalBondBased: "Thermal Bond Based",
                thermalExpansionCoefficient: "Thermal Expansion Coefficient",
                environmentalTemperature: "Environmental Temperature",
                // 3dPrint
                printBedTemperature: "Print Bed Temperature",
                printBedThermalConductivity: "Thermal Conductivity Print Bed",
                volumeFactor: "Volume Factor",
                volumeLimit: "Volume Limit",
                surfaceCorrection: "Surface Correction",
            },
        };
    },
    methods: {
        onMultiFilePicked(event) {
            const files = event.target.files;
            const filetype = files[0].type;
            if (files.length <= 0) {
                return false;
            }

            this.viewStore.modelLoading = true;
            this.uploadfiles(files);

            this.viewStore.modelLoading = false;
        },
        async uploadfiles(files) {
            const formData = new FormData();
            for (var i = 0; i < files.length; i++) {
                formData.append("files", files[i]);
            }
            let params = {
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName
            }

            this.$api.post('/upload/files', formData, { params })
                .then((response) => {
                    this.$q.notify({
                        message: response.data.message
                    })
                })
                .catch((error) => {
                    this.$q.notify({
                        type: 'negative',
                        message: error.response.data.detail
                    })
                })
        },
        uploadSo() {
            this.$refs.multiSoInput.click();
        },
        uploadProps(id) {
            this.$refs.propsInput.click();
            this.selectedMaterial = id;
        },
        onPropsFilePicked(event) {
            const files = event.target.files;

            const fr = new FileReader();
            fr.onload = (e) => {
                const input_string = e.target.result;

                let filtered_string = input_string.match(/\*User([\D\S]*?)\*/gi);
                let propsArray = filtered_string[0].split(/[\n,]/gi);
                propsArray = propsArray.slice(0, propsArray.length - 1);

                if (propsArray[1].match(/\d+/) == propsArray.length - 2) {
                    this.materials[0].properties = [];
                    for (var i = 2; i < propsArray.length; i++) {
                        this.addProp(0);
                        this.materials[0].properties[i - 2].value = propsArray[i].trim();
                    }
                } else {
                    console.log("Length of Propsarray unexpected");
                }
            };
            fr.readAsText(files.item(0));

            // console.log(input_string)
            // let filtered_string = input_string.search(/\*User([\D\S]*?)\*/i);
        },
        addMaterial() {
            const len = this.materials.length;
            let newItem = deepCopy(this.materials[len - 1])
            newItem.materialsId = len + 1
            newItem.name = "Material" + (len + 1)
            this.materials.push(newItem);
        },
        removeMaterial(index) {
            this.materials.splice(index, 1);
        },
        addProp(index) {
            const len = this.materials[index].properties.length;
            let newItem = {}
            if (len != 0) {
                newItem = deepCopy(this.materials[index].properties[len - 1])
            }
            newItem.materialsPropId = len + 1
            newItem.name = "Prop_" + (len + 1)

            this.materials[index].properties.push(newItem)
        },
        removeProp(index, subindex) {
            this.materials[index].properties.splice(subindex, 1);
        },
    }
})
</script>
