// src/lib/components/TextComp.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  import { Tabs } from 'bits-ui';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { bus } from '$lib/utils/bus';
  import TextView from '$lib/components/views/TextView.svelte';
  import LogView from '$lib/components/views/LogView.svelte';

  function updateTextView() {
    if (viewStore.textId === 'input') {
      bus.emit('viewInputFile' as never);
    } else if (viewStore.textId === 'log') {
      bus.emit('enableWebsocket' as never);
    }
  }
  onMount(() => {
    bus.on('updateTextView' as never, updateTextView);
    return () => bus.off('updateTextView' as never, updateTextView);
  });

  const tabClass =
    'flex-1 px-3 py-2 text-center text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground';
</script>

<div class="flex h-full flex-col overflow-hidden">
  <Tabs.Root bind:value={viewStore.textId} class="flex h-full flex-col">
    <Tabs.List class="border-border bg-muted/40 flex border-b">
      <Tabs.Trigger value="input" class={tabClass}>Input</Tabs.Trigger>
      <Tabs.Trigger value="log" class={tabClass}>Log</Tabs.Trigger>
    </Tabs.List>

    <div class="flex-1 overflow-auto">
      <Tabs.Content value="input" class="h-full"><TextView /></Tabs.Content>
      <Tabs.Content value="log" class="h-full"><LogView /></Tabs.Content>
    </div>
  </Tabs.Root>
</div>

// frontend/app/src/components/TextComp.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div :style="{ 'height': textHeight }">
    <q-tabs v-model="store.textId" dense class="text-grey" active-color="primary" indicator-color="primary"
      align="justify" @update:model-value="updateTextView">
      <q-tab name="input" label="Input"></q-tab>
      <q-tab name="log" label="Log"></q-tab>
    </q-tabs>

    <q-separator></q-separator>

    <q-tab-panels v-model="store.textId" animated style="height:100%">
      <q-tab-panel name="input">
        <TextView></TextView>
      </q-tab-panel>
      <q-tab-panel name="log">
        <LogView></LogView>
      </q-tab-panel>
    </q-tab-panels>

    <q-inner-loading :showing="store.textLoading">
      <q-spinner-gears size="50px" color="primary"></q-spinner-gears>
    </q-inner-loading>
  </div>
</template>

<script>
import { defineComponent, inject } from 'vue'
import TextView from 'components/views/TextView.vue'
import LogView from 'components/views/LogView.vue'
import { useViewStore } from 'stores/view-store';

export default defineComponent({
  name: "TextComp",
  components: {
    TextView,
    LogView
  },
  data() {
    return {
      textHeight: "400px",
    };
  },
  setup() {
    const store = useViewStore();
    const bus = inject('bus');
    return {
      store,
      bus
    }
  },
  created() {
    this.bus.on('resizeTextPanel', (height) => {
      this.textHeight = height - 113 + 'px'
    })
  },
  methods: {
    updateTextView() {
      if (this.store.textId === 'input') {
        this.bus.emit('viewInputFile')
      }
      else if (this.store.textId === 'log') {
        this.bus.emit('enableWebsocket')
      }
    }
  }
})
</script>
