// src/lib/components/actions/TextActions.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Save } from 'lucide-svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { config } from '$lib/config';
  import { getStatus, viewInputFile as viewInputFileApi, writeInputFile as writeInputFileApi, OpenAPI } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';

  const modelData = $derived(modelStore.modelData);

  let connection: WebSocket | null = null;
  let debug = $state(false);
  let lastLine = '';

  function viewInputFile() {
    viewInputFileApi({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName
    })
      .then((response) => {
        notify.positive('Inputfile loaded');
        viewStore.textOutput = response as unknown as string;
        viewStore.textId = 'input';
      })
      .catch((error) => notify.apiError(error));
  }

  function writeInputFile() {
    writeInputFileApi({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName,
      inputString: viewStore.textOutput
    })
      .then(() => notify.positive('Inputfile saved'))
      .catch((error) => notify.apiError(error));
  }

  function _getStatus() {
    getStatus({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName,
      meshfile: modelData.model.meshFile!,
      cluster: modelData.job.cluster,
      sbatch: modelData.job.sbatch
    })
      .then((response) => {
        notify.positive('Status updated');
        defaultStore.status = response;
      })
      .catch((error) => notify.apiError(error));
  }

  function enableWebsocket() {
    if (connection) {
      connection.close();
      connection = null;
    }
    const params = {
      model_name: modelStore.selectedModel.file,
      model_folder_name: modelData.model.modelFolderName,
      cluster: modelData.job.cluster,
      token: OpenAPI.TOKEN,
      user_name: defaultStore.username,
      debug
    };
    const queryString = Object.entries(params)
      .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`)
      .join('&');

    let socketPath = `ws://${window.location.host}/ws?${queryString}`;
    if (window.location.protocol === 'https:') {
      socketPath = `wss://${window.location.host}/ws?${queryString}`;
    }
    if (config.dev) {
      socketPath = `ws://localhost:8000/ws?${queryString}`;
    }

    connection = new WebSocket(socketPath);
    connection.onmessage = (event) => {
      viewStore.logOutput = event.data;
      const lines = viewStore.logOutput.split('\n');
      const currentLastLine = lines[lines.length - 2];
      if (currentLastLine !== lastLine) {
        if (currentLastLine?.includes('[Info] Run ')) {
          viewStore.viewId = 'results';
        }
        if (currentLastLine?.includes('[Info] PeriLab finished') && connection) {
          connection.close();
          connection = null;
          _getStatus();
          bus.emit('getJobs' as never);
          if (defaultStore.status.submitted) notify.positive('PeriLab finished');
        }
        if (currentLastLine?.includes('[Error]') && connection) {
          connection.close();
          connection = null;
          _getStatus();
          bus.emit('getJobs' as never);
          if (defaultStore.status.submitted) notify.negative(currentLastLine);
        }
        lastLine = currentLastLine ?? '';
      }
    };
    connection.onerror = (event) => {
      console.error(event);
      notify.negative('Websocket error');
    };
    viewStore.textLoading = false;
  }

  onMount(() => {
    _getStatus();
    enableWebsocket();

    bus.on('enableWebsocket' as never, enableWebsocket);
    bus.on('viewInputFile' as never, viewInputFile);
    bus.on('getStatus' as never, _getStatus);

    return () => {
      bus.off('enableWebsocket' as never, enableWebsocket);
      bus.off('viewInputFile' as never, viewInputFile);
      bus.off('getStatus' as never, _getStatus);
      connection?.close();
    };
  });

  onDestroy(() => connection?.close());
</script>

<div class="flex items-center gap-1 border-b border-border bg-muted/30 px-2 py-1">
  <Button
    variant="ghost"
    size="icon"
    onclick={writeInputFile}
    disabled={!defaultStore.status.created || viewStore.textId !== 'input' || defaultStore.trial}
    title={defaultStore.trial ? 'Disabled in trial version' : 'Save Inputfile'}
  >
    <Save class="h-4 w-4" />
  </Button>
  <div class="flex-1"></div>
  <Toggle bind:checked={debug} label="Debug" />
</div>

// frontend/app/src/components/actions/TextActions.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div class="row">
    <!-- <q-btn flat icon="fas fa-sync-alt" @click="viewInputFile(false)" :disable="!store.status.created">
      <q-tooltip>
        Reload Inputfile
      </q-tooltip>
    </q-btn> -->
    <q-btn flat icon="fas fa-save" @click="writeInputFile"
      :disable="!store.status.created || viewStore.textId != 'input'">
      <q-tooltip>
        Save Inputfile
      </q-tooltip>
    </q-btn>

    <q-space></q-space>
    <q-toggle class="my-toggle" v-model="debug" label="Debug" standout dense></q-toggle>
  </div>
</template>

<script>
import { computed, defineComponent } from 'vue'
import { useDefaultStore } from 'src/stores/default-store';
import { useModelStore } from 'src/stores/model-store';
import { useViewStore } from 'src/stores/view-store';
import { inject } from 'vue'
import { useQuasar } from 'quasar'
import { getStatus, viewInputFile, writeInputFile, OpenAPI } from 'src/client';
import rules from 'assets/rules.js';

const sleep = (ms) => new Promise((res) => setTimeout(res, ms));

export default defineComponent({
  name: 'TextActions',
  setup() {
    const $q = useQuasar()
    const store = useDefaultStore();
    const modelStore = useModelStore();
    const viewStore = useViewStore();
    const modelData = computed(() => modelStore.modelData)
    const bus = inject('bus')

    return {
      store,
      viewStore,
      modelStore,
      modelData,
      rules,
      bus,
    }
  },
  created() {
    this.bus.on('enableWebsocket', (loadFile) => {
      this.enableWebsocket(loadFile)
    })
    this.bus.on('viewInputFile', (loadFile) => {
      this.viewInputFile(loadFile)
    })
    this.bus.on('getStatus', () => {
      this._getStatus()
    })
  },
  beforeUnmount() {
    this.bus.off('enableWebsocket')
    this.bus.off('viewInputFile')
    this.bus.off('getStatus')
  },
  data() {
    return {
      connection: null,
      debug: false,
      lastLine: '',
    };
  },
  methods: {
    async viewInputFile(loadFile) {
      console.log('viewInputFile')

      viewInputFile({ modelName: this.modelStore.selectedModel.file, modelFolderName: this.modelData.model.modelFolderName, ownMesh: this.modelData.model.ownMesh })
        .then((response) => {
          this.$q.notify({
            message: response.message
          })
          this.viewStore.textOutput = response.data;
          this.viewStore.textId = 'input'
          if (loadFile) {
            this.loadYamlString(response.data);
          }
        })
        .catch((error) => {
          this.$q.notify({
            color: 'negative',
            position: 'bottom-right',
            message: error,
            icon: 'report_problem'
          })
        })
    },
    writeInputFile() {

      writeInputFile({ modelName: this.modelStore.selectedModel.file, modelFolderName: this.modelData.model.modelFolderName, inputString: this.viewStore.textOutput })
        .then((response) => {
          this.$q.notify({
            message: response.message
          })
        })
        .catch((error) => {
          this.$q.notify({
            type: 'negative',
            message: error.response.detail
          })
        })
    },
    async _getStatus() {
      console.log('getStatus');

      const response = await getStatus({
        modelName: this.modelStore.selectedModel.file,
        modelFolderName: this.modelData.model.modelFolderName,
        meshfile: this.modelData.model.meshFile,
        ownModel: this.modelData.model.ownModel,
        cluster: this.modelData.job.cluster,
        sbatch: this.modelData.job.sbatch
      });
      console.log(response)
      this.$q.notify({
        message: response.message
      })
      this.store.status = response.data
      // if (this.store.status.submitted)
      // {
      //   this.enableWebsocket()
      // }
      // this.$api.get('/jobs/getStatus', { params })
      //   .then((response) => {
      //     this.$q.notify({
      //       message: response.data.message
      //     })
      //     this.store.status = response.data.data
      //     console.log(this.store.status)
      //   })
      //   .catch((error) => {
      //     this.$q.notify({
      //       type: 'negative',
      //       message: error.response.data.detail
      //     })
      //   })
    },
    async enableWebsocket() {
      console.log('enableWebsocket')
      // Check if there is an existing connection
      if (this.connection) {
        // Close the existing connection
        console.log('close existing connection')
        await this.connection.close();
        this.connection = null; // Reset the connection variable
      }
      const params = {
        model_name: this.modelStore.selectedModel.file,
        model_folder_name: this.modelData.model.modelFolderName,
        cluster: this.modelData.job.cluster,
        token: OpenAPI.TOKEN,
        user_name: this.store.username,
        debug: this.debug
      };

      const queryString = Object.entries(params)
        .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
        .join('&');

      // TODO: socket path wont work on build
      let socket_path = `ws://${window.location.host}/ws?${queryString}`;
      if (window.location.protocol === 'https:') {
        socket_path = `wss://${window.location.host}/ws?${queryString}`;
      }
      if (process.env.DEV) {
        socket_path = `ws://localhost:8000/ws?${queryString}`;
      }
      this.connection = new WebSocket(socket_path);
      this.connection.onmessage = (event) => {
        this.viewStore.logOutput = event.data;
        // get last line and compare
        const lines = this.viewStore.logOutput.split('\n');
        const lastLine = lines[lines.length - 2];
        if (lastLine != this.lastLine) {
          if (lastLine && lastLine.includes('[Info] Run ')) {
            this.viewStore.viewId = 'results';
          }
          if (lastLine && lastLine.includes('[Info] PeriLab finished')) {
            this.connection.close();
            this.connection = null; // Reset the connection variable
            this._getStatus();
            this.bus.emit('getJobs')
            if (this.store.status.submitted) {
              this.$q.notify({
                message: 'PeriLab finished'
              })
            }
          }
          if (lastLine && lastLine.includes('[Error]')) {
            this.connection.close();
            this.connection = null; // Reset the connection variable
            this._getStatus();
            this.bus.emit('getJobs')
            if (this.store.status.submitted) {
              this.$q.notify({
                color: 'negative',
                message: lastLine
              })
            }
          }
          this.lastLine = lastLine
        }
      }
      this.connection.onerror = (event) => {
        console.log(event)
        this.$q.notify({
          type: 'negative',
          message: event
        })
      }
      this.viewStore.textLoading = false;
    },
  },
  mounted() {
    this._getStatus();
    this.enableWebsocket();
  },
})
</script>
