// src/lib/components/views/ResultsView.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Accordion } from 'bits-ui';
  import {
    RotateCw,
    Maximize,
    SkipBack,
    Rewind,
    Pause,
    Play,
    FastForward,
    SkipForward,
    Settings,
    LoaderCircle
  } from 'lucide-svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { notify } from '$lib/utils/notify';
  import { getPointDataResults } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';
  import Select from '$lib/components/ui/Select.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';
  import AccordionItem from '$lib/components/ui/AccordionItem.svelte';
  import VerticalColoredLegend from '$lib/components/views/VerticalColoredLegend.svelte';
  import ResultsScene from '$lib/components/views/ResultsScene.svelte';

  const modelData = $derived(modelStore.modelData);

  const AXIS_OPTIONS = ['X', 'Y', 'Z', 'Magnitude'];
  const FILTER_OPTIONS = ['Active', 'Temperature', 'Displacements', 'Damage'];

  const modelParams = $state({
    variable: 'Displacements',
    axis: 'Magnitude',
    displFactor: 1,
    step: 1,
    numberOfSteps: 100,
    filter: '',
    colorBarMin: null as number | null,
    colorBarMax: null as number | null
  });
  let variableOptions = $state<string[]>(['Displacements', 'Damage', 'Forces', 'Temperature']);

  let resolution = $state(6);
  let radius = $state(0.2);
  let dxValue = $state(0.2);
  let multiplier = $state(100);
  let pointString = $state<number[]>([1, 0, 0]);
  let blockIdString = $state<number[]>([0]);
  let modelLoading = $state(false);
  let maxValue = $state(100);
  let minValue = $state(0);
  let time = $state(0);
  let playing = $state(false);
  let expansionValue = $state('');

  let timer: ReturnType<typeof setInterval> | undefined;
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;

  let scene: ResultsScene | undefined = $state();

  const sphereRadius = $derived((radius * multiplier) / 100);

  async function viewPointData(loading = true) {
    modelLoading = loading;
    await getPointDataAndUpdateDx();
    radius = parseFloat(dxValue.toFixed(3));
    updatePoints();
    modelLoading = false;
  }

  function updatePoints() {
    // Kept as its own step (matching the old component) even though it's
    // currently a no-op beyond the loading flag - radius/resolution changes
    // are already applied reactively via props passed into ResultsScene.
    modelLoading = true;
    modelLoading = false;
  }

  async function getPointDataAndUpdateDx() {
    await getPointDataResults({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName!,
      cluster: modelData.job.cluster,
      output: modelData.outputs[0]!.name,
      tasks: modelData.job.tasks,
      axis: modelParams.axis,
      step: modelParams.step,
      displFactor: modelParams.displFactor,
      variable: modelParams.variable,
      filter: modelParams.filter,
      colorBarMin: modelParams.colorBarMin,
      colorBarMax: modelParams.colorBarMax
    })
      .then((response) => {
        pointString = response.nodes;
        blockIdString = response.value;
        dxValue = Math.hypot(pointString[3]! - pointString[0]!, pointString[4]! - pointString[1]!, pointString[5]! - pointString[2]!);
        maxValue = response.max_value;
        minValue = response.min_value;
        variableOptions = response.variables;
        modelParams.numberOfSteps = response.number_of_steps;
        time = response.time;
      })
      .catch((error) => notify.apiError(error));
  }

  function debouncedReload() {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => viewPointData(true), 500);
  }

  function play() {
    playing = true;
    timer = setInterval(forward, 200);
  }

  function pause() {
    playing = false;
    clearInterval(timer);
  }

  async function backward() {
    if (modelParams.step > 1) {
      modelParams.step -= 1;
      await viewPointData(false);
    }
  }

  async function fastBackward() {
    modelParams.step = 1;
    await viewPointData(false);
  }

  async function forward() {
    if (modelParams.step < modelParams.numberOfSteps) {
      modelParams.step += 1;
      await viewPointData(false);
    } else {
      pause();
    }
  }

  async function fastForward() {
    modelParams.step = modelParams.numberOfSteps;
    await viewPointData(false);
  }

  onMount(() => {
    // Just the data load - ResultsScene/Canvas handles its own sizing
    // (including the tab-mounted-but-hidden case), so no ResizeObserver
    // bookkeeping is needed here any more.
    viewPointData(true);
  });

  onDestroy(() => {
    clearInterval(timer);
    clearTimeout(debounceTimer);
  });
</script>

<div class="relative flex h-full flex-col overflow-hidden">
  <div class="flex flex-col gap-1 border-b border-border bg-muted/30 px-2 py-1.5">
    <div class="flex flex-wrap items-center gap-1">
      <Button variant="ghost" size="icon" onclick={() => viewPointData(true)} title="Reload Model">
        <RotateCw class="h-4 w-4" />
      </Button>
      <Button variant="ghost" size="icon" onclick={() => scene?.resetCamera()} title="Reset Camera">
        <Maximize class="h-4 w-4" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        disabled={modelParams.step === 1}
        onclick={fastBackward}
        title="Fast Backward"
      >
        <SkipBack class="h-4 w-4" />
      </Button>
      <Button variant="ghost" size="icon" onclick={backward} title="Backward">
        <Rewind class="h-4 w-4" />
      </Button>
      <Button variant="ghost" size="icon" disabled={!playing} onclick={pause} title="Pause">
        <Pause class="h-4 w-4" />
      </Button>
      <Button variant="ghost" size="icon" disabled={playing} onclick={play} title="Play">
        <Play class="h-4 w-4" />
      </Button>
      <Button variant="ghost" size="icon" onclick={forward} title="Forward">
        <FastForward class="h-4 w-4" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        disabled={modelParams.step === modelParams.numberOfSteps}
        onclick={fastForward}
        title="Fast Forward"
      >
        <SkipForward class="h-4 w-4" />
      </Button>

      <div class="ml-2 flex min-w-[160px] items-center gap-2 px-2">
        <label for="results-step" class="whitespace-nowrap text-xs text-muted-foreground">
          Time Step: {modelParams.step}
        </label>
        <input
          id="results-step"
          type="range"
          min="0"
          max={modelParams.numberOfSteps}
          step="1"
          bind:value={modelParams.step}
          onchange={() => viewPointData(true)}
          class="flex-1 accent-primary"
        />
        <span class="w-10 shrink-0 whitespace-nowrap text-right text-xs text-muted-foreground">{time.toExponential(2)}</span>
      </div>
      <div class="flex min-w-[160px] items-center gap-2">
        <label for="results-node-size" class="whitespace-nowrap text-xs text-muted-foreground">
          Node Size: {multiplier}%
        </label>
        <input
          id="results-node-size"
          type="range"
          min="1"
          max="200"
          step="1"
          bind:value={multiplier}
          onchange={updatePoints}
          class="w-24 accent-primary"
        />
      </div>

      <div class="flex min-w-[160px] items-center gap-2">
        <label for="results-resolution" class="whitespace-nowrap text-xs text-muted-foreground">
          Resolution: {resolution}
        </label>
        <input
          id="results-resolution"
          type="range"
          min="3"
          max="20"
          step="1"
          bind:value={resolution}
          class="w-24 accent-primary"
        />
      </div>
    </div>
  </div>

  <div class="relative min-h-0 flex-1">
    <ResultsScene
      bind:this={scene}
      points={pointString}
      values={blockIdString}
      radius={sphereRadius}
      {resolution}
      {minValue}
      {maxValue}
    />

    <!-- Variable/axis/filter controls, floating over the 3D view like the
         old absolutely-positioned `.variables` panel. Positioned relative to
         this viewport wrapper (not the whole component), so it always sits
         at the top-left of the 3D view regardless of how many rows the
         toolbar above ends up needing. -->
    <div class="absolute left-2 top-2 flex w-56 flex-col gap-2 rounded-md border border-border bg-background/90 p-2 shadow-sm backdrop-blur-sm">
      <div>
        <Label for="results-variable">Variable</Label>
        <Select id="results-variable" bind:value={modelParams.variable} onchange={() => viewPointData(true)}>
          {#each variableOptions as option (option)}
            <option value={option}>{option}</option>
          {/each}
        </Select>
      </div>
      <div>
        <Label for="results-axis">Axis</Label>
        <Select id="results-axis" bind:value={modelParams.axis} onchange={() => viewPointData(true)}>
          {#each AXIS_OPTIONS as option (option)}
            <option value={option}>{option}</option>
          {/each}
        </Select>
      </div>
      <div>
        <Label for="results-displ-factor">Displ. Magnitude</Label>
        <Input
          id="results-displ-factor"
          type="number"
          bind:value={modelParams.displFactor}
          oninput={debouncedReload}
        />
      </div>

      <Accordion.Root type="single" bind:value={expansionValue}>
        <AccordionItem value="options" label="Options" icon={Settings}>
          <div class="flex flex-col gap-2">
            <div>
              <Label for="results-filter">Filter</Label>
              <Select id="results-filter" bind:value={modelParams.filter} onchange={() => viewPointData(true)}>
                <option value="">-</option>
                {#each FILTER_OPTIONS as option (option)}
                  <option value={option}>{option}</option>
                {/each}
              </Select>
            </div>
            <div>
              <Label for="results-min">Min.</Label>
              <Input id="results-min" type="number" bind:value={modelParams.colorBarMin} oninput={debouncedReload} />
            </div>
            <div>
              <Label for="results-max">Max.</Label>
              <Input id="results-max" type="number" bind:value={modelParams.colorBarMax} oninput={debouncedReload} />
            </div>
          </div>
        </AccordionItem>
      </Accordion.Root>
    </div>

    <div class="absolute bottom-2 left-2">
      <VerticalColoredLegend min={minValue} max={maxValue} />
    </div>

    {#if modelLoading}
      <div class="absolute inset-0 flex items-center justify-center bg-background/40">
        <LoaderCircle class="h-10 w-10 animate-spin text-primary" />
      </div>
    {/if}
  </div>
</div>

// frontend/app/src/components/views/ResultsView.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div style="height: 100%; width: 100%; overflow: hidden">
    <div style="height:100%;">
      <div class="row" :class="$q.dark.isActive ? 'bg-grey-9' : 'bg-grey-3'">
        <q-btn padding="none" flat dense icon="fas fa-sync-alt" @click="viewPointData(true)">
          <q-tooltip>
            Reload Model
          </q-tooltip>
        </q-btn>
        <!-- @vue-ignore -->
        <q-btn padding="none" flat dense icon="fas fa-expand" @click="$refs.view.resetCamera()">
          <q-tooltip>
            Reset Camera
          </q-tooltip>
        </q-btn>
        <q-btn :disabled="modelParams.step == 1" padding="none" flat dense icon="fas fa-fast-backward"
          @click="fastBackward()">
          <q-tooltip>
            Fast Backward
          </q-tooltip>
        </q-btn>
        <q-btn padding="none" flat dense icon="fas fa-backward" @click="backward()">
          <q-tooltip>
            Backward
          </q-tooltip>
        </q-btn>
        <q-btn :disabled="!playing" padding="none" flat dense icon="fas fa-pause" @click="pause()">
          <q-tooltip>
            Pause
          </q-tooltip>
        </q-btn>
        <q-btn :disabled="playing" padding="none" flat dense icon="fas fa-play" @click="play()">
          <q-tooltip>
            Play
          </q-tooltip>
        </q-btn>
        <q-btn padding="none" flat dense icon="fas fa-forward" @click="forward()">
          <q-tooltip>
            Forward
          </q-tooltip>
        </q-btn>
        <q-btn :disabled="modelParams.step == modelParams.numberOfSteps" padding="none" flat dense
          icon="fas fa-fast-forward" @click="fastForward()">
          <q-tooltip>
            Fast Forward
          </q-tooltip>
        </q-btn>
        <q-item style="padding-right: 5px">
          <q-item-section style="width: 10px; margin-right:15px" side>
            <q-icon color=" #cfcfcf" name="fas fa-clock" />
          </q-item-section>
          <q-item-section v-if="modelParams.numberOfSteps > 0">
            <q-slider style="width: 100px" v-model="modelParams.step" :min="0" :max="modelParams.numberOfSteps"
              :step="1" label :label-value="'Time Step: ' + modelParams.step" switch-label-side color="secondary"
              @change="viewPointData(true)"></q-slider>
          </q-item-section>
          <q-item-section side>
            {{ time }}
          </q-item-section>
        </q-item>
        <!-- <div class="settings-column">
          <q-select class="textfield-col" :options="variableOptions" v-model="modelParams.variable" label="Variable"
            outlined dense @update:model-value="viewPointData"></q-select>
        </div>
        <div class="settings-column">
          <q-select class="textfield-col" :options="axisOptions" v-model="modelParams.axis" label="Axis" outlined dense
            @update:model-value="viewPointData"></q-select>
        </div>
        <div class="settings-column">
          <q-input v-model.number="modelParams.displFactor" type="number" label="Displ. Magnitude" outlined dense
            debounce:500 @update:model-value="viewPointData"></q-input>
        </div> -->
        <q-item style="padding-right: 5px">
          <q-item-section style="width: 10px; margin-right:15px" side>
            <q-icon color="#cfcfcf" name="fas fa-up-right-and-down-left-from-center" />
          </q-item-section>
          <q-item-section>
            <q-slider style="width: 80px" v-model="multiplier" :min="1" :max="200" :step="1" label
              :label-value="'Node Size: ' + multiplier + ' %'" switch-label-side @change="updatePoints"
              color="secondary"></q-slider>
          </q-item-section>
        </q-item>
        <q-item style="padding-right: 5px">
          <q-item-section style="width: 10px; margin-right:15px" side>
            <q-icon color="#cfcfcf" name="fas fa-eye" />
          </q-item-section>
          <q-item-section>
            <q-slider style="width: 80px" v-model="resolution" :min="3" :max="20" :step="1" label
              :label-value="'Resolution: ' + resolution" switch-label-side color="secondary"></q-slider>
          </q-item-section>
        </q-item>
        <!-- <div class="settings-column">
      <q-toggle v-model="sphere" :label="sphere" false-value="Cube" true-value="Sphere"
        @update:model-value="$refs.view.resetCamera();" />
    </div> -->
      </div>
      <div class="viewport">
        <vtk-view ref="view" :background="[45 / 255, 45 / 255, 45 / 255]" :key="viewKey">
          <vtk-glyph-representation>
            <vtk-polydata :points="pointString">
              <vtk-cell-data>
                <vtk-data-array registration="setScalars" name="scalars" :values="blockIdString"
                  :state="{ rangeMax: 12 }" />
              </vtk-cell-data>
            </vtk-polydata>
            <vtk-algorithm v-if='sphere == "Sphere"' vtkClass="vtkSphereSource"
              :state="{ phiResolution: resolution, thetaResolution: resolution, radius: radius * multiplier / 100 }"
              :port="1" />
            <!-- <vtk-algorithm v-if='sphere == "Cube"' vtkClass="vtkCubeSource"
            :state="{ XLength: radius * multiplier / 100, YLength: radius * multiplier / 100, ZLength: radius * multiplier / 100 }"
            :port="1" /> -->
          </vtk-glyph-representation>
        </vtk-view>
      </div>
    </div>
    <div class="variables" :class="$q.dark.isActive ? 'bg-grey-9' : 'bg-grey-3'">
      <q-select class="variable" :options="variableOptions" v-model="modelParams.variable" label="Variable" outlined
        dense @update:model-value="viewPointData(true)"></q-select>
      <q-select class="variable" :options="axisOptions" v-model="modelParams.axis" label="Axis" outlined dense
        @update:model-value="viewPointData(true)"></q-select>
      <q-input class="variable" v-model.number="modelParams.displFactor" type="number" label="Displ. Magnitude" outlined
        dense debounce:500 @update:model-value="viewPointData(true)"></q-input>
      <q-expansion-item v-model="expansion" expand-separator dense dense-toggle icon="fas fa-cogs" label="Options">
        <q-select class="variable" :options="filterOptions" v-model="modelParams.filter" label="Filter" outlined dense
          clearable @update:model-value="viewPointData(true)"></q-select>
        <q-input class="variable" v-model.number="modelParams.colorBarMin" type="number" label="Min." outlined dense
          clearable debounce:500 @update:model-value="viewPointData(true)"></q-input>
        <q-input class="variable" v-model.number="modelParams.colorBarMax" type="number" label="Max." outlined dense
          clearable debounce:500 @update:model-value="viewPointData(true)"></q-input>
      </q-expansion-item>
    </div>
    <vertical-colored-legend class="legend" :min="minValue" :max="maxValue" :key="legendKey" />
    <q-inner-loading :showing="modelLoading">
      <q-spinner-gears size="50px" color="primary"></q-spinner-gears>
    </q-inner-loading>
  </div>
</template>

<script lang="ts">
import { computed, ref } from 'vue'
import { useModelStore } from 'src/stores/model-store';
import VerticalColoredLegend from 'src/components/tools/VerticalColoredLegend.vue';
import { getPointDataResults } from 'src/client';
export default {
  name: 'PeriLab_Web_Results',
  components: {
    VerticalColoredLegend
  },
  setup() {
    const modelStore = useModelStore();
    const modelData = computed(() => modelStore.modelData)

    return {
      modelData,
      modelStore
    }
  },
  data() {
    return {
      modelParams: {
        variable: 'Displacements',
        axis: 'Magnitude',
        displFactor: 1,
        step: 1,
        numberOfSteps: 100,
        filter: '',
        output: 'Output1',
        colorBarMin: null,
        colorBarMax: null
      },
      variableOptions: [
        'Displacements',
        'Damage',
        'Forces',
        'Temperature'
      ],
      axisOptions: [
        'X',
        'Y',
        'Z',
        'Magnitude'
      ],
      filterOptions: [
        'Active',
        'Temperature',
        'Displacements',
        'Damage',
      ],
      sphere: 'Sphere',
      resolution: 6,
      radius: 0.2,
      dx_value: 0.2,
      multiplier: 100,
      pointString: [1, 0, 0, 2, 0, 0, 3, 0, 0, 4, 0, 0, 5, 0, 0, 6, 0, 0, 7, 0, 0, 8, 0, 0, 9, 0, 0, 10, 0, 0, 11, 0, 0],
      blockIdString: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
      file: 'DCBmodel_Output1.e',
      modelLoading: false,
      drawer: false,
      maxValue: 100,
      minValue: 0,
      legendKey: 0,
      viewKey: 0,
      time: 0,
      playing: false,
      timer: ref(),
      expansion: false
    };
  },

  async mounted() {
    console.log('ModelView mounted')
    await this.viewPointData(true);
    this.viewKey++;
  },
  methods: {
    async viewPointData(loading = true) {
      console.log('viewPointData')
      this.modelLoading = loading;

      await this.getPointDataAndUpdateDx();
      this.radius = parseFloat(this.dx_value.toFixed(3));
      this.updatePoints();

      this.modelLoading = false;
    },
    // filterPointData() {
    //   console.log('filterPointData')
    //   var idx = 0;
    //   let filteredBlockIdStringTemp = [];
    //   let filteredPointStringTemp = [];
    //   const blocks = this.modelData.blocks
    //   for (var i = 0; i < this.blockIdString.length; i++) {
    //     if (
    //       blocks[parseInt(this.blockIdString[i] * this.modelData.blocks.length - 1)].show
    //     ) {
    //       filteredBlockIdStringTemp[idx] = this.blockIdString[i];
    //       for (var j = 0; j < 3; j++) {
    //         filteredPointStringTemp[idx * 3 + j] = this.pointString[i * 3 + j];
    //         // this.pointString[i * 3 + j] * this.multiplier;
    //       }
    //       idx += 1;
    //     }
    //   }
    //   this.viewStore.filteredBlockIdString = filteredBlockIdStringTemp;
    //   this.viewStore.filteredPointString = filteredPointStringTemp;
    // },
    updatePoints() {
      this.modelLoading = true;
      console.log('updatePoints')
      // if (this.radius < 0.01) {
      //   this.multiplier = (1 - this.radius / 0.5) * 30;
      //   this.radius=0.01
      // } else if (this.radius <= 0.2) {
      //   this.multiplier = (1 - this.radius / 0.5) * 30;
      // } else {
      //   this.multiplier = 1;
      // }
      // this.filterPointData();
      this.modelLoading = false;
    },
    async getPointDataAndUpdateDx() {

      console.log('getPointDataAndUpdateDx')
      await getPointDataResults({
        modelName: this.modelStore.selectedModel.file,
        modelFolderName: this.modelData.model.modelFolderName!,
        cluster: this.modelData.job.cluster,
        output: this.modelData.outputs[0]!.name,
        tasks: this.modelData.job.tasks,
        axis: this.modelParams.axis,
        step: this.modelParams.step,
        displFactor: this.modelParams.displFactor,
        variable: this.modelParams.variable,
        filter: this.modelParams.filter,
        colorBarMin: this.modelParams.colorBarMin,
        colorBarMax: this.modelParams.colorBarMax
      })
        .then((response) => {
          const data = response
          this.pointString = data.nodes
          this.blockIdString = data.value
          this.dx_value = Math.hypot(
            this.pointString[3]! - this.pointString[0]!,
            this.pointString[4]! - this.pointString[1]!,
            this.pointString[5]! - this.pointString[2]!
          );
          this.maxValue = data.max_value
          this.minValue = data.min_value
          this.variableOptions = data.variables
          this.modelParams.numberOfSteps = data.number_of_steps
          this.time = data.time
        })
        .catch((error) => {
          this.$q.notify({
            type: 'negative',
            message: error.body.detail
          })
        })
    },
    play() {
      this.playing = true
      // eslint-disable-next-line
      this.timer = setInterval(this.forward, 1000)
    },
    pause() {
      this.playing = false
      clearInterval(this.timer)
    },
    async backward() {
      if (this.modelParams.step > 1) {
        this.modelParams.step = this.modelParams.step - 1
        await this.viewPointData(false)
      }
    },
    async fastBackward() {
      this.modelParams.step = 1
      await this.viewPointData(false)
    },
    async forward() {
      if (this.modelParams.step < this.modelParams.numberOfSteps) {
        this.modelParams.step = this.modelParams.step + 1
        await this.viewPointData(false)
      } else {
        this.pause()
      }
    },
    async fastForward() {
      this.modelParams.step = this.modelParams.numberOfSteps
      await this.viewPointData(false)
    }

  },
  watch: {
    maxValue() {
      this.legendKey++; // Increment key to force re-rendering
    },
    minValue() {
      this.legendKey++; // Increment key to force re-rendering
    }
  },
  unmounted() {
    clearInterval(this.timer)
  }
}
</script>

<style>
.viewport {
  height: calc(100% - 50px);
  width: 100%;
}

.settings-column {
  width: 120px;
  margin-left: 5px;
  margin-top: 5px;
}

.legend {
  position: absolute;
  bottom: 160px;
  left: 20px;
  width: 100px;
}

.variables {
  position: absolute;
  top: 58px;
  left: 10px;
  width: 150px;
}

.variable {
  padding: 10px
}

.settings {
  height: 50px;
}
</style>
