// quasar-gui/app/src/components/actions/ModelActions.vue
<template>
    <div class="row">
        <q-btn flat icon="fas fa-upload" @click="readData">
            <q-tooltip>
                Load Model
            </q-tooltip>
        </q-btn>
        <input
            type="file"
            style="display: none"
            ref="fileInput"
            accept="application/json,application/xml,.yaml,.peridigm,.bdf,.cdb,.inp,.gcode"
            @change="onFilePicked"
        />
        <input
          type="file"
          style="display: none"
          ref="multifileInput"
          multiple
          accept="text/plain,.g"
          @change="onMultiFilePicked"
        />
        <q-dialog v-model="dialogGcode" persistent max-width="800">
            <q-card>
                <q-card-section>
                    <div class="text-h6">Gcode Translator</div>
                </q-card-section>

                <q-card-section class="q-pt-none">
                    Configurations
                    <q-input
                        v-model="gcodeDiscretization"
                        :rules="[rules.float]"
                        label="Discretization"
                        clearable
                        standout
                    ></q-input>
                    <q-input
                        v-model="gcodeDt"
                        :rules="[rules.float]"
                        label="dt"
                        clearable
                        standout
                    ></q-input>
                    <q-input
                        v-model="gcodeScale"
                        :rules="[rules.float]"
                        label="Scale"
                        clearable
                        standout
                    ></q-input>
                </q-card-section>
                <q-card-actions align="right">
                    <q-btn flat label="Ok" color="primary" v-close-popup @click="loadGcodeModel"></q-btn>
                    <q-btn flat label="Cancel" color="primary" v-close-popup></q-btn>
                </q-card-actions>
            </q-card>
        </q-dialog>

        <q-btn flat icon="fas fa-save" @click="saveData">
            <q-tooltip>
                Save as JSON
            </q-tooltip>
        </q-btn>

        <q-btn v-if="!modelData.model.ownModel" flat icon="fas fa-undo" @click="bus.emit('resetData')">
            <q-tooltip>
                Reset Data
            </q-tooltip>
        </q-btn>

        <q-btn v-if="modelData.modelmodelNameSelected=='RVE' & !modelData.modelownModel" flat icon="fas fa-cogs" @click="generateMesh">
            <q-tooltip>
                Generate Mesh
            </q-tooltip>
        </q-btn>

        <q-btn flat icon="fas fa-cogs" @click="generateModel">
            <q-tooltip>
                Generate Model
            </q-tooltip>
        </q-btn>

        <q-btn v-if="modelData.model.ownModel" flat icon="fas fa-upload" @click="uploadMesh">
            <q-tooltip>
                Upload Mesh and Nodesets
            </q-tooltip>
        </q-btn>
        
        <q-btn flat icon="fas fa-download" @click="saveModel" :disable="!store.status.created">
            <q-tooltip>
                Download Modelfiles
            </q-tooltip>
        </q-btn>
        
        <q-btn v-if="modelData.model.ownModel" flat icon="fas fa-backward" @click="switchModels">
            <q-tooltip>
                Use predefined Models
            </q-tooltip>
        </q-btn>

        <q-space></q-space>

        <q-btn flat icon="fas fa-sort" @click="bus.emit('openHidePanels')">
            <q-tooltip>
                Collapse/Expand all panel
            </q-tooltip>
        </q-btn>

        <q-btn flat icon="fas fa-info" @click="bus.emit('showTutorial')">
            <q-tooltip>
                Show Tutorial
            </q-tooltip>
        </q-btn>
    </div>
</template>

<script>
    import { computed, defineComponent } from 'vue'
    import { parseFromJson } from '../../utils/functions.js'
    import { useDefaultStore } from 'stores/default-store';
    import { useModelStore } from 'stores/model-store';
    import { useViewStore } from 'stores/view-store';
    import { inject } from 'vue'
    import rules from "assets/rules.js";

export default defineComponent({
    name: "ModelActions",
        setup() {
            const store = useDefaultStore();
            const modelStore = useModelStore();
            const viewStore = useViewStore();
            const modelData = computed(() => modelStore.modelData)
            const bus = inject('bus')

            return {
                store,
                viewStore,
                modelStore,
                modelData,
                rules,
                bus,
            }
        },
    data() {
        return {
            dialogGcode: false,
            gcodeDiscretization: 1,
            gcodeDt: 0.02,
            gcodeScale: 0.001,
            gcodeFile: undefined,
        };
    },
    methods: {
        switchModels() {
            this.modelStore.modelData.model.ownMesh = false;
            this.modelStore.modelData.model.ownModel = false;
            this.modelStore.modelData.model.translated = false;
        },
        readData() {
            this.$refs.fileInput.click();
        },
        uploadMesh() {
            this.$refs.multifileInput.click();
        },
        onFilePicked(event) {
            const file = event.target.files[0];
            const filetype = file.type;
            if (file.length <= 0) {
                return false;
            }

            const fr = new FileReader();

            if (filetype == "application/json") {
                this.loadJsonFile(fr, file);
            } else if (file.name.includes(".yaml")) {
                this.loadYamlModel(fr, file);
            } else if (filetype == "text/xml") {
                this.loadXmlModel(fr, file);
            } else if (filetype == ".peridigm") {
                this.loadPeridigmModel(fr, file);
            } else if (file.name.includes(".gcode")) {
                this.gcodeFile = file;
                this.dialogGcode = true;
            } else {
                this.loadFeModel(file);
            }
        },
        onMultiFilePicked(event) {
            const files = event.target.files;
            const filetype = files[0].type;
            if (files.length <= 0) {
                return false;
            }

            this.viewStore.modelLoading = true;
            this.uploadfiles(files);

            this.bus.emit('viewPointData');
            this.viewStore.modelLoading = false;
            this.snackbar = true;
        },
        async uploadfiles(files) {
            const formData = new FormData();
            for (var i = 0; i < files.length; i++) {
                formData.append("files", files[i]);
            }
            
            let params={
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName
            }

            await this.$api.post('/uploadfiles', formData, {params})
            .then((response) => {
                this.$q.notify({
                    message: response.data.message
                })
            })
            .catch((error) => {
                this.$q.notify({
                    type: 'negative',
                    message: error.response.data.detail
                })
            })
        },
        loadJsonFile(fr, file) {
            this.modelStore.modelData.model.ownMesh = false;
            this.modelStore.modelData.model.ownModel = false;
            this.modelStore.modelData.model.translated = false;

            fr.onload = (e) => {
                const result = JSON.parse(e.target.result);
                parseFromJson(this.modelData,result)
            };
            fr.readAsText(file);
        },
        loadYamlModel(fr, file) {
            this.modelStore.modelData.model.ownMesh = false;
            this.modelStore.modelData.model.ownModel = true;
            this.modelStore.modelData.model.translated = false;

            this.modelStore.modelData.model.modelNameSelected = file.name.split(".")[0];

            fr.onload = (e) => {
                const yaml = e.target.result;
                this.loadYamlString(yaml);
            };
            fr.readAsText(file);
        },
        loadXmlModel(fr, file) {
            this.modelStore.modelData.model.ownMesh = false;
            this.modelStore.modelData.model.ownModel = true;
            this.modelStore.modelData.model.translated = false;

            this.modelStore.modelData.model.modelNameSelected = file.name.split(".")[0];

            fr.onload = (e) => {
                const xml = e.target.result;
                var yaml = this.translateXMLtoYAML(xml);
                this.loadYamlString(yaml);
            };
            fr.readAsText(file);
        },
        async loadFeModel(file) {
            this.modelStore.modelData.model.ownMesh = true;
            this.modelStore.modelData.model.ownModel = true;
            this.modelStore.modelData.model.translated = true;

            this.viewStore.modelLoading = true;
            this.textLoading = true;

            if (file.length <= 0) {
                return false;
            }

            if (await this.checkFeSize(file)) {
                this.modelStore.modelData.model.modelNameSelected = file.name.split(".")[0];
                const filetype = file.name.split(".")[1];

                await this.translateModel(file, filetype, true);
            } else {
                this.viewStore.modelLoading = false;
                this.textLoading = false;
            }
        },
        async loadGcodeModel() {
            this.dialogGcode = false;
            this.modelStore.modelData.model.ownMesh = false;
            this.modelStore.modelData.model.ownModel = true;
            // this.modelStore.modelData.model.translated = true;

            this.viewStore.modelLoading = true;

            if (this.gcodeFile == undefined) {
                return false;
            }

            this.modelStore.modelData.model.modelNameSelected = this.gcodeFile.name.split(".")[0];
            const filetype = this.gcodeFile.name.split(".")[1];

            await this.translateGcode(this.gcodeFile, true);
        },
        async translateGcode(file, upload) {
            if (upload) {
                await this.uploadfiles([file]);
            }
            
            let params={
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName,
                discretization: this.gcodeDiscretization,
                dt: this.gcodeDt,
                scale: this.gcodeScale
            }

            await this.$api.post('/translateGcode', '', {params})
            .then((response) => {
                this.modelStore.modelData.model.meshFile = this.modelData.model.modelNameSelected + ".txt"
                this.$q.notify({
                    message: response.data.message
                })
                this.viewStore.viewId = "model";
                this.bus.emit('viewPointData');
            })
            .catch((error) => {
                this.$q.notify({
                    type: 'negative',
                    message: error.message
                })
            })

            this.viewStore.modelLoading = false;
        },
        saveData() {
            var fileURL = window.URL.createObjectURL(
                new Blob([JSON.stringify(this.modelData)], { type: "application/json" })
            );
            var fileLink = document.createElement("a");
            fileLink.href = fileURL;
            fileLink.setAttribute("download", this.modelData.model.modelNameSelected + ".json");
            document.body.appendChild(fileLink);
            fileLink.click();
        },
        saveModel() {

            let params = {model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName}
            this.$api.get('/getModel', {params, responseType: "blob"})
            .then((response) => {
                var fileURL = window.URL.createObjectURL(new Blob([response.data]));
                var fileLink = document.createElement("a");
                fileLink.href = fileURL;
                fileLink.setAttribute("download", this.modelData.model.modelNameSelected + "_" + this.modelData.model.modelFolderName + ".zip");
                document.body.appendChild(fileLink);
                fileLink.click();
                this.$q.notify({
                    message: response.data.message
                })
            })
            .catch((error) => {
                this.$q.notify({
                    type: 'negative',
                    message: error.response.data.detail
                })
            })
        },
        async generateModel () {

            if (this.modelData.model.ownModel == false) {
                this.viewStore.modelLoading = true;
            }
            this.viewStore.textLoading = true;
            
            let params={
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName
            }

            this.viewStore.viewId = "model";
            
            await this.$api.post('/generateModel', this.modelData, {params})
            .then((response) => {
                this.$q.notify({
                    message: response.data.message
                })
                this.bus.emit("viewInputFile",false)
                if (this.modelData.model.ownModel == false) {
                    console.log("generateModel")
                    // if (this.viewStore.viewId != "model") {
                    this.bus.emit('viewPointData');
                    // }
                }
                this.bus.emit("getStatus")
            })
            .catch((error) => {
                let message = "";
                if (error.response!= undefined && error.response.status == 422) {
                    for (let i in error.response.data.detail) {
                        message += error.response.data.detail[i].loc[1] + " ";
                        message += error.response.data.detail[i].loc[2] + ", ";
                        message += error.response.data.detail[i].loc[3] + ", ";
                        message += error.response.data.detail[i].msg + "\n";
                    }
                    message = message.slice(0, -2);
                }
                else{
                    message = error.message
                }
                this.$q.notify({
                    color: 'negative',
                    position: 'bottom-right',
                    message: message,
                    icon: 'report_problem'
                })
            })

            this.viewStore.modelLoading = false;
            this.viewStore.textLoading = false;
        },
        showTutorial() {
            var color = "gray";
            if (this.$cookie.get("darkMode") == "true") {
                color = "gray";
            } else {
                color = "white";
            }
            console.log(this.$cookie.get("darkMode"));
            console.log(color);

            const driver = new Driver({
                animate: true, // Animate while changing highlighted element
                opacity: 0.5,
                stageBackground: color,
            });

            // Define the steps for introduction
            driver.defineSteps([
                {
                element: "#model-configuration",
                popover: {
                    className: "first-step-popover-class",
                    title: "Title on Popover",
                    description: "Body of the popover",
                    position: "right",
                },
                },
                {
                element: "#model-output",
                popover: {
                    title: "Title on Popover",
                    description: "Body of the popover",
                    position: "left",
                },
                },
                {
                element: "#button-runModel",
                popover: {
                    title: "Title on Popover",
                    description: "Body of the popover",
                    position: "bottom",
                },
                },
            ]);

            // Start the introduction
            driver.start();
        },
    },
})
</script>

// src/lib/components/actions/ModelActions.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Dialog } from 'bits-ui';
  import { Upload, Save, Undo2, Cog, Download, Rewind, ArrowUpDown, Info, X } from 'lucide-svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { downloadFile } from '$lib/utils/download';
  import { api } from '$lib/api/client';
  import { config } from '$lib/config';
  import { generateModel as generateModelApi, saveConfig } from '$lib/client';
  import type { Discretization, ModelData, Valves } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';

  const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms));

  const modelData = $derived(modelStore.modelData);
  const uploadPath = `${config.apiBase}/upload/files`;

  let dialogUpload = $state(false);
  let modelLoading = $state(false);
  let fileInput: HTMLInputElement;
  let uploadInput: HTMLInputElement;
  let uploadBusy = $state(false);

  function switchModels() {
    modelStore.modelData.model.ownMesh = false;
    modelStore.modelData.model.ownModel = false;
  }

  function readData() {
    fileInput.click();
  }

  function onFilePicked(event: Event) {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    if (file.type === 'application/json') loadJsonFile(file);
  }

  function loadJsonFile(file: Blob) {
    modelStore.modelData.model.ownMesh = false;
    modelStore.modelData.model.ownModel = false;

    const fr = new FileReader();
    fr.onload = (e) => {
      const result = JSON.parse(e.target?.result as string);
      if (result.modelData) {
        modelStore.modelData = { ...modelStore.modelData, ...result.modelData } as ModelData;
      } else {
        modelStore.modelData = { ...modelStore.modelData, ...result } as ModelData;
        console.log('Deprecated Json Format!');
      }
      if (result.modelParams) {
        modelStore.modelParams = structuredClone(result.modelParams) as Valves;
      }
      if (result.selectedModel) {
        modelStore.selectedModel = structuredClone(result.selectedModel);
      }
    };
    fr.readAsText(file);
  }

  function saveData() {
    downloadFile(
      `${modelStore.selectedModel.file}.json`,
      '{"modelData":' +
        JSON.stringify(modelStore.modelData) +
        ',"modelParams":' +
        JSON.stringify(modelStore.modelParams) +
        ',"selectedModel":' +
        JSON.stringify(modelStore.selectedModel) +
        '}',
      'application/json'
    );
  }

  async function _saveConfig() {
    try {
      await saveConfig({ configFile: modelStore.selectedModel.file, requestBody: modelData });
      notify.positive('Config saved');
    } catch (error) {
      notify.apiError(error);
    }
  }

  async function saveModel() {
    modelLoading = true;
    try {
      const params = {
        model_name: modelStore.selectedModel.file,
        model_folder_name: modelData.model.modelFolderName
      };
      const response = await api.get('/model/getModel', { params, responseType: 'blob' });
      const filename = `${modelStore.selectedModel.file}_${modelData.model.modelFolderName}.zip`;
      downloadFile(filename, response.data);
    } catch (error) {
      notify.negative('Download failed');
      console.error(error);
    }
    modelLoading = false;
  }

  async function generateModel() {
    if (!modelData.model.ownModel) {
      viewStore.modelLoading = true;
    }
    viewStore.textLoading = true;
    viewStore.viewId = 'model';

    const body = { data: modelData, valves: modelStore.modelParams };

    try {
      await generateModelApi({
        modelName: modelStore.selectedModel.file,
        modelFolderName: modelData.model.modelFolderName,
        requestBody: body
      });
      notify.positive('Model generated');
      bus.emit('updateTextView' as never);
      bus.emit('viewInputFile' as never);
      if (!modelData.model.ownModel) {
        bus.emit('viewPointData' as never);
      }
      bus.emit('getStatus' as never);
      bus.emit('getJobFolders' as never);
    } catch (error: unknown) {
      const err = error as { status?: number; body?: { detail?: unknown } };
      if (err?.status === 422 && Array.isArray(err.body?.detail)) {
        for (const d of err.body!.detail as { msg: string; loc: string[] }[]) {
          notify.negative(`${d.msg} ${d.loc.join(', ')}`);
        }
      } else {
        notify.negative(String(err?.body?.detail ?? 'Model generation failed'));
      }
    }

    viewStore.modelLoading = false;
    viewStore.textLoading = false;
  }

  async function uploadFiles(files: FileList) {
    uploadBusy = true;
    const formData = new FormData();
    Array.from(files).forEach((f) => formData.append('files', f));

    try {
      const response = await api.post(
        `${uploadPath}?model_name=${modelStore.selectedModel.file}&model_folder_name=${modelData.model.modelFolderName}`,
        formData,
        { headers: { username: defaultStore.username } }
      );
      notify.positive('Files uploaded');
      dialogUpload = false;

      const first = files[0]!;
      const type = first.name.split('.')[1];
      if (type === 'gcode') {
        modelStore.modelData.model.meshFile = first.name;
        if (!modelStore.modelData.discretization) {
          modelStore.modelData.discretization = {} as Discretization;
        }
        modelStore.modelData.discretization.discType = 'gcode';
        if (!modelStore.modelData.discretization.gcode) {
          modelStore.modelData.discretization.gcode = {
            overwriteMesh: true,
            sampling: 1,
            width: 0.4,
            height: 0.2,
            scale: 1
          };
        }
      } else if (type === 'g') {
        viewStore.modelLoading = true;
        viewStore.viewId = 'model';
        await sleep(500);
        bus.emit('viewPointData' as never);
      } else if (type === 'txt' || type === 'e') {
        if (response.data?.message) {
          modelStore.modelData.model.meshFile = first.name;
          if (!modelStore.modelData.discretization) {
            modelStore.modelData.discretization = {} as Discretization;
          }
          modelStore.modelData.discretization.discType = type as 'txt' | 'e';
        }
        if (type === 'txt') {
          viewStore.modelLoading = true;
          viewStore.viewId = 'model';
          await sleep(500);
          bus.emit('viewPointData' as never);
        }
      }
      bus.emit('getStatus' as never);
    } catch (error) {
      console.error(error);
      notify.negative('Upload failed, file type not supported!');
    }
    viewStore.modelLoading = false;
    uploadBusy = false;
  }

  function onUploadPicked(event: Event) {
    const files = (event.target as HTMLInputElement).files;
    if (files && files.length > 0) uploadFiles(files);
  }
</script>

<div class="flex flex-wrap items-center gap-1 border-b border-border bg-muted/30 px-2 py-1">
  <Button variant="ghost" size="icon" onclick={readData} disabled={defaultStore.trial} title={defaultStore.trial ? 'Disabled in trial version' : 'Load Model'}>
    <Upload class="h-4 w-4" />
  </Button>
  <input bind:this={fileInput} type="file" class="hidden" accept="application/json" onchange={onFilePicked} />

  <Button variant="ghost" size="icon" onclick={saveData} title="Save as JSON">
    <Save class="h-4 w-4" />
  </Button>

  {#if defaultStore.dev}
    <Button variant="ghost" size="icon" onclick={_saveConfig} title="Save Config">
      <Save class="h-4 w-4" />
    </Button>
  {/if}

  {#if !modelData.model.ownModel}
    <Button variant="ghost" size="icon" onclick={() => bus.emit('resetData')} title="Reset Data">
      <Undo2 class="h-4 w-4" />
    </Button>
  {/if}

  <Button variant="ghost" size="icon" onclick={generateModel} title="Generate Model" id="button-runModel">
    <Cog class="h-4 w-4" />
  </Button>

  {#if modelData.model.ownModel}
    <Button
      variant="ghost"
      size="icon"
      onclick={() => (dialogUpload = true)}
      disabled={defaultStore.trial}
      title={defaultStore.trial ? 'Disabled in trial version' : 'Upload Modelfiles'}
    >
      <Upload class="h-4 w-4" />
    </Button>
  {/if}

  <Button
    variant="ghost"
    size="icon"
    onclick={saveModel}
    disabled={modelLoading || !defaultStore.status.created}
    title="Download Modelfiles"
  >
    <Download class="h-4 w-4" />
  </Button>

  {#if modelData.model.ownModel}
    <Button variant="ghost" size="icon" onclick={switchModels} title="Use predefined Models">
      <Rewind class="h-4 w-4" />
    </Button>
  {/if}

  <div class="flex-1"></div>

  <Button variant="ghost" size="icon" onclick={() => bus.emit('openHidePanels')} title="Collapse/Expand all panels">
    <ArrowUpDown class="h-4 w-4" />
  </Button>

  <Button variant="ghost" size="icon" onclick={() => bus.emit('showTutorial')} title="Show Tutorial">
    <Info class="h-4 w-4" />
  </Button>
</div>

<Dialog.Root bind:open={dialogUpload}>
  <Dialog.Portal>
    <Dialog.Overlay class="fixed inset-0 z-50 bg-black/50" />
    <Dialog.Content
      class="fixed left-1/2 top-1/2 z-50 w-[min(92vw,26rem)] -translate-x-1/2 -translate-y-1/2 rounded-xl border border-border bg-card p-5 shadow-lg"
    >
      <div class="mb-3 flex items-center justify-between">
        <Dialog.Title class="text-lg font-semibold">Upload Data</Dialog.Title>
        <Dialog.Close class="rounded-full p-1.5 hover:bg-muted"><X class="h-4 w-4" /></Dialog.Close>
      </div>
      <input
        bind:this={uploadInput}
        type="file"
        multiple
        onchange={onUploadPicked}
        disabled={uploadBusy}
        class="block w-full text-sm text-muted-foreground file:mr-3 file:rounded-md file:border-0 file:bg-primary file:px-3 file:py-1.5 file:text-primary-foreground hover:file:bg-primary/90"
      />
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>
