// frontend/app/src/components/actions/ModelActions.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div class="row">
    <q-btn flat icon="fas fa-upload" @click="readData" :disable="store.TRIAL">
      <q-tooltip>
        <div v-if="!store.TRIAL">Load Model</div>
        <div v-if="store.TRIAL">Disabled in trial version</div>
      </q-tooltip>
    </q-btn>
    <input type="file" style="display: none" ref="fileInput" accept="application/json" @change="onFilePicked" />

    <q-btn flat icon="fas fa-save" @click="saveData">
      <q-tooltip>
        Save as JSON
      </q-tooltip>
    </q-btn>

    <q-btn v-if="store.DEV" flat icon="fas fa-save" @click="_saveConfig">
      <q-tooltip>
        Save Config
      </q-tooltip>
    </q-btn>

    <q-btn v-if="!modelData.model.ownModel" flat icon="fas fa-undo" @click="$bus.emit('resetData')">
      <q-tooltip>
        Reset Data
      </q-tooltip>
    </q-btn>

    <q-btn flat icon="fas fa-cogs" @click="generateModel">
      <q-tooltip>
        Generate Model
      </q-tooltip>
    </q-btn>

    <q-btn v-if="modelData.model.ownModel" flat icon="fas fa-upload" @click="dialogUpload = true"
      :disable="store.TRIAL">
      <q-tooltip>
        <div v-if="!store.TRIAL">Upload Modelfiles</div>
        <div v-if="store.TRIAL">Disabled in trial version</div>
      </q-tooltip>
    </q-btn>

    <q-btn flat icon="fas fa-download" @click="saveModel" :loading="modelLoading"
      :disable="modelLoading || !status.created">
      <q-tooltip>
        Download Modelfiles
      </q-tooltip>
    </q-btn>

    <q-btn v-if="modelData.model.ownModel" flat icon="fas fa-backward" @click="switchModels">
      <q-tooltip>
        Use predefined Models
      </q-tooltip>
    </q-btn>

    <q-space></q-space>

    <q-btn flat icon="fas fa-sort" @click="$bus.emit('openHidePanels')">
      <q-tooltip>
        Collapse/Expand all panel
      </q-tooltip>
    </q-btn>

    <q-btn flat icon="fas fa-info" @click="$bus.emit('showTutorial')">
      <q-tooltip>
        Show Tutorial
      </q-tooltip>
    </q-btn>
    <q-dialog v-model="dialogUpload" style="max-width: 200px">
      <q-card>
        <q-card-section>
          <div class="text-h6">Upload Data</div>
        </q-card-section>
        <q-card-section class="q-pt-none">
          <q-uploader
            :url="uploadPath + '?model_name=' + modelStore.selectedModel.file + '&model_folder_name=' + modelData.model.modelFolderName"
            :headers="[{ name: 'username', value: store.username }]" field-name="files" label="Pick file" filled counter
            multiple style="max-width: 300px" @uploaded="uploadFinished" @failed="uploadFailed" />
          <!--max-file-size="2097152"  -->
        </q-card-section>
      </q-card>
    </q-dialog>

  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import { useDefaultStore } from 'src/stores/default-store';
import { useModelStore } from 'src/stores/model-store';
import { useViewStore } from 'src/stores/view-store';
import { exportFile } from 'quasar'
import { api } from 'boot/axios';
import { generateModel, saveConfig } from 'src/client';
import type { Discretization_Input } from 'src/client';
import rules from 'assets/rules.js';

const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms));

export default defineComponent({
  name: 'ModelActions',
  setup() {
    const store = useDefaultStore();
    const status = store.status;
    const modelStore = useModelStore();
    const viewStore = useViewStore();
    const modelData = computed(() => modelStore.modelData)
    const uploadPath = process.env.API + '/upload/files'

    return {
      store,
      status,
      viewStore,
      modelStore,
      modelData,
      rules,
      uploadPath
    }
  },
  data() {
    return {
      dialogUpload: false,
      modelLoading: false,
    };
  },
  methods: {
    switchModels() {
      this.modelStore.modelData.model.ownMesh = false;
      this.modelStore.modelData.model.ownModel = false;
    },
    readData() {
      // @ts-expect-error Bla
      this.$refs.fileInput.click();
    },
    uploadMesh() {
      // @ts-expect-error Bla
      this.$refs.meshInput.click();
    },
    uploadNodesets() {
      // @ts-expect-error Bla
      this.$refs.nodesetsInput.click();
    },
    async uploadFinished(res) {
      this.$q.notify({
        message: 'Files uploaded'
      })
      this.dialogUpload = false
      const type = res.files[0].name.split('.')[1]
      console.log(type)
      if (type == 'gcode') {
        this.modelStore.modelData.model.meshFile = res.files[0].name
        if (!this.modelStore.modelData.discretization) {
          this.modelStore.modelData.discretization = {} as Discretization_Input
        }
        this.modelStore.modelData.discretization.discType = 'gcode'
        if (!this.modelStore.modelData.discretization.gcode) {
          this.modelStore.modelData.discretization.gcode = {
            overwriteMesh: true,
            sampling: 1,
            width: 0.4,
            height: 0.2,
            scale: 1,
          }
        }
      } else if (type == 'g') {
        this.viewStore.modelLoading = true;
        this.viewStore.viewId = 'model';
        await sleep(500)
        this.$bus.emit('viewPointData');
      } else if (type == 'txt') {
        if (JSON.parse(res.xhr.response).message != '') {
          this.modelStore.modelData.model.meshFile = res.files[0].name
          if (!this.modelStore.modelData.discretization) {
            this.modelStore.modelData.discretization = {} as Discretization_Input
          }
          this.modelStore.modelData.discretization.discType = 'txt'
        }
        this.viewStore.modelLoading = true;
        this.viewStore.viewId = 'model';
        await sleep(500)
        this.$bus.emit('viewPointData');
      }
      this.$bus.emit('getStatus')
      this.viewStore.modelLoading = false;
    },
    uploadFailed(res) {
      console.log(res)
      this.$q.notify({
        message: 'Upload failed, file type not supported!',
        type: 'negative'
      })
    },
    // onNodesetsPicked(event) {
    //   const files = event.target.files;
    //   const filetype = files[0].type;
    //   if (files.length <= 0) {
    //     return false;
    //   }

    //   this.viewStore.modelLoading = true;
    //   this._uploadfiles(files);

    //   for (var i = 0; i < files.length; i++) {
    //     if (this.modelStore.modelData.boundaryConditions.conditions.length < i + 1) {
    //       this.$bus.emit('addCondition')
    //     }
    //     this.modelStore.modelData.boundaryConditions.nodeSets[i].file = files[i].name
    //   }

    //   this.viewStore.modelLoading = false;
    // },
    onFilePicked(event: Event) {
      // @ts-expect-error Bla
      const file = event.target.files[0];
      const filetype = file.type;
      if (file.length <= 0) {
        return false;
      }

      const fr = new FileReader();

      if (filetype == 'application/json') {
        this.loadJsonFile(fr, file);
      }
    },
    loadJsonFile(fr: FileReader, file: string) {
      this.modelStore.modelData.model.ownMesh = false;
      this.modelStore.modelData.model.ownModel = false;

      fr.onload = (e) => {
        // @ts-expect-error Bla
        const result = JSON.parse(e.target.result);
        console.log(result)
        if (result.modelData) {
          this.modelStore.modelData = structuredClone(result.modelData)
        } else {
          this.modelStore.modelData = structuredClone(result)
          console.log('Deprecated Json Format!')
        }
        if (result.modelParams) {
          this.modelStore.modelParams = structuredClone(result.modelParams)
        }
        if (result.selectedModel) {
          this.modelStore.selectedModel = structuredClone(result.selectedModel)
        }
        // const filename = file.name.split('.')[0]
        // if (this.modelStore.modelData.model.ownModel) {
        //   this.modelStore.selectedModel.file = filename;
        // }
      };
      fr.readAsText(file);
    },
    saveData() {
      exportFile(this.modelStore.selectedModel.file + '.json', '{"modelData":' + JSON.stringify(this.modelStore.modelData) + ',"modelParams":' + JSON.stringify(this.modelStore.modelParams) + ',"selectedModel":' + JSON.stringify(this.modelStore.selectedModel) + '}');
    },
    async _saveConfig() {
      await saveConfig({
        configFile: this.modelStore.selectedModel.file,
        requestBody: this.modelData,
      }).then(() => this.$q.notify({
        message: 'Config saved',
      })).catch((error) => {
        console.log(error.body.detail)
        this.$q.notify({
          type: 'negative',
          message: error.body.detail
        })
      })
    },
    async saveModel() {
      this.modelLoading = true;
      const params = {
        model_name: this.modelStore.selectedModel.file,
        model_folder_name: this.modelData.model.modelFolderName
      }
      // getModel({ modelName: this.modelStore.selectedModel.file, modelFolderName: this.modelData.model.modelFolderName })
      await api.get('/model/getModel', { params, responseType: 'blob' })
        .then((response) => {
          const filename = this.modelStore.selectedModel.file + '_' + this.modelData.model.modelFolderName + '.zip'
          const status = exportFile(filename, response.data)
          if (status) {
            // browser allowed it
            console.log('ok')
          } else {
            // browser denied it
            console.log(status)
            this.$q.notify({
              message: status
            })
          }
        })
        .catch((error) => {
          console.log(error)
          this.$q.notify({
            type: 'negative',
            message: error
          })
        })
      this.modelLoading = false;
    },
    async generateModel() {

      if (this.modelData.model.ownModel == false) {
        this.viewStore.modelLoading = true;
      }
      this.viewStore.textLoading = true;

      this.viewStore.viewId = 'model';

      const body = {
        'model_data': this.modelData,
        'valves': this.modelStore.modelParams
      }

      await generateModel({
        modelName: this.modelStore.selectedModel.file,
        modelFolderName: this.modelData.model.modelFolderName,
        requestBody: body
      })
        .then((response) => {
          console.log('generateModel')
          this.$q.notify({
            message: response.message
          })
          this.$bus.emit('viewInputFile', false)
          if (this.modelData.model.ownModel == false) {
            // if (this.viewStore.viewId != 'model') {
            this.$bus.emit('viewPointData');
            // }
          }
          this.$bus.emit('getStatus')
          this.$bus.emit('getJobFolders')
        })
        .catch((error) => {
          error = JSON.parse(JSON.stringify(error))
          console.log(error)
          // console.log(error.response)
          // console.log(error.response.status)
          if (error != undefined && error.status == 422) {
            for (const i in error.body.detail) {
              let message = '';
              message += error.body.detail[i].msg + ' ';
              for (const j in error.body.detail[i].loc) {
                message += error.body.detail[i].loc[j] + ', ';
              }
              this.$q.notify({
                color: 'negative',
                position: 'bottom-right',
                message: message,
                icon: 'report_problem',
                timeout: 0,
                actions: [{ icon: 'close', color: 'white' }]
              })
            }
          }
          else {
            this.$q.notify({
              color: 'negative',
              message: error.body.detail,
              icon: 'report_problem'
            })
          }
        })

      this.viewStore.modelLoading = false;
      this.viewStore.textLoading = false;
    },
    showTutorial() {
      let color = 'gray';
      if (this.$cookie.get('darkMode') == 'true') {
        color = 'gray';
      } else {
        color = 'white';
      }
      console.log(this.$cookie.get('darkMode'));
      console.log(color);

      const driver = new Driver({
        animate: true, // Animate while changing highlighted element
        opacity: 0.5,
        stageBackground: color,
      });

      // Define the steps for introduction
      driver.defineSteps([
        {
          element: '#model-configuration',
          popover: {
            className: 'first-step-popover-class',
            title: 'Title on Popover',
            description: 'Body of the popover',
            position: 'right',
          },
        },
        {
          element: '#model-output',
          popover: {
            title: 'Title on Popover',
            description: 'Body of the popover',
            position: 'left',
          },
        },
        {
          element: '#button-runModel',
          popover: {
            title: 'Title on Popover',
            description: 'Body of the popover',
            position: 'bottom',
          },
        },
      ]);

      // Start the introduction
      driver.start();
    },
  }
})
</script>
<style>
.q-btn {
  padding-right: 5px;
}
</style>

// src/lib/components/actions/ModelActions.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Dialog } from 'bits-ui';
  import { Upload, Save, Undo2, Cog, Download, Rewind, ArrowUpDown, Info, X } from 'lucide-svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { downloadFile } from '$lib/utils/download';
  import { api } from '$lib/api/client';
  import { config } from '$lib/config';
  import { generateModel as generateModelApi, saveConfig } from '$lib/client';
  import type { Discretization, ModelData, Valves } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';

  const sleep = (ms: number) => new Promise((res) => setTimeout(res, ms));

  const modelData = $derived(modelStore.modelData);
  const uploadPath = `${config.apiBase}/upload/files`;

  let dialogUpload = $state(false);
  let modelLoading = $state(false);
  let fileInput: HTMLInputElement;
  let uploadInput: HTMLInputElement;
  let uploadBusy = $state(false);

  function switchModels() {
    modelStore.modelData.model.ownMesh = false;
    modelStore.modelData.model.ownModel = false;
  }

  function readData() {
    fileInput.click();
  }

  function onFilePicked(event: Event) {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;
    if (file.type === 'application/json') loadJsonFile(file);
  }

  function loadJsonFile(file: Blob) {
    modelStore.modelData.model.ownMesh = false;
    modelStore.modelData.model.ownModel = false;

    const fr = new FileReader();
    fr.onload = (e) => {
      const result = JSON.parse(e.target?.result as string);
      if (result.modelData) {
        modelStore.modelData = { ...modelStore.modelData, ...result.modelData } as ModelData;
      } else {
        modelStore.modelData = { ...modelStore.modelData, ...result } as ModelData;
        console.log('Deprecated Json Format!');
      }
      if (result.modelParams) {
        modelStore.modelParams = structuredClone(result.modelParams) as Valves;
      }
      if (result.selectedModel) {
        modelStore.selectedModel = structuredClone(result.selectedModel);
      }
    };
    fr.readAsText(file);
  }

  function saveData() {
    downloadFile(
      `${modelStore.selectedModel.file}.json`,
      '{"modelData":' +
        JSON.stringify(modelStore.modelData) +
        ',"modelParams":' +
        JSON.stringify(modelStore.modelParams) +
        ',"selectedModel":' +
        JSON.stringify(modelStore.selectedModel) +
        '}',
      'application/json'
    );
  }

  async function _saveConfig() {
    try {
      await saveConfig({ configFile: modelStore.selectedModel.file, requestBody: modelData });
      notify.positive('Config saved');
    } catch (error) {
      notify.apiError(error);
    }
  }

  async function saveModel() {
    modelLoading = true;
    try {
      const params = {
        model_name: modelStore.selectedModel.file,
        model_folder_name: modelData.model.modelFolderName
      };
      const response = await api.get('/model/getModel', { params, responseType: 'blob' });
      const filename = `${modelStore.selectedModel.file}_${modelData.model.modelFolderName}.zip`;
      downloadFile(filename, response.data);
    } catch (error) {
      notify.negative('Download failed');
      console.error(error);
    }
    modelLoading = false;
  }

  async function generateModel() {
    if (!modelData.model.ownModel) {
      viewStore.modelLoading = true;
    }
    viewStore.textLoading = true;
    viewStore.viewId = 'model';

    const body = { data: modelData, valves: modelStore.modelParams };

    try {
      await generateModelApi({
        modelName: modelStore.selectedModel.file,
        modelFolderName: modelData.model.modelFolderName,
        requestBody: body
      });
      notify.positive('Model generated');
      bus.emit('updateTextView' as never);
      bus.emit('viewInputFile' as never);
      if (!modelData.model.ownModel) {
        bus.emit('viewPointData' as never);
      }
      bus.emit('getStatus' as never);
      bus.emit('getJobFolders' as never);
    } catch (error: unknown) {
      const err = error as { status?: number; body?: { detail?: unknown } };
      if (err?.status === 422 && Array.isArray(err.body?.detail)) {
        for (const d of err.body!.detail as { msg: string; loc: string[] }[]) {
          notify.negative(`${d.msg} ${d.loc.join(', ')}`);
        }
      } else {
        notify.negative(String(err?.body?.detail ?? 'Model generation failed'));
      }
    }

    viewStore.modelLoading = false;
    viewStore.textLoading = false;
  }

  async function uploadFiles(files: FileList) {
    uploadBusy = true;
    const formData = new FormData();
    Array.from(files).forEach((f) => formData.append('files', f));

    try {
      const response = await api.post(
        `${uploadPath}?model_name=${modelStore.selectedModel.file}&model_folder_name=${modelData.model.modelFolderName}`,
        formData,
        { headers: { username: defaultStore.username } }
      );
      notify.positive('Files uploaded');
      dialogUpload = false;

      const first = files[0]!;
      const type = first.name.split('.')[1];
      if (type === 'gcode') {
        modelStore.modelData.model.meshFile = first.name;
        if (!modelStore.modelData.discretization) {
          modelStore.modelData.discretization = {} as Discretization;
        }
        modelStore.modelData.discretization.discType = 'gcode';
        if (!modelStore.modelData.discretization.gcode) {
          modelStore.modelData.discretization.gcode = {
            overwriteMesh: true,
            sampling: 1,
            width: 0.4,
            height: 0.2,
            scale: 1
          };
        }
      } else if (type === 'g') {
        viewStore.modelLoading = true;
        viewStore.viewId = 'model';
        await sleep(500);
        bus.emit('viewPointData' as never);
      } else if (type === 'txt' || type === 'e') {
        if (response.data?.message) {
          modelStore.modelData.model.meshFile = first.name;
          if (!modelStore.modelData.discretization) {
            modelStore.modelData.discretization = {} as Discretization;
          }
          modelStore.modelData.discretization.discType = type as 'txt' | 'e';
        }
        if (type === 'txt') {
          viewStore.modelLoading = true;
          viewStore.viewId = 'model';
          await sleep(500);
          bus.emit('viewPointData' as never);
        }
      }
      bus.emit('getStatus' as never);
    } catch (error) {
      console.error(error);
      notify.negative('Upload failed, file type not supported!');
    }
    viewStore.modelLoading = false;
    uploadBusy = false;
  }

  function onUploadPicked(event: Event) {
    const files = (event.target as HTMLInputElement).files;
    if (files && files.length > 0) uploadFiles(files);
  }
</script>

<div class="flex flex-wrap items-center gap-1 border-b border-border bg-muted/30 px-2 py-1">
  <Button variant="ghost" size="icon" onclick={readData} disabled={defaultStore.trial} title={defaultStore.trial ? 'Disabled in trial version' : 'Load Model'}>
    <Upload class="h-4 w-4" />
  </Button>
  <input bind:this={fileInput} type="file" class="hidden" accept="application/json" onchange={onFilePicked} />

  <Button variant="ghost" size="icon" onclick={saveData} title="Save as JSON">
    <Save class="h-4 w-4" />
  </Button>

  {#if defaultStore.dev}
    <Button variant="ghost" size="icon" onclick={_saveConfig} title="Save Config">
      <Save class="h-4 w-4" />
    </Button>
  {/if}

  {#if !modelData.model.ownModel}
    <Button variant="ghost" size="icon" onclick={() => bus.emit('resetData')} title="Reset Data">
      <Undo2 class="h-4 w-4" />
    </Button>
  {/if}

  <Button variant="ghost" size="icon" onclick={generateModel} title="Generate Model" id="button-runModel">
    <Cog class="h-4 w-4" />
  </Button>

  {#if modelData.model.ownModel}
    <Button
      variant="ghost"
      size="icon"
      onclick={() => (dialogUpload = true)}
      disabled={defaultStore.trial}
      title={defaultStore.trial ? 'Disabled in trial version' : 'Upload Modelfiles'}
    >
      <Upload class="h-4 w-4" />
    </Button>
  {/if}

  <Button
    variant="ghost"
    size="icon"
    onclick={saveModel}
    disabled={modelLoading || !defaultStore.status.created}
    title="Download Modelfiles"
  >
    <Download class="h-4 w-4" />
  </Button>

  {#if modelData.model.ownModel}
    <Button variant="ghost" size="icon" onclick={switchModels} title="Use predefined Models">
      <Rewind class="h-4 w-4" />
    </Button>
  {/if}

  <div class="flex-1"></div>

  <Button variant="ghost" size="icon" onclick={() => bus.emit('openHidePanels')} title="Collapse/Expand all panels">
    <ArrowUpDown class="h-4 w-4" />
  </Button>

  <Button variant="ghost" size="icon" onclick={() => bus.emit('showTutorial')} title="Show Tutorial">
    <Info class="h-4 w-4" />
  </Button>
</div>

<Dialog.Root bind:open={dialogUpload}>
  <Dialog.Portal>
    <Dialog.Overlay class="fixed inset-0 z-50 bg-black/50" />
    <Dialog.Content
      class="fixed left-1/2 top-1/2 z-50 w-[min(92vw,26rem)] -translate-x-1/2 -translate-y-1/2 rounded-xl border border-border bg-card p-5 shadow-lg"
    >
      <div class="mb-3 flex items-center justify-between">
        <Dialog.Title class="text-lg font-semibold">Upload Data</Dialog.Title>
        <Dialog.Close class="rounded-full p-1.5 hover:bg-muted"><X class="h-4 w-4" /></Dialog.Close>
      </div>
      <input
        bind:this={uploadInput}
        type="file"
        multiple
        onchange={onUploadPicked}
        disabled={uploadBusy}
        class="block w-full text-sm text-muted-foreground file:mr-3 file:rounded-md file:border-0 file:bg-primary file:px-3 file:py-1.5 file:text-primary-foreground hover:file:bg-primary/90"
      />
    </Dialog.Content>
  </Dialog.Portal>
</Dialog.Root>
