// quasar-gui/app/src/components/actions/TextActions.vue
<template>
    <div class="row">
        <q-btn flat icon="fas fa-sync-alt" @click="viewInputFile(false)" :disable="!store.status.created">
            <q-tooltip>
                Reload Inputfile
            </q-tooltip>
        </q-btn>
        <q-btn flat icon="fas fa-save" @click="writeInputFile"
            :disable="!store.status.created || viewStore.textId != 'input'">
            <q-tooltip>
                Save Inputfile
            </q-tooltip>
        </q-btn>

        <q-space></q-space>
    </div>
</template>

<script>
import { computed, defineComponent } from 'vue'
import { useDefaultStore } from 'stores/default-store';
import { useModelStore } from 'stores/model-store';
import { useViewStore } from 'stores/view-store';
import { inject } from 'vue'
import { useQuasar } from 'quasar'
import rules from "assets/rules.js";

export default defineComponent({
    name: "TextActions",
    setup() {
        const $q = useQuasar()
        const store = useDefaultStore();
        const modelStore = useModelStore();
        const viewStore = useViewStore();
        const modelData = computed(() => modelStore.modelData)
        const bus = inject('bus')

        return {
            store,
            viewStore,
            modelData,
            rules,
            bus,
        }
    },
    created() {
        this.bus.on('enableWebsocket', (loadFile) => {
            this.enableWebsocket(loadFile)
        })
        this.bus.on('viewInputFile', (loadFile) => {
            this.viewInputFile(loadFile)
        })
        this.bus.on('getStatus', () => {
            this.getStatus()
        })
    },
    data() {
        return {
            connection: null,
        };
    },
    methods: {
        async viewInputFile(loadFile) {

            let params = {
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName,
                own_mesh: this.modelData.model.ownMesh,
                file_type: this.modelData.solver.filetype
            }

            this.$api.get('/viewInputFile', { params })
                .then((response) => {
                    this.$q.notify({
                        message: response.data.message
                    })
                    this.viewStore.textOutput = response.data.data;
                    this.viewStore.textId = "input"
                    if (loadFile) {
                        this.loadYamlString(response.data.data);
                    }
                })
                .catch((error) => {
                    this.$q.notify({
                        color: 'negative',
                        position: 'bottom-right',
                        message: error,
                        icon: 'report_problem'
                    })
                })
        },
        writeInputFile() {
            let params = {
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName,
                input_string: this.viewStore.textOutput,
                file_type: this.modelData.solver.filetype,
            }

            this.$api.put('/writeInputFile', '', { params })
                .then((response) => {
                    this.$q.notify({
                        message: response.data.message
                    })
                })
                .catch((error) => {
                    this.$q.notify({
                        type: 'negative',
                        message: error.response.data.detail
                    })
                })
        },
        async getStatus() {
            console.log("getStatus");

            let params = {
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName,
                own_model: this.modelData.model.ownModel,
                cluster: this.modelData.job.cluster
            }

            this.$api.get('/getStatus', { params })
                .then((response) => {
                    this.$q.notify({
                        message: response.data.message
                    })
                    this.store.status = response.data.data
                    console.log(this.store.status)
                })
                .catch((error) => {
                    this.$q.notify({
                        type: 'negative',
                        message: error.response.data.detail
                    })
                })
        },
        enableWebsocket() {
            // Check if there is an existing connection
            if (this.connection) {
                // Close the existing connection
                this.connection.close();
                this.connection = null; // Reset the connection variable
            }
            console.log("websocket");
            const params = {
                model_name: this.modelData.model.modelNameSelected,
                model_folder_name: this.modelData.model.modelFolderName,
                cluster: this.modelData.job.cluster,
                token: this.$api.defaults.headers.common['Authorization']
            };

            const queryString = Object.entries(params)
                .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(value)}`)
                .join('&');

            const socket_path = `ws${process.env.API.split("http")[1]}/log?${queryString}`;

            // const socket_path = "ws" + process.env.API.split("http")[1] + '/log?token=' + this.$api.defaults.headers.common['Authorization']
            console.log(socket_path)
            this.connection = new WebSocket(socket_path);
            this.connection.onmessage = (event) => {
                this.viewStore.logOutput = event.data;
            }
        },
    },
    mounted() {
        this.getStatus();
        this.enableWebsocket();
    },
})
</script>

// src/lib/components/actions/TextActions.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { Save } from 'lucide-svelte';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { bus } from '$lib/utils/bus';
  import { notify } from '$lib/utils/notify';
  import { config } from '$lib/config';
  import { getStatus, viewInputFile as viewInputFileApi, writeInputFile as writeInputFileApi, OpenAPI } from '$lib/client';
  import Button from '$lib/components/ui/Button.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';

  const modelData = $derived(modelStore.modelData);

  let connection: WebSocket | null = null;
  let debug = $state(false);
  let lastLine = '';

  function viewInputFile() {
    viewInputFileApi({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName
    })
      .then((response) => {
        notify.positive('Inputfile loaded');
        viewStore.textOutput = response as unknown as string;
        viewStore.textId = 'input';
      })
      .catch((error) => notify.apiError(error));
  }

  function writeInputFile() {
    writeInputFileApi({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName,
      inputString: viewStore.textOutput
    })
      .then(() => notify.positive('Inputfile saved'))
      .catch((error) => notify.apiError(error));
  }

  function _getStatus() {
    getStatus({
      modelName: modelStore.selectedModel.file,
      modelFolderName: modelData.model.modelFolderName,
      meshfile: modelData.model.meshFile!,
      cluster: modelData.job.cluster,
      sbatch: modelData.job.sbatch
    })
      .then((response) => {
        notify.positive('Status updated');
        defaultStore.status = response;
      })
      .catch((error) => notify.apiError(error));
  }

  function enableWebsocket() {
    if (connection) {
      connection.close();
      connection = null;
    }
    const params = {
      model_name: modelStore.selectedModel.file,
      model_folder_name: modelData.model.modelFolderName,
      cluster: modelData.job.cluster,
      token: OpenAPI.TOKEN,
      user_name: defaultStore.username,
      debug
    };
    const queryString = Object.entries(params)
      .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`)
      .join('&');

    let socketPath = `ws://${window.location.host}/ws?${queryString}`;
    if (window.location.protocol === 'https:') {
      socketPath = `wss://${window.location.host}/ws?${queryString}`;
    }
    if (config.dev) {
      socketPath = `ws://localhost:8000/ws?${queryString}`;
    }

    connection = new WebSocket(socketPath);
    connection.onmessage = (event) => {
      viewStore.logOutput = event.data;
      const lines = viewStore.logOutput.split('\n');
      const currentLastLine = lines[lines.length - 2];
      if (currentLastLine !== lastLine) {
        if (currentLastLine?.includes('[Info] Run ')) {
          viewStore.viewId = 'results';
        }
        if (currentLastLine?.includes('[Info] PeriLab finished') && connection) {
          connection.close();
          connection = null;
          _getStatus();
          bus.emit('getJobs' as never);
          if (defaultStore.status.submitted) notify.positive('PeriLab finished');
        }
        if (currentLastLine?.includes('[Error]') && connection) {
          connection.close();
          connection = null;
          _getStatus();
          bus.emit('getJobs' as never);
          if (defaultStore.status.submitted) notify.negative(currentLastLine);
        }
        lastLine = currentLastLine ?? '';
      }
    };
    connection.onerror = (event) => {
      console.error(event);
      notify.negative('Websocket error');
    };
    viewStore.textLoading = false;
  }

  onMount(() => {
    _getStatus();
    enableWebsocket();

    bus.on('enableWebsocket' as never, enableWebsocket);
    bus.on('viewInputFile' as never, viewInputFile);
    bus.on('getStatus' as never, _getStatus);

    return () => {
      bus.off('enableWebsocket' as never, enableWebsocket);
      bus.off('viewInputFile' as never, viewInputFile);
      bus.off('getStatus' as never, _getStatus);
      connection?.close();
    };
  });

  onDestroy(() => connection?.close());
</script>

<div class="flex items-center gap-1 border-b border-border bg-muted/30 px-2 py-1">
  <Button
    variant="ghost"
    size="icon"
    onclick={writeInputFile}
    disabled={!defaultStore.status.created || viewStore.textId !== 'input' || defaultStore.trial}
    title={defaultStore.trial ? 'Disabled in trial version' : 'Save Inputfile'}
  >
    <Save class="h-4 w-4" />
  </Button>
  <div class="flex-1"></div>
  <Toggle bind:checked={debug} label="Debug" />
</div>
