// frontend/app/src/components/ViewComp.vue
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<template>
  <div :style="{ 'height': viewHeight }">
    <q-tabs v-model="viewStore.viewId" dense class="text-grey" active-color="primary" indicator-color="primary"
      align="justify">
      <q-tab name="image" label="Image"></q-tab>
      <q-tab name="model" label="Model"></q-tab>
      <q-tab name="cad" label="CAD"></q-tab>
      <q-tab name="jobs" label="Jobs"></q-tab>
      <q-tab v-show="outputs.some((output) => output.selectedFileType == 'Exodus')" name="results"
        label="Results"></q-tab>
      <q-tab v-show="outputs.some((output) => output.selectedFileType == 'CSV')" name="plotly" label="Plotly"></q-tab>
      <!-- <q-tab name="json" label="Json"></q-tab> -->
      <q-tab v-show="store.saveEnergy" name="renewable" label="Renewable"></q-tab>
      <!-- <q-tab name="trame" label="Trame"></q-tab> -->
    </q-tabs>

    <q-separator></q-separator>

    <q-tab-panels v-model="viewStore.viewId" animated style="height:100%">
      <q-tab-panel name="image">
        <ImageView></ImageView>
      </q-tab-panel>

      <q-tab-panel name="model">
        <ModelView></ModelView>
      </q-tab-panel>

      <q-tab-panel name="cad">
        <CadView></CadView>
      </q-tab-panel>

      <q-tab-panel name="jobs">
        <JobsView></JobsView>
      </q-tab-panel>

      <q-tab-panel name="results">
        <ResultsView></ResultsView>
      </q-tab-panel>

      <q-tab-panel name="plotly">
        <PlotlyView></PlotlyView>
      </q-tab-panel>

      <q-tab-panel name="json">
        <JsonView></JsonView>
      </q-tab-panel>

      <q-tab-panel name="renewable">
        <RenewableView></RenewableView>
      </q-tab-panel>

      <!-- <q-tab-panel name="trame">
        <iframe :src="viewStore.resultPort" width="100%" height="100%" frameborder="0" />
      </q-tab-panel> -->

    </q-tab-panels>

    <q-inner-loading :showing="viewStore.modelLoading">
      <q-spinner-gears size="50px" color="primary"></q-spinner-gears>
    </q-inner-loading>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import ImageView from 'components/views/ImageView.vue'
import ModelView from 'components/views/ModelView.vue'
import CadView from 'components/views/CadView.vue'
import JobsView from 'components/views/JobsView.vue'
import PlotlyView from 'components/views/PlotlyView.vue'
import JsonView from 'components/views/JsonView.vue'
import RenewableView from 'components/views/RenewableView.vue'
import ResultsView from 'components/views/ResultsView.vue'
import { useDefaultStore } from 'src/stores/default-store';
import { useViewStore } from 'src/stores/view-store';
import { useModelStore } from 'src/stores/model-store';

export default defineComponent({
  name: 'ViewComp',
  components: {
    ImageView,
    ModelView,
    CadView,
    JobsView,
    PlotlyView,
    JsonView,
    RenewableView,
    ResultsView
  },
  data() {
    return {
      viewHeight: '400px',
      tab: 'results',
    };
  },
  setup() {
    const store = useDefaultStore();
    const viewStore = useViewStore();
    const modelStore = useModelStore();
    const outputs = computed(() => modelStore.modelData.outputs)
    return {
      store,
      viewStore,
      outputs
    }
  },
  created() {
    this.$bus.on('resizeViewPanel', (height) => {
      this.viewHeight = height - 89 + 'px'
    })
  },
})
</script>
<style>
.q-tab-panel {
  padding: 0px;
}
</style>

// src/lib/components/ViewComp.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { Tabs } from 'bits-ui';
  import { defaultStore } from '$lib/stores/default-store.svelte';
  import { viewStore } from '$lib/stores/view-store.svelte';
  import { modelStore } from '$lib/stores/model-store.svelte';

  import ImageView from '$lib/components/views/ImageView.svelte';
  import ModelView from '$lib/components/views/ModelView.svelte';
  import ResultsView from '$lib/components/views/ResultsView.svelte';
  import CadView from '$lib/components/views/CadView.svelte';
  import JobsView from '$lib/components/views/JobsView.svelte';
  import PlotlyView from '$lib/components/views/PlotlyView.svelte';
  import RenewableView from '$lib/components/views/RenewableView.svelte';

  const outputs = $derived(modelStore.modelData.outputs ?? []);
  const showResults = $derived(outputs.some((o) => o.selectedFileType === 'Exodus'));
  const showPlotly = $derived(outputs.some((o) => o.selectedFileType === 'CSV'));

  const tabClass =
    'px-3 py-2 text-sm font-medium text-muted-foreground data-[state=active]:border-b-2 data-[state=active]:border-primary data-[state=active]:text-foreground';
</script>

<div class="flex h-full flex-col overflow-hidden rounded-lg border border-border">
  <Tabs.Root bind:value={viewStore.viewId} class="flex h-full flex-col">
    <Tabs.List class="flex flex-wrap justify-between border-b border-border bg-muted/40">
      <Tabs.Trigger value="image" class={tabClass}>Image</Tabs.Trigger>
      <Tabs.Trigger value="model" class={tabClass}>Model</Tabs.Trigger>
      <Tabs.Trigger value="cad" class={tabClass}>CAD</Tabs.Trigger>
      <Tabs.Trigger value="jobs" class={tabClass}>Jobs</Tabs.Trigger>
      {#if showResults}
        <Tabs.Trigger value="results" class={tabClass}>Results</Tabs.Trigger>
      {/if}
      {#if showPlotly}
        <Tabs.Trigger value="plotly" class={tabClass}>Plotly</Tabs.Trigger>
      {/if}
      {#if defaultStore.saveEnergy}
        <Tabs.Trigger value="renewable" class={tabClass}>Renewable</Tabs.Trigger>
      {/if}
    </Tabs.List>

    <div class="flex-1 overflow-auto">
      <Tabs.Content value="image" class="h-full"><ImageView /></Tabs.Content>
      <Tabs.Content value="model" class="h-full"><ModelView /></Tabs.Content>
      <Tabs.Content value="cad" class="h-full"><CadView /></Tabs.Content>
      <Tabs.Content value="jobs" class="h-full"><JobsView /></Tabs.Content>
      <Tabs.Content value="results" class="h-full"><ResultsView /></Tabs.Content>
      <Tabs.Content value="plotly" class="h-full"><PlotlyView /></Tabs.Content>
      <Tabs.Content value="renewable" class="h-full"><RenewableView /></Tabs.Content>
    </div>
  </Tabs.Root>
</div>
