// quasar-gui/app/src/pages/Publications.vue
<template>
    <q-page class="flex-center">
        <h1>Publications</h1>
        <ul>
          <q-list v-for="entry in bib_entries" :key="entry.entryTags.URL">
            <div v-if="entry.entryTags.Title">
              <div v-if="entry.entryTags.URL">
                <a :href="entry.entryTags.URL"
                  ><span class="title">{{ entry.entryTags.Title }}</span></a
                >
              </div>
              <div v-if="entry.entryTags.url">
                <a :href="entry.entryTags.url"
                  ><span class="title">{{ entry.entryTags.Title }}</span></a
                >
              </div>
              <div v-if="!entry.entryTags.url & !entry.entryTags.URL">
                <span class="title">{{ entry.entryTags.Title }}</span>
              </div>
            </div>
            <div v-if="entry.entryTags.title">
              <div v-if="entry.entryTags.URL">
                <a :href="entry.entryTags.URL"
                  ><span class="title">{{ entry.entryTags.title }}</span></a
                >
              </div>
              <div v-if="entry.entryTags.url">
                <a :href="entry.entryTags.url"
                  ><span class="title">{{ entry.entryTags.title }}</span></a
                >
              </div>
              <div v-if="!entry.entryTags.url & !entry.entryTags.URL">
                <span class="title">{{ entry.entryTags.title }}</span>
              </div>
            </div>
            <div v-if="entry.entryTags.Author">
              <span class="author">{{ entry.entryTags.Author }}</span>
            </div>
            <div v-if="entry.entryTags.author">
              <span class="author">{{ entry.entryTags.author }}</span>
            </div>
            <div>
              <span v-if="entry.entryTags.Journal"
                ><em
                  ><span class="journal">{{
                    entry.entryTags.Journal
                  }}</span></em
                >&nbsp;</span
              >
              <span v-if="entry.entryTags.journal"
                ><em
                  ><span class="journal">{{
                    entry.entryTags.journal
                  }}</span></em
                >&nbsp;</span
              >
              <span v-if="entry.entryTags.Month"
                ><span class="month">{{ entry.entryTags.Month }}</span
                >,&nbsp;</span
              >
              <span v-if="entry.entryTags.month"
                ><span class="month">{{ entry.entryTags.month }}</span
                >,&nbsp;</span
              >
              <span v-if="entry.entryTags.Year"
                ><span class="year">{{ entry.entryTags.Year }}</span></span
              >
              <span v-if="entry.entryTags.year"
                ><span class="year">{{ entry.entryTags.year }}</span></span
              >.
            </div>
          </q-list>
        </ul>
    </q-page>
</template>

<script>
import { api } from 'boot/axios'
import { defineComponent } from 'vue'
import bibtexParse from "bibtex-parse-js";


export default defineComponent({
    name: "PublicationPage",
    components: {
        // bibtexParse,
    },
    data() {
        return {
        bib_data: "",
        bib_entries: [],
        };
    },
    methods: {
        async getPublications() {

            api.get('/getPublications')
            .then((response) => {
                this.bib_data = this.latexToUtf(response.data)
                this.bib_entries = bibtexParse.toJSON(this.bib_data);
            })
            .catch((error) => {
                this.$q.notify({
                    type: 'negative',
                    message: error.response.data.detail
                })
            })
        },
        latexToUtf(string) {
            return string.replace(/{\\\"a}/gi, "ä");
        },
    },
    beforeMount() {
        this.getPublications();
    },
});
</script>

<style>
</style>

// src/routes/publications/+page.svelte
<!--
SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>

SPDX-License-Identifier: Apache-2.0
-->

<script lang="ts">
  import { onMount } from 'svelte';
  // @ts-expect-error no types shipped
  import bibtexParse from 'bibtex-parse-js';
  import { getPublications } from '$lib/client';
  import { notify } from '$lib/utils/notify';
  import Card from '$lib/components/ui/Card.svelte';

  interface BibEntry {
    entryTags: Record<string, string>;
  }

  let entries = $state<BibEntry[]>([]);

  function latexToUtf(input: string) {
    return input.replace(/{\\"a}/gi, 'ä');
  }

  function field(entry: BibEntry, ...keys: string[]) {
    for (const key of keys) {
      if (entry.entryTags[key]) return entry.entryTags[key];
    }
    return undefined;
  }

  onMount(async () => {
    try {
      const response = await getPublications();
      const bibData = latexToUtf(response as unknown as string);
      entries = bibtexParse.toJSON(bibData);
    } catch (error) {
      notify.apiError(error);
    }
  });
</script>

<svelte:head>
  <title>Publications — PeriHub</title>
</svelte:head>

<div class="mx-auto max-w-3xl space-y-4 px-6 py-10">
  <h1 class="text-2xl font-semibold tracking-tight">Publications</h1>

  {#each entries as entry (field(entry, 'URL', 'url', 'Title', 'title'))}
    {@const title = field(entry, 'Title', 'title')}
    {@const url = field(entry, 'URL', 'url')}
    {@const author = field(entry, 'Author', 'author')}
    {@const journal = field(entry, 'Journal', 'journal')}
    {@const month = field(entry, 'Month', 'month')}
    {@const year = field(entry, 'Year', 'year')}

    <Card class="p-4">
      {#if title}
        {#if url}
          <a href={url} class="font-medium text-primary hover:underline">{title}</a>
        {:else}
          <span class="font-medium">{title}</span>
        {/if}
      {/if}
      {#if author}
        <div class="mt-1 text-sm text-muted-foreground">{author}</div>
      {/if}
      <div class="mt-1 text-sm">
        {#if journal}<em>{journal}</em>&nbsp;{/if}
        {#if month}{month},&nbsp;{/if}
        {#if year}{year}{/if}.
      </div>
    </Card>
  {:else}
    <p class="text-muted-foreground">No publications found.</p>
  {/each}
</div>
